
// SPDX-License-Identifier: MIT
/*
This file is part of Collective Toolbox, a database and document workspace and utilities.
Copyright (C) 2026 Collective Toolbox Developers
Contact: info@collectivetoolbox.com

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the “Software”), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

/*
== License information for parts derived from kaitai_struct_tests, from https://raw.githubusercontent.com/kaitai-io/kaitai_struct_tests/59afee013e1a8e5fb894ca99838f55ef7b329cb3/LICENSE :

MIT License

Copyright (c) 2019 Kaitai Project

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.


*/


// @generated by ctb-formats-kaitai::codegen::test_generator
// Source: test_enum_long_range_s.rs

#![allow(
    unused_imports,
    unused_variables,
    non_snake_case,
    clippy::panic,
    clippy::expect_used,
    clippy::unwrap_used,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects,
    clippy::redundant_clone,
    reason = "Standard repository test boilerplate"
)]

use std::path::PathBuf;

use std::fs;
use kaitai::*;
use rust::formats::enum_long_range_s::*;

#[crate::ctb_test]
fn test_enum_long_range_s() -> KResult<()> {
    let manifest_dir = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let bytes = std::fs::read(manifest_dir.join("kaitai_struct_tests/src/enum_long_range_s.bin"))?;
    let _io = BytesReader::from(bytes);
    let r: OptRc<EnumLongRangeS> = EnumLongRangeS::read_into(&_io, None, None)?;

    assert_eq!(*r.f1(), EnumLongRangeS_Constants::LongMin);
    assert_eq!(*r.f2(), EnumLongRangeS_Constants::IntBelowMin);
    assert_eq!(*r.f3(), EnumLongRangeS_Constants::IntMin);
    assert_eq!(*r.f4(), EnumLongRangeS_Constants::Zero);
    assert_eq!(*r.f5(), EnumLongRangeS_Constants::IntMax);
    assert_eq!(*r.f6(), EnumLongRangeS_Constants::IntOverMax);
    assert_eq!(*r.f7(), EnumLongRangeS_Constants::LongMax);
    Ok(())
}
