;;; This file is part of Collective Toolbox, a database and document workspace and utilities.
;;; Copyright (C) 2026 Collective Toolbox Developers
;;; Contact: info@collectivetoolbox.com
;;;
;;; This Scheme program is free software; you can redistribute it and/or modify
;;; it under the terms of the GNU General Public License as published by the
;;; Free Software Foundation; either version 3 of the License, or (at your
;;; option) any later version.
;;;
;;; This Scheme program is distributed in the hope that it will be useful, but
;;; WITHOUT ANY WARRANTY; without even the implied warranty of
;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;;; GNU General Public License for more details.
;;;
;;; You should have received a copy of the GNU General Public License
;;; along with this Scheme program.  If not, see <http://www.gnu.org/licenses/>.

;;; Aggregator module for Guix package patches.

(define-module (patches)
  #:use-module (guix packages)
  #:use-module (ice-9 match)
  #:use-module (patches abseil-cpp)
  #:use-module (patches atkmm)
  #:use-module (patches at-spi2-core)
  #:use-module (patches colord)
  #:use-module (patches cups)
  #:use-module (patches dconf)
  #:use-module (patches dillo)
  #:use-module (patches ffmpeg)
  #:use-module (patches fig2dev)
  #:use-module (patches fltk)
  #:use-module (patches freeglut)
  #:use-module (patches gdk-pixbuf)
  #:use-module (patches gavl)
  #:use-module (patches glibmm)
  #:use-module (patches gnome-vfs)
  #:use-module (patches gst-plugins-good)
  #:use-module (patches gstreamer)
  #:use-module (patches gspell)
  #:use-module (patches graphene)
  #:use-module (patches graphviz)
  #:use-module (patches gtk)
  #:use-module (patches gtkmm)
  #:use-module (patches gnupg)
  #:use-module (patches gpgme)
  #:use-module (patches ibus)
  #:use-module (patches imagemagick)
  #:use-module (patches inkscape)
  #:use-module (patches json-glib)
  #:use-module (patches gusb)
  #:use-module (patches libaacs)
  #:use-module (patches libbluray)
  #:use-module (patches libcamera)
  #:use-module (patches lib2geom)
  #:use-module (patches libcddb)
  #:use-module (patches libcdio)
  #:use-module (patches libdbusmenu)
  #:use-module (patches libepoxy)
  #:use-module (patches libgudev)
  #:use-module (patches libgnome)
  #:use-module (patches libical)
  #:use-module (patches libidl)
  #:use-module (patches libnotify)
  #:use-module (patches libsoup)
  #:use-module (patches libsigc++)
  #:use-module (patches librsvg)
  #:use-module (patches libvpx)
  #:use-module (patches libx264)
  #:use-module (patches libxkbcommon)
  #:use-module (patches mesa)
  #:use-module (patches orbit2)
  #:use-module (patches pcsc-lite)
  #:use-module (patches phodav)
  #:use-module (patches pipewire)
  #:use-module (patches pulseaudio)
  #:use-module (patches poppler)
  #:use-module (patches polkit)
  #:use-module (patches qpdf)
  #:use-module (patches rest)
  #:use-module (patches shaderc)
  #:use-module (patches spice-gtk)
  #:use-module (patches srt)
  #:use-module (patches talloc)
  #:use-module (patches texlive-bin)
  #:use-module (patches usbredir)
  #:use-module (patches x265)
  #:use-module (patches xorg-server)
  #:use-module (patches xvfb-run)
  #:use-module (patches icecat)
  #:use-module (patches orc)
  #:use-module (patches qemu)
  #:use-module (patches vulkan-loader)
  #:use-module (patches virglrenderer)
  #:use-module (patches vala)
  #:use-module (patches webrtc-audio-processing)
  #:use-module (patches gsettings-desktop-schemas)
  #:use-module (patches gst-plugins-base)
  #:use-module (patches gobject-introspection)
  #:use-module (patches pango)
  #:use-module (patches glib)
  #:use-module (patches cairo)
  #:use-module (patches harfbuzz)
  #:use-module (patches wayland)
  #:use-module (patches alsa-lib)
  #:use-module (srfi srfi-1)
  #:export (apply-patches
            all-transitive-sources))

(define package-patches
  `(("abseil-cpp" . ,abseil-cpp-fixed-proc)
    ("alsa-lib" . ,alsa-lib-fixed-proc)
    ("atkmm" . ,atkmm-fixed-proc)
    ("atkmm-2.28" . ,atkmm-fixed-proc)
    ("atkmm-2.36" . ,atkmm-fixed-proc)
    ("at-spi2-core" . ,at-spi2-core-fixed-proc)
    ("cairo" . ,cairo-fixed-proc)
    ("webrtc-audio-processing" . ,webrtc-audio-processing-fixed-proc)
    ("webrtc-audio-processing-0.3" . ,webrtc-audio-processing-fixed-proc)
    ("harfbuzz" . ,harfbuzz-fixed-proc)
    ("wayland" . ,wayland-fixed-proc)
    ("colord-minimal" . ,colord-fixed-proc)
    ("colord" . ,colord-fixed-proc)
    ("glib" . ,glib-fixed-proc)
    ("gobject-introspection" . ,gobject-introspection-fixed-proc)
    ("gsettings-desktop-schemas" . ,gsettings-desktop-schemas-fixed-proc)
    ("cups-filters" . ,cups-filters-fixed-proc)
    ("cups-minimal" . ,cups-minimal-fixed-proc)
    ("cups" . ,cups-fixed-proc)
    ("dconf" . ,dconf-fixed-proc)
    ("dillo" . ,dillo-fixed-proc)
    ("ffmpeg" . ,ffmpeg-fixed-proc)
    ("fig2dev" . ,fig2dev-fixed-proc)
    ("fltk" . ,fltk-fixed-proc)
    ("freeglut" . ,freeglut-fixed-proc)
    ("gavl" . ,gavl-fixed-proc)
    ("gdk-pixbuf" . ,gdk-pixbuf-fixed-proc)
    ("gdk-pixbuf+svg" . ,gdk-pixbuf-fixed-proc)
    ("glibmm" . ,glibmm-fixed-proc)
    ("glibmm-2.66" . ,glibmm-fixed-proc)
    ("gnome-vfs" . ,gnome-vfs-fixed-proc)
    ("gnupg" . ,gnupg-fixed-proc)
    ("gpgme" . ,gpgme-fixed-proc)
    ("graphene" . ,graphene-fixed-proc)
    ("graphviz" . ,graphviz-fixed-proc)
    ("gspell" . ,gspell-fixed-proc)
    ("gst-plugins-base" . ,gst-plugins-base-fixed-proc)
    ("gst-plugins-good" . ,gst-plugins-good-fixed-proc)
    ("gstreamer" . ,gstreamer-fixed-proc)
    ("gtk" . ,gtk-fixed-proc)
    ("gtk+" . ,gtk+-fixed-proc)
    ("gtkmm" . ,gtkmm-fixed-proc)
    ("gusb-minimal" . ,gusb-fixed-proc)
    ("gusb" . ,gusb-fixed-proc)
    ("ibus" . ,ibus-fixed-proc)
    ("imagemagick" . ,imagemagick-fixed-proc)
    ("inkscape" . ,inkscape-fixed-proc)
    ("json-glib" . ,json-glib-fixed-proc)
    ("json-glib-minimal" . ,json-glib-fixed-proc)
    ("libaacs" . ,libaacs-fixed-proc)
    ("lib2geom" . ,lib2geom-fixed-proc)
    ("libbdplus" . ,libaacs-fixed-proc)
    ("libbluray" . ,libbluray-fixed-proc)
    ("libcamera" . ,libcamera-fixed-proc)
    ("libcamera-minimal" . ,libcamera-minimal-fixed-proc)
    ("libcddb" . ,libcddb-fixed-proc)
    ("libcdio" . ,libcdio-fixed-proc)
    ("libcdio-paranoia" . ,libcdio-fixed-proc)
    ("libdbusmenu" . ,libdbusmenu-fixed-proc)
    ("libepoxy" . ,libepoxy-fixed-proc)
    ("libgnome" . ,libgnome-fixed-proc)
    ("libgudev" . ,libgudev-fixed-proc)
    ("libical" . ,libical-fixed-proc)
    ("libidl" . ,libidl-fixed-proc)
    ("libnotify" . ,libnotify-fixed-proc)
    ("librsvg" . ,librsvg-fixed-proc)
    ("librsvg-2.40" . ,librsvg-fixed-proc)
    ("libsigc++" . ,libsigc++-fixed-proc)
    ("libsigc++-2" . ,libsigc++-fixed-proc)
    ("libsigc++-3" . ,libsigc++-fixed-proc)
    ("libsoup-minimal" . ,libsoup-minimal-fixed-proc)
    ("libsoup-minimal-2" . ,libsoup-minimal-2-fixed-proc)
    ("libsoup" . ,libsoup-fixed-proc)
    ("libvpx" . ,libvpx-fixed-proc)
    ("libx264" . ,libx264-fixed-proc)
    ("libxkbcommon" . ,libxkbcommon-fixed-proc)
    ("ldb" . ,ldb-fixed-proc)
    ("mesa" . ,mesa-libclc-pkg-config-fixed-proc)
    ("orbit2" . ,orbit2-fixed-proc)
    ("pango" . ,pango-fixed-proc)
    ("pcsc-lite" . ,pcsc-lite-fixed-proc)
    ("phodav" . ,phodav-fixed-proc)
    ("pipewire" . ,pipewire-fixed-proc)
    ("pulseaudio" . ,pulseaudio-fixed-proc)
    ("poppler" . ,poppler-fixed-proc)
    ("poppler-qt5" . ,poppler-fixed-proc)
    ("polkit" . ,polkit-fixed-proc)
    ("orc" . ,orc-fixed-proc)
    ("qpdf" . ,qpdf-fixed-proc)
    ("qemu" . ,qemu-fixed-proc)
    ("qemu-minimal" . ,qemu-fixed-proc)
    ("rest" . ,rest-fixed-proc)
    ("librest" . ,rest-fixed-proc)
    ("shaderc" . ,shaderc-fixed-proc)
    ("spice-gtk" . ,spice-gtk-fixed-proc)
    ("srt" . ,srt-fixed-proc)
    ("talloc" . ,talloc-fixed-proc)
    ("tdb" . ,tdb-fixed-proc)
    ("tevent" . ,tevent-fixed-proc)
    ("texlive-bin" . ,texlive-bin-fixed-proc)
    ("usbredir" . ,usbredir-fixed-proc)
    ("x265" . ,x265-fixed-proc)
    ("xorg-server" . ,xorg-server-fixed-proc)
    ("xorg-server-for-tests" . ,xorg-server-fixed-proc)
    ("xvfb-run" . ,xvfb-run-fixed-proc)
    ("icecat-minimal" . ,icecat-minimal-fixed-proc)
    ("icecat" . ,icecat-fixed-proc)
    ("vulkan-loader" . ,vulkan-loader-fixed-proc)
    ("vala" . ,vala-fixed-proc)
    ("virglrenderer" . ,virglrenderer-fixed-proc)))

(define (apply-patches root-pkg)
  (let ((table (make-hash-table)))
    (define (transform pkg)
      (if (not (package? pkg))
          pkg
          (or (hashq-ref table pkg)
              (let* ((name (package-name pkg))
                     (patch-proc (assoc-ref package-patches name))
                     (patched (if patch-proc (patch-proc pkg) pkg))
                     (rewritten
                      (package
                        (inherit patched)
                        (inputs (map (match-lambda
                                       ((label (? package? p) . rest)
                                        (cons* label (transform p) rest))
                                       ((? package? p)
                                        (transform p))
                                       (other other))
                                     (package-inputs patched)))
                        (propagated-inputs (map (match-lambda
                                                  ((label (? package? p) . rest)
                                                   (cons* label (transform p) rest))
                                                  ((? package? p)
                                                   (transform p))
                                                  (other other))
                                                (package-propagated-inputs patched)))
                        (native-inputs (map (match-lambda
                                              ((label (? package? p) . rest)
                                               (cons* label (transform p) rest))
                                              ((? package? p)
                                               (transform p))
                                              (other other))
                                            (package-native-inputs patched))))))
                (hashq-set! table pkg rewritten)
                rewritten))))
    (transform root-pkg)))

(define (all-transitive-sources packages)
  "Return a list of all source origins for PACKAGES and their transitive closure,
including all bootstrap toolchain origins."
  (let* ((closure (package-closure (filter package? packages)))
         (sources (filter-map package-source closure)))
    (delete-duplicates
     (filter origin? sources)
     (lambda (a b)
       (equal? (origin-uri a) (origin-uri b))))))
