#!/usr/bin/env bash

set -euo pipefail

# Change directory to the script's parent directory (the repo root)
cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" || exit 1

profile="--debug"
platform="linux-x64"

for arg in "$@"; do
    if [[ "$arg" == "--release" ]]; then
        profile="--release"
    elif [[ "$arg" == "--debug" ]]; then
        profile="--debug"
    elif [[ "$arg" == "windows-amd64" ]]; then
        platform="windows-x64"
    else
        platform="$arg"
    fi
done

./build --quick --no-test $profile "$platform" || exit 1
