doc-valid-idents = ["StageL", "StageR", "UserLand", "AppleScript", "AppleSingle", "AppleDouble", "ProDOS", "QuickDraw", "FInfo", "FXInfo", "SITx", "CRLite", "SQLite", "WebPKI", "DcText", "DcArray", "DcId", "DcList", "DcUtf", "DcUTF", "DcIds", "DcString", "SeaBIOS", "MathML", "AlphaSmart", ".."]
allowed-wildcard-imports = [ "utilities" ]
allow-unwrap-in-tests = true
allow-expect-in-tests = true
allow-panic-in-tests = true
allow-indexing-slicing-in-tests = true
allow-dbg-in-tests = true