#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This file is part of Collective Toolbox, a database and document workspace and utilities.
# Copyright (C) 2026 Collective Toolbox Developers
# Contact: info@collectivetoolbox.com
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program.  If not, see <https://www.gnu.org/licenses/>.
set -euo pipefail

# Note for agents: for Clippy lints specifically, it's worth giving `RUSTFLAGS="-A warnings" cargo clippy --workspace --all-targets --keep-going` a try and get that clean before running this script.
# Also note that there's a `--quick` option for this script that will make it run more quickly.

# Change directory to the script's parent directory (the repo root)
cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" || exit 1

./scripts/lint "$@" || exit 1
