#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This file is part of Collective Toolbox, a database and document workspace and utilities.
# Copyright (C) 2026 Collective Toolbox Developers
# Contact: info@collectivetoolbox.com
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program.  If not, see <https://www.gnu.org/licenses/>.
set -euo pipefail

cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/" || exit 1

target="${1:-}"
extra_args=()

case "$target" in
	github)
		shift
		extra_args=("$@")
		;;
	all)
		shift
		extra_args=("$@")
		target=""
		;;
	-h|--help)
		echo "Usage: $0 [github|all] [git-push-options...]"
		exit 0
		;;
	*)
		if [[ -n "$target" && "$target" =~ ^- ]]; then
			target=""
			extra_args=("$@")
		elif [[ -n "$target" ]]; then
			echo "Error: Unknown target '$target'. Usage: $0 [github|all] [git-push-options...]" >&2
			exit 1
		fi
		;;
esac

push_repo() {
	local dir="$1"
	pushd "$dir" || exit 1
	if [[ "$target" == "github" ]]; then
		git push github ${extra_args+"${extra_args[@]}"}
	else
		git push ${extra_args+"${extra_args[@]}"}
		git push all ${extra_args+"${extra_args[@]}"}
	fi
	popd || exit 1
}

push_repo vendor/ctb-vendored/
push_repo vendor/
push_repo packaging/homebrew-tap/
push_repo .

