#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This file is part of Collective Toolbox, a database and document workspace and utilities.
# Copyright (C) 2026 Collective Toolbox Developers
# Contact: info@collectivetoolbox.com
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program.  If not, see <https://www.gnu.org/licenses/>.
# This is meant to be a hot-reload watcher for development. Unfortunately it no longer works practically, as the build time has grown. If I can pull down the build time, this could get resurrected.
# Needs inotify-tools package

set -euxo pipefail

cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" || exit 1


./run-web &

disown -a

# https://superuser.com/questions/181517/how-to-execute-a-command-whenever-a-file-changes
cd src
echo "$(pwd)"
inotifywait -re close_write,moved_to,create -m . |
#inotifywait -m . |
while read -r directory events filename; do
    echo "Event: $filename $directory $events"
    if [[ "$directory" =~ ./built/.* ]] || [[ "$filename" == ".keep" ]] || [[ "$directory" =~ .*/pkg/ ]]; then
        echo "Skipping $filename"
        continue
    fi
    echo "Event accepted: $filename $directory $events"
    # https://stackoverflow.com/questions/28195821/how-can-i-interrupt-or-debounce-an-inotifywait-loop
    jobs -p | xargs kill || true
    (
        pushd .. || exit 1
        ./build --wasm &
        popd || exit 1
    ) &
    echo "Skipping $(timeout 5 cat | wc -l) further changes"
done