// SPDX-License-Identifier: AGPL-3.0-or-later AND MIT
// SPDX-License-Identifier for parts derived from kaitai_struct_tests: MIT
/*
This file is part of Collective Toolbox, a database and document workspace and utilities.
Copyright (C) 2026 Collective Toolbox Developers
Contact: info@collectivetoolbox.com

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along
with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Parts derived from kaitai_struct_tests (see full license information at the end of this file):
// Copyright (c) 2019 Kaitai Project

//! Test generator that transforms upstream Kaitai Struct test files into
//! repository-compliant Rust tests with caching support.
const LICENSE_HEADER: &str = r#"
// SPDX-License-Identifier: MIT
// license-linter:allow-non-AGPL
/*
This file is part of Collective Toolbox, a database and document workspace and utilities.
Copyright (C) 2026 Collective Toolbox Developers
Contact: info@collectivetoolbox.com

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the “Software”), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

/*
== License information for parts derived from kaitai_struct_tests, from https://raw.githubusercontent.com/kaitai-io/kaitai_struct_tests/59afee013e1a8e5fb894ca99838f55ef7b329cb3/LICENSE :

MIT License

Copyright (c) 2019 Kaitai Project

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.


*/
"#;
#[allow(
    unused_imports,
    clippy::wildcard_imports,
    reason = "Standard workspace module prelude"
)]
use crate::utilities::*;

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::UNIX_EPOCH;
use walkdir::WalkDir;

use crate::precompile::hierarchy::to_upper_camel_case;
use crate::spec::kst::{parse_kst_file, KstException, KstSpec};
use crate::spec::KsyFile;

/// Statistics reporting the results of test generation.
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct GenerationStats {
    /// Number of tests regenerated from source files.
    pub generated_count: usize,
    /// Number of tests skipped because the cached output is up to date.
    pub cache_hits: usize,
    /// Total number of candidate test files discovered.
    pub total_discovered: usize,
}

/// Checks if a source test file contains the upstream autogenerated marker.
#[must_use]
pub fn has_autogenerated_marker(content: &str) -> bool {
    content
        .lines()
        .take(5)
        .any(|line| line.contains("Autogenerated from KST"))
}

/// Helper to write file only if contents differ, avoiding timestamp updates.
fn write_if_changed(path: &Path, content: &str) -> Result<()> {
    if path.exists() {
        if let Ok(existing) = fs::read_to_string(path) {
            if existing == content {
                return Ok(());
            }
        }
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, content)?;
    Ok(())
}

/// Transforms an upstream Kaitai Rust test file content into repository-compliant
/// Rust test code.
pub fn transform_test_content(src_name: &str, content: &str) -> Result<String> {
    let mut lines_out = Vec::new();
    let mut has_pathbuf = false;
    let mut has_context = false;

    for line in content.lines() {
        let trimmed = line.trim();

        // 1. Skip autogenerated comment from KST
        if trimmed.starts_with("// Autogenerated from KST") {
            continue;
        }

        // 2. Skip extern crate kaitai
        if trimmed.starts_with("extern crate kaitai;") {
            continue;
        }

        // 3. Transform imports
        let mut modified = line.to_string();
        if trimmed == "use self::kaitai::*;" {
            modified = line.replace("use self::kaitai::*;", "use kaitai::*;");
        }

        // 4. Transform #[test] to #[crate::ctb_test]
        if trimmed == "#[test]" {
            modified = line.replace("#[test]", "#[crate::ctb_test]");
        }

        // 5. Transform data read line:
        // let bytes = fs::read("../../src/<name>.bin").unwrap();
        if trimmed.starts_with("let bytes = fs::read(") && trimmed.contains("../../src/") {
            if let Some(start) = trimmed.find("../../src/") {
                let after_prefix = &trimmed[start.saturating_add(10)..];
                if let Some(end) = after_prefix.find(".bin\").unwrap();") {
                    let bin_name = &after_prefix[..end.saturating_add(4)];
                    let indent = line.len().saturating_sub(line.trim_start().len());
                    let pad = &line[..indent];
                    lines_out.push(format!(
                        "{pad}let manifest_dir = std::path::PathBuf::from(env!(\"CARGO_MANIFEST_DIR\"));"
                    ));
                    modified = format!(
                        "{pad}let bytes = std::fs::read(manifest_dir.join(\"kaitai_struct_tests/src/{bin_name}\"))?;"
                    );
                    has_pathbuf = true;
                }
            }
        }

        // 6. Transform as casts
        if modified.contains(" as usize") {
            modified = modified.replace(" as usize", "");
        }
        if modified.contains("(0.5 as f32)") {
            modified = modified.replace("(0.5 as f32)", "0.5_f32");
        }
        if modified.contains("(1 + 4) as i32") {
            modified = modified.replace("(1 + 4) as i32", "(1_i32.saturating_add(4_i32))");
        }
        if modified.contains("(2 as i32)") {
            modified = modified.replace("(2 as i32)", "2_i32");
        }
        if modified.contains("(4 as i32)") {
            modified = modified.replace("(4 as i32)", "4_i32");
        }

        // 7. Transform unwraps on tag_content
        if modified.contains(".as_ref().unwrap()") {
            modified = modified.replace(".as_ref().unwrap()", ".as_ref().context(\"Missing optional field\")?");
            has_context = true;
        }

        lines_out.push(modified);
    }

    let mut out = String::with_capacity(content.len().saturating_add(512));

    // File header
    out.push_str(LICENSE_HEADER);
    out.push_str("\n\n// @generated by ctb-formats-kaitai::codegen::test_generator\n");
    out.push_str(&format!("// Source: {src_name}\n\n"));

    // Lint boilerplate
    out.push_str("#![allow(\n");
    out.push_str("    unused_imports,\n");
    out.push_str("    unused_variables,\n");
    out.push_str("    non_snake_case,\n");
    out.push_str("    clippy::panic,\n");
    out.push_str("    clippy::expect_used,\n");
    out.push_str("    clippy::unwrap_used,\n");
    out.push_str("    clippy::indexing_slicing,\n");
    out.push_str("    clippy::arithmetic_side_effects,\n");
    out.push_str("    clippy::redundant_clone,\n");
    out.push_str("    reason = \"Standard repository test boilerplate\"\n");
    out.push_str(")]\n\n");

    if has_pathbuf {
        out.push_str("use std::path::PathBuf;\n");
    }
    if has_context {
        out.push_str("use anyhow::Context;\n");
    }

    out.push_str(&lines_out.join("\n"));
    if !out.ends_with('\n') {
        out.push('\n');
    }
    Ok(out)
}

/// Formats a `.kst` expected value into a Rust expression string.
#[must_use]
pub fn format_expected_expr(expected: &serde_yaml::Value, current_format: &str) -> String {
    match expected {
        serde_yaml::Value::Bool(b) => b.to_string(),
        serde_yaml::Value::Number(n) => {
            if let Some(i) = n.as_i64() {
                format!("{i}")
            } else if let Some(u) = n.as_u64() {
                format!("{u}")
            } else if let Some(f) = n.as_f64() {
                format!("{f}")
            } else {
                format!("{n}")
            }
        }
        serde_yaml::Value::String(s) => {
            let trimmed = s.trim();
            if trimmed.starts_with('[') && trimmed.ends_with(']') {
                let inner = &trimmed[1..trimmed.len().saturating_sub(1)];
                let items: Vec<String> = inner
                    .split(',')
                    .map(|item| {
                        let item = item.trim();
                        if item.starts_with("0x") || item.starts_with("0X") {
                            format!("{item}u8")
                        } else if let Ok(num) = item.parse::<u8>() {
                            format!("{num}u8")
                        } else {
                            item.to_string()
                        }
                    })
                    .collect();
                format!("vec![{}]", items.join(", "))
            } else if s.contains("::") {
                let parts: Vec<&str> = s.split("::").collect();
                if parts.len() == 3 {
                    let fmt = to_upper_camel_case(parts[0]);
                    let enum_name = to_upper_camel_case(parts[1]);
                    let variant = to_upper_camel_case(parts[2]);
                    format!("{fmt}_{enum_name}::{variant}")
                } else if parts.len() == 2 {
                    let fmt = to_upper_camel_case(current_format);
                    let enum_name = to_upper_camel_case(parts[0]);
                    let variant = to_upper_camel_case(parts[1]);
                    format!("{fmt}_{enum_name}::{variant}")
                } else {
                    s.clone()
                }
            } else {
                format!("{s:?}")
            }
        }
        serde_yaml::Value::Sequence(seq) => {
            let items: Vec<String> = seq
                .iter()
                .map(|v| format_expected_expr(v, current_format))
                .collect();
            format!("vec![{}]", items.join(", "))
        }
        _ => format!("{expected:?}"),
    }
}

/// Formats a `.kst` actual path expression into a Rust method chain on root `r`.
#[must_use]
pub fn format_actual_expr(actual: &str, ksy: Option<&KsyFile>) -> String {
    let parts: Vec<&str> = actual.split('.').collect();
    if parts.is_empty() {
        return "r".to_string();
    }

    let is_len = parts.last().is_some_and(|p| *p == "size" || *p == "length");
    let mut call_chain = String::new();
    let mut current_ksy = ksy;

    for part in &parts {
        if *part == "size" || *part == "length" {
            call_chain.push_str(".len()");
            continue;
        }

        if let Some(bracket_pos) = part.find('[') {
            if let Some(end_bracket) = part.find(']') {
                let field_name = &part[..bracket_pos];
                let index_str = &part[bracket_pos.saturating_add(1)..end_bracket];

                let is_inst = current_ksy
                    .map(|k| k.instances.contains_key(field_name))
                    .unwrap_or(false);

                if is_inst {
                    call_chain.push_str(&format!(".{field_name}()?[{index_str}]"));
                } else {
                    call_chain.push_str(&format!(".{field_name}()[{index_str}]"));
                }

                if let Some(k) = current_ksy {
                    if let Some(child_file) = k.types.get(field_name) {
                        current_ksy = Some(child_file);
                    }
                }
                continue;
            }
        }

        if part.starts_with("as<") && part.ends_with('>') {
            call_chain.push_str(".as_ref().context(\"Missing optional field\")?");
            continue;
        }

        let is_inst = current_ksy
            .map(|k| k.instances.contains_key(*part))
            .unwrap_or(false);

        if is_inst {
            call_chain.push_str(&format!(".{part}()?"));
        } else {
            call_chain.push_str(&format!(".{part}()"));
        }

        if let Some(k) = current_ksy {
            if let Some(child_file) = k.types.get(*part) {
                current_ksy = Some(child_file);
            }
        }
    }

    if is_len {
        format!("r{call_chain}")
    } else {
        format!("*r{call_chain}")
    }
}

/// Synthesizes a Rust unit test source string directly from a `.kst` specification.
///
/// # Errors
/// Returns an error if the `.kst` file cannot be read or parsed.
pub fn synthesize_test_from_kst(
    kst_path: &Path,
    formats_dir: Option<&Path>,
) -> Result<String> {
    let kst = parse_kst_file(kst_path)?;
    let kst_name = kst_path
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or("test.kst");

    let root_type = to_upper_camel_case(&kst.id);
    let mod_name = &kst.id;

    let mut out = String::with_capacity(2048);
    out.push_str(LICENSE_HEADER);
    out.push_str("\n\n// @generated by ctb-formats-kaitai::codegen::test_generator from KST specification\n");
    out.push_str(&format!("// Source: {kst_name}\n\n"));

    out.push_str("#![allow(\n");
    out.push_str("    unused_imports,\n");
    out.push_str("    unused_variables,\n");
    out.push_str("    non_snake_case,\n");
    out.push_str("    clippy::panic,\n");
    out.push_str("    clippy::expect_used,\n");
    out.push_str("    clippy::unwrap_used,\n");
    out.push_str("    clippy::indexing_slicing,\n");
    out.push_str("    clippy::arithmetic_side_effects,\n");
    out.push_str("    clippy::redundant_clone,\n");
    out.push_str("    reason = \"Standard repository test boilerplate\"\n");
    out.push_str(")]\n\n");

    out.push_str("use std::path::PathBuf;\n");
    out.push_str("use anyhow::Context;\n");
    out.push_str("use std::fs;\n");
    out.push_str("use kaitai::*;\n");
    out.push_str(&format!("use rust::formats::{mod_name}::*;\n\n"));

    out.push_str("#[crate::ctb_test]\n");
    out.push_str(&format!("fn test_{mod_name}() -> KResult<()> {{\n"));

    if let Some(data_file) = &kst.data {
        out.push_str("    let manifest_dir = std::path::PathBuf::from(env!(\"CARGO_MANIFEST_DIR\"));\n");
        out.push_str(&format!(
            "    let bytes = std::fs::read(manifest_dir.join(\"kaitai_struct_tests/src/{data_file}\"))?;\n"
        ));
        out.push_str("    let _io = BytesReader::from(bytes);\n");
    }

    if let Some(exc) = &kst.exception {
        out.push_str(&format!(
            "    let res: KResult<OptRc<{root_type}>> = {root_type}::read_into(&_io, None, None);\n"
        ));
        out.push_str("    let err = res.expect_err(\"expected Err, but got Ok\");\n");
        let exc_name = match exc {
            KstException::Simple(s) => s.as_str(),
            KstException::Detailed { r#type, .. } => r#type.as_str(),
        };
        if exc_name.starts_with("Validation") {
            out.push_str("    assert!(matches!(err, KError::ValidationFailed(..)), \"expected validation error, got: {:?}\", err);\n");
        } else if exc_name.contains("EndOfStream") || exc_name.contains("Eof") || exc_name.contains("Eos") {
            out.push_str("    assert!(matches!(err, KError::Io(..) | KError::ValidationFailed(..)), \"expected EOF/Io error, got: {:?}\", err);\n");
        } else if exc_name.contains("UndecidedEndianness") {
            out.push_str("    assert!(matches!(err, KError::UndecidedEndianness { .. }), \"expected UndecidedEndianness error, got: {:?}\", err);\n");
        } else {
            out.push_str("    let _ = err;\n");
        }
    } else {
        out.push_str(&format!(
            "    let r: OptRc<{root_type}> = {root_type}::read_into(&_io, None, None)?;\n\n"
        ));

        let ksy = if let Some(dir) = formats_dir {
            let ksy_path = dir.join(format!("{mod_name}.ksy"));
            if ksy_path.exists() {
                if let Ok(content) = fs::read_to_string(&ksy_path) {
                    crate::parser::parse_ksy_str(&content).ok()
                } else {
                    None
                }
            } else {
                None
            }
        } else {
            None
        };

        for assert in &kst.asserts {
            let actual_str = match &assert.actual {
                serde_yaml::Value::String(s) => s.clone(),
                v => format!("{v:?}"),
            };

            if let Some(exc) = &assert.exception {
                out.push_str(&format!("    // Exception expected on {actual_str}: {exc}\n"));
                continue;
            }

            if let Some(expected_val) = &assert.expected {
                let actual_expr = format_actual_expr(&actual_str, ksy.as_ref());
                let expected_expr = format_expected_expr(expected_val, mod_name);
                out.push_str(&format!("    assert_eq!({actual_expr}, {expected_expr});\n"));
            }
        }
    }

    out.push_str("    Ok(())\n");
    out.push_str("}\n");

    Ok(out)
}

/// Regenerates all Kaitai Struct tests from `.kst` specifications in `kst_dir`,
/// writing `.generated.rs` test files into `out_dir` with caching via `cache_file`.
///
/// # Errors
/// Returns an error if directory traversal or code generation fails.
pub fn regenerate_tests_from_kst(
    kst_dir: &Path,
    out_dir: &Path,
    formats_dir: Option<&Path>,
    cache_file: &Path,
    force: bool,
) -> Result<GenerationStats> {
    let mut stats = GenerationStats::default();

    if !kst_dir.exists() {
        return Ok(stats);
    }

    fs::create_dir_all(out_dir)?;

    let mut cache: HashMap<String, (u128, u64)> = HashMap::new();
    if !force && cache_file.exists() {
        if let Ok(cache_str) = fs::read_to_string(cache_file) {
            for line in cache_str.lines() {
                let parts: Vec<&str> = line.split('\t').collect();
                if parts.len() == 3 {
                    if let (Ok(mtime), Ok(size)) = (parts[1].parse(), parts[2].parse()) {
                        cache.insert(parts[0].to_string(), (mtime, size));
                    }
                }
            }
        }
    }

    let mut updated_cache = cache.clone();

    for entry in WalkDir::new(kst_dir) {
        let entry = entry?;
        let path = entry.path();

        if !path.is_file() {
            continue;
        }

        let file_name = path
            .file_name()
            .and_then(|s| s.to_str())
            .unwrap_or_default();

        if !file_name.ends_with(".kst") {
            continue;
        }

        stats.total_discovered = stats.total_discovered.saturating_add(1);

        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or_default();

        let target_name = format!("test_{stem}.generated.rs");
        let target_path = out_dir.join(&target_name);

        let metadata = fs::metadata(path)?;
        let mtime = metadata
            .modified()?
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_nanos();
        let size = metadata.len();

        let rel_key = path
            .strip_prefix(kst_dir)
            .unwrap_or(path)
            .to_string_lossy()
            .to_string();

        if !force && target_path.exists() {
            if let Some((cached_mtime, cached_size)) = cache.get(&rel_key) {
                if *cached_mtime == mtime && *cached_size == size {
                    stats.cache_hits = stats.cache_hits.saturating_add(1);
                    continue;
                }
            }
        }

        let generated_code = synthesize_test_from_kst(path, formats_dir)?;
        write_if_changed(&target_path, &generated_code)?;
        updated_cache.insert(rel_key, (mtime, size));
        stats.generated_count = stats.generated_count.saturating_add(1);
    }

    let mut cache_str = String::new();
    for (k, (mtime, size)) in &updated_cache {
        cache_str.push_str(&format!("{k}\t{mtime}\t{size}\n"));
    }
    write_if_changed(cache_file, &cache_str)?;

    Ok(stats)
}

/// Regenerates all Kaitai Struct tests in `src_dir`, writing `.generated.rs` files
/// into `out_dir` with caching via `cache_file`.
pub fn regenerate_tests(
    src_dir: &Path,
    out_dir: &Path,
    cache_file: &Path,
    force: bool,
) -> Result<GenerationStats> {
    let has_kst = WalkDir::new(src_dir)
        .max_depth(1)
        .into_iter()
        .filter_map(std::result::Result::ok)
        .any(|e| e.path().extension().is_some_and(|ext| ext == "kst"));

    if has_kst {
        let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let formats_dir = manifest_dir.join("kaitai_struct_tests/formats");
        return regenerate_tests_from_kst(src_dir, out_dir, Some(&formats_dir), cache_file, force);
    }

    let mut stats = GenerationStats::default();

    if !src_dir.exists() {
        return Ok(stats);
    }

    fs::create_dir_all(out_dir)?;

    // 1. Load build cache
    let mut cache: HashMap<String, (u128, u64)> = HashMap::new();
    if !force && cache_file.exists() {
        if let Ok(cache_str) = fs::read_to_string(cache_file) {
            for line in cache_str.lines() {
                let parts: Vec<&str> = line.split('\t').collect();
                if parts.len() == 3 {
                    if let (Ok(mtime), Ok(size)) = (parts[1].parse(), parts[2].parse()) {
                        cache.insert(parts[0].to_string(), (mtime, size));
                    }
                }
            }
        }
    }

    let mut updated_cache = cache.clone();

    // 2. Discover test_*.rs files (excluding already generated files)
    for entry in WalkDir::new(src_dir) {
        let entry = entry?;
        let path = entry.path();

        if !path.is_file() {
            continue;
        }

        let file_name = path
            .file_name()
            .and_then(|s| s.to_str())
            .unwrap_or_default();

        if !file_name.starts_with("test_") || !file_name.ends_with(".rs") {
            continue;
        }

        // Skip files that are already generated
        if file_name.ends_with(".generated.rs") {
            continue;
        }

        stats.total_discovered = stats.total_discovered.saturating_add(1);

        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or_default();

        let target_name = format!("{stem}.generated.rs");
        let target_path = out_dir.join(&target_name);

        let metadata = fs::metadata(path)?;
        let mtime = metadata
            .modified()?
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_nanos();
        let size = metadata.len();

        let rel_key = path
            .strip_prefix(src_dir)
            .unwrap_or(path)
            .to_string_lossy()
            .to_string();

        // 3. Cache hit check
        if !force && target_path.exists() {
            if let Some((cached_mtime, cached_size)) = cache.get(&rel_key) {
                if *cached_mtime == mtime && *cached_size == size {
                    stats.cache_hits = stats.cache_hits.saturating_add(1);
                    continue;
                }
            }
        }

        // 4. Regenerate content
        let content = fs::read_to_string(path)?;
        let transformed = transform_test_content(file_name, &content)?;

        write_if_changed(&target_path, &transformed)?;
        updated_cache.insert(rel_key, (mtime, size));
        stats.generated_count = stats.generated_count.saturating_add(1);
    }

    // 5. Write updated build cache
    let mut cache_str = String::new();
    for (k, (mtime, size)) in &updated_cache {
        cache_str.push_str(&format!("{k}\t{mtime}\t{size}\n"));
    }
    write_if_changed(cache_file, &cache_str)?;

    Ok(stats)
}

/// Deletes the upstream test files that have been verified to have matching
/// `.generated.rs` files, explicitly preserving any files that omit the autogenerated
/// marker.
pub fn remove_verified_autogenerated_originals(tests_dir: &Path) -> Result<usize> {
    let mut removed_count: usize = 0;

    for entry in WalkDir::new(tests_dir) {
        let entry = entry?;
        let path = entry.path();

        if !path.is_file() {
            continue;
        }

        let file_name = path
            .file_name()
            .and_then(|s| s.to_str())
            .unwrap_or_default();

        if !file_name.starts_with("test_") || !file_name.ends_with(".rs") {
            continue;
        }

        // Never touch generated files
        if file_name.ends_with(".generated.rs") {
            continue;
        }

        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or_default();

        let target_generated = tests_dir.join(format!("{stem}.generated.rs"));

        // Only consider deletion if the replacement .generated.rs exists
        if !target_generated.exists() {
            continue;
        }

        // Check if this file has the autogenerated marker
        let content = fs::read_to_string(path)?;
        if !has_autogenerated_marker(&content) {
            // Preserve files that omit the marker
            continue;
        }

        // Remove the verified original autogenerated file explicitly
        fs::remove_file(path)?;
        removed_count = removed_count.saturating_add(1);
    }

    Ok(removed_count)
}

/*
== License information for parts derived from kaitai_struct_tests, from https://raw.githubusercontent.com/kaitai-io/kaitai_struct_tests/59afee013e1a8e5fb894ca99838f55ef7b329cb3/LICENSE :

MIT License

Copyright (c) 2019 Kaitai Project

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.


*/