// SPDX-License-Identifier: AGPL-3.0-or-later
/*
This file is part of Collective Toolbox, a database and document workspace and utilities.
Copyright (C) 2026 Collective Toolbox Developers
Contact: info@collectivetoolbox.com

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along
with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

//! Constants and definitions for Document Character (Dc) data.
//! @generated by ctb-formats-dcdata::updater from category data tables.
//! Do not edit by hand.

#[expect(
    unused_imports,
    clippy::wildcard_imports,
    reason = "Standard workspace module prelude"
)]
use crate::utilities::*;

pub use ctb_storage_minimal::global_graph_layout::{
    SHORT_DC_REGION_END, SHORT_DC_REGION_START,
};

pub use crate::dc_char::DcChar;

/// Begin a DCE number. (Dc 6).
pub const DC_BEGIN_NUMBER: DcChar = DcChar::from_short(6);
/// End a DCE number. (Dc 7).
pub const DC_END_NUMBER: DcChar = DcChar::from_short(7);
/// Positive value (syntactical representation — This is not the + character) (Dc 10).
pub const DC_POSITIVE: DcChar = DcChar::from_short(10);
/// Negative (syntactical representation — This is not the − character) (Dc 11).
pub const DC_NEGATIVE: DcChar = DcChar::from_short(11);
/// Base 64 encapsulation digit 0 (Dc 127).
pub const DC_BASE64_START: DcChar = DcChar::from_short(127);
/// Base 64 encapsulation digit 63 (Dc 190).
pub const DC_BASE64_END: DcChar = DcChar::from_short(190);
/// Begin Base 64 encapsulated UTF-8 (Dc 191).
pub const DC_START_ENCAPSULATION_UTF8: DcChar = DcChar::from_short(191);
/// End Base 64 encapsulated UTF-8 (Dc 192).
pub const DC_END_ENCAPSULATION_UTF8: DcChar = DcChar::from_short(192);
/// Base 64 encapsulation padding character (Dc 195).
pub const DC_BASE64_PADDING: DcChar = DcChar::from_short(195);
/// Arbitrary binary data (base64 encoded, no semantic significance assigned to it) (Dc 203).
pub const DC_START_ENCAPSULATION_BINARY: DcChar = DcChar::from_short(203);
/// See description for 203 (Dc 204).
pub const DC_END_ENCAPSULATION_BINARY: DcChar = DcChar::from_short(204);
/// Used to replace an incoming character whose value is unknown or unrepresentable in Unicode (Dc 206).
pub const DC_REPLACEMENT_UNAVAIL_UNICODE: DcChar = DcChar::from_short(206);
/// Used to replace an incoming character whose value is not mapped to a Dc (document component) (Dc 207).
pub const DC_REPLACEMENT_UNAVAIL_DC: DcChar = DcChar::from_short(207);
/// Indicates that the next character should be ignored. (Dc 255).
pub const DC_ESCAPE: DcChar = DcChar::from_short(255);
/// Used to embed Dcs with short numbers greater than 1,114,111 (the largest, in practice, that EITE would be able to support without needing changes to pack32, I think) into short Dc range. If encountered as a long Dc, it must be escaped with 255 before converting to short Dc, or else it would be lost (if followed by a Dc number) when converting back. (Dc 308).
pub const DC_LONG_DC: DcChar = DcChar::from_short(308);
/// Begins an ordered, contiguous, typed homogenous or heterogenous list. (Dc 310).
pub const DC_BEGIN_LIST: DcChar = DcChar::from_short(310);
/// Terminates a typed list begun by 310. Optionally, a length can be specified, in which case it must have that many elements declared. (Dc 311).
pub const DC_END_LIST: DcChar = DcChar::from_short(311);
/// Begins an ordered key-value associative map. (Dc 313).
pub const DC_BEGIN_KV_MAP: DcChar = DcChar::from_short(313);
/// Terminates an ordered key-value associative map begun by 313. (Dc 314).
pub const DC_END_KV_MAP: DcChar = DcChar::from_short(314);
/// Indicates an optional value is present. (Dc 315).
pub const DC_OPTIONAL_PRESENT: DcChar = DcChar::from_short(315);
/// Indicates an optional value is absent. (Dc 316).
pub const DC_OPTIONAL_ABSENT: DcChar = DcChar::from_short(316);
/// Indicates that all values within the list have the same underlying meaning. (Dc 397).
pub const DC_EQUIVALENT_REPRESENTATIONS: DcChar = DcChar::from_short(397);
/// Boolean true (Dc 517).
pub const DC_BOOLEAN_TRUE: DcChar = DcChar::from_short(517);
/// Boolean false (Dc 518).
pub const DC_BOOLEAN_FALSE: DcChar = DcChar::from_short(518);

/// Converts a short Document Character (Dc) ID to its long (Global Graph) ID.
#[must_use]
pub fn short_to_long_dc(short_id: u32) -> u128 {
    SHORT_DC_REGION_START.saturating_add(u128::from(short_id))
}

/// Converts a long (Global Graph) Document Character ID to its short Dc ID, if within short range.
#[must_use]
pub fn long_to_short_dc(dc_id: u128) -> Option<u32> {
    if (SHORT_DC_REGION_START..=SHORT_DC_REGION_END).contains(&dc_id) {
        u32::try_from(dc_id.saturating_sub(SHORT_DC_REGION_START)).ok()
    } else {
        None
    }
}
