.TH man 1 "31 Aug 2025" "0.1.0" "ctoolbox man page"
.SH NAME
ctoolbox \- the Collective Toolbox for egalitarian, compassionate, community-minded computing
.SH SYNOPSIS
ctoolbox

ctoolbox help

ctoolbox tools hex2dec [INPUT]

ctoolbox tools dec2hex [INPUT]
.SH DESCRIPTION
ctoolbox is the binary of the CollectiveToolbox environment for computing.
.SH OPTIONS

.SH SEE ALSO
 
.SH BUGS
No known bugs.
.SH AUTHOR
Collective Toolbox
