[package]
name = "ctb-build-info"
edition = "2024"

[lib]
path = "build_info.rs"
crate-type = ["lib"]

[dependencies]
ctb-utilities = { path = "../utilities" }
serde = { version = "1.0.228", features = ["derive"] }

[build-dependencies]
anyhow = "1.0.100"
cargo_metadata = "0.23.1"
vergen-gix = { version = "9.1.0", features = ["build", "cargo", "rustc"] }

[lints]
workspace = true
