[package]
name = "kaitai-diag"
version = "0.1.0"
edition = "2024"

[workspace]

[[bin]]
name = "kaitai-diag"
path = "main.rs"

[dependencies]
ctb-formats-kaitai = { path = "/workspaces/ctoolbox/src/formats/kaitai" }
ctb-utilities = { path = "/workspaces/ctoolbox/src/utilities" }
walkdir = "2.5.0"
anyhow = "1.0.100"
