[package]
name = "ctb-nopersonality"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"
description = "LD_PRELOAD shim for overriding personality() in containerized Guix builds"

[lib]
path = "nopersonality.rs"
# Note: it's actually built and used as a cdylib rather than an rlib, but we can't turn that on here because it breaks other workspace tooling, so set as rlib here.
crate-type = ["rlib"]

[dependencies]

[lints]
workspace = true
