// SPDX-License-Identifier: AGPL-3.0-or-later
/*
This file is part of Collective Toolbox, a database and document workspace and utilities.
Copyright (C) 2026 Collective Toolbox Developers
Contact: info@collectivetoolbox.com

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along
with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
//! @generated by ctb-build-support::format_support_codegen from format category data tables.
//! Operational format support enums and conversion implementations.

use crate::FormatId;
use anyhow::Result;

/// Single-stream compression formats supported for decompression / extraction by the workspace.
#[expect(
    non_camel_case_types,
    reason = "Variant names align with canonical FormatId identifier naming"
)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum SupportedDecompressionFormat {
    /// Brotli compressed stream (RFC 9841)
    Brotli,
    /// GNU gzip format (RFC 1952)
    Gzip,
    /// Raw DEFLATE compressed stream (RFC 1951)
    Deflate,
    /// Zlib-wrapped DEFLATE stream (RFC 1950)
    Zlib,
    /// Bzip2 compressed stream
    Bzip2,
    /// Original bzip compression
    Bzip,
    /// Zstandard compression
    Zstd,
    /// Lzip compression
    Lzip,
    /// XZ compression
    Xz,
    /// compress: SCO compress -H format (LZH)
    ScoCompress,
    /// compress format, modern LZW block format
    CompressLzw,
    /// compress 1.0 (LZW headerless format)
    CompressLzw1,
    /// compress 1.6 (LZW sorted chain format)
    CompressLzw16,
    /// compress 2.0 (LZW non-block format)
    CompressLzw2,
    /// pack format, common version (Huffman)
    Pack,
    /// pack format, early PDP-11 Unix binary tree
    OldPack,
    /// compact (McMaster Adaptive Huffman)
    Compact,
    /// freeze: Freeze 2.X format (LZSS + Dynamic Huffman)
    Freeze2,
    /// freeze: Freeze 1.0 format (LZSS + Dynamic Huffman)
    Freeze1,
    /// rzip: rzip format (long range chunk matching + bzip2)
    Rzip,
    /// LZ4
    Lz4,
    /// LZO (Lempel-Ziv-Oberhumer)
    Lzo,
    /// LZMA (Lempel–Ziv–Markov chain algorithm)
    Lzma,
    /// LZMA container format
    Lzma2,
    /// szip (Michael Schindler)
    Szip,
    /// szip (Michael Schindler) version 1.11+
    Szip111,
}

impl SupportedDecompressionFormat {
    /// Ordered list of all formats supported by this capability.
    pub const ALL: &'static [SupportedDecompressionFormat] = &[
        Self::Brotli,
        Self::Gzip,
        Self::Deflate,
        Self::Zlib,
        Self::Bzip2,
        Self::Bzip,
        Self::Zstd,
        Self::Lzip,
        Self::Xz,
        Self::ScoCompress,
        Self::CompressLzw,
        Self::CompressLzw1,
        Self::CompressLzw16,
        Self::CompressLzw2,
        Self::Pack,
        Self::OldPack,
        Self::Compact,
        Self::Freeze2,
        Self::Freeze1,
        Self::Rzip,
        Self::Lz4,
        Self::Lzo,
        Self::Lzma,
        Self::Lzma2,
        Self::Szip,
        Self::Szip111,
    ];

    /// Ordered list of all canonical `FormatId`s supported by this capability.
    pub const ALL_FORMAT_IDS: &'static [FormatId] = &[
        FormatId::Brotli,
        FormatId::Gzip,
        FormatId::Deflate,
        FormatId::Zlib,
        FormatId::Bzip2,
        FormatId::Bzip,
        FormatId::Zstd,
        FormatId::Lzip,
        FormatId::Xz,
        FormatId::ScoCompress,
        FormatId::CompressLzw,
        FormatId::CompressLzw1,
        FormatId::CompressLzw16,
        FormatId::CompressLzw2,
        FormatId::Pack,
        FormatId::OldPack,
        FormatId::Compact,
        FormatId::Freeze2,
        FormatId::Freeze1,
        FormatId::Rzip,
        FormatId::Lz4,
        FormatId::Lzo,
        FormatId::Lzma,
        FormatId::Lzma2,
        FormatId::Szip,
        FormatId::Szip111,
    ];

    /// Maps this variant to the canonical global `FormatId`.
    #[must_use]
    pub const fn to_format_id(&self) -> FormatId {
        match self {
            Self::Brotli => FormatId::Brotli,
            Self::Gzip => FormatId::Gzip,
            Self::Deflate => FormatId::Deflate,
            Self::Zlib => FormatId::Zlib,
            Self::Bzip2 => FormatId::Bzip2,
            Self::Bzip => FormatId::Bzip,
            Self::Zstd => FormatId::Zstd,
            Self::Lzip => FormatId::Lzip,
            Self::Xz => FormatId::Xz,
            Self::ScoCompress => FormatId::ScoCompress,
            Self::CompressLzw => FormatId::CompressLzw,
            Self::CompressLzw1 => FormatId::CompressLzw1,
            Self::CompressLzw16 => FormatId::CompressLzw16,
            Self::CompressLzw2 => FormatId::CompressLzw2,
            Self::Pack => FormatId::Pack,
            Self::OldPack => FormatId::OldPack,
            Self::Compact => FormatId::Compact,
            Self::Freeze2 => FormatId::Freeze2,
            Self::Freeze1 => FormatId::Freeze1,
            Self::Rzip => FormatId::Rzip,
            Self::Lz4 => FormatId::Lz4,
            Self::Lzo => FormatId::Lzo,
            Self::Lzma => FormatId::Lzma,
            Self::Lzma2 => FormatId::Lzma2,
            Self::Szip => FormatId::Szip,
            Self::Szip111 => FormatId::Szip111,
        }
    }

    /// Converts a global `FormatId` to `SupportedDecompressionFormat` if supported.
    #[must_use]
    pub const fn from_format_id(id: FormatId) -> Option<Self> {
        match id {
            FormatId::Brotli => Some(Self::Brotli),
            FormatId::Gzip => Some(Self::Gzip),
            FormatId::Deflate => Some(Self::Deflate),
            FormatId::Zlib => Some(Self::Zlib),
            FormatId::Bzip2 => Some(Self::Bzip2),
            FormatId::Bzip => Some(Self::Bzip),
            FormatId::Zstd => Some(Self::Zstd),
            FormatId::Lzip => Some(Self::Lzip),
            FormatId::Xz => Some(Self::Xz),
            FormatId::ScoCompress => Some(Self::ScoCompress),
            FormatId::CompressLzw => Some(Self::CompressLzw),
            FormatId::CompressLzw1 => Some(Self::CompressLzw1),
            FormatId::CompressLzw16 => Some(Self::CompressLzw16),
            FormatId::CompressLzw2 => Some(Self::CompressLzw2),
            FormatId::Pack => Some(Self::Pack),
            FormatId::OldPack => Some(Self::OldPack),
            FormatId::Compact => Some(Self::Compact),
            FormatId::Freeze2 => Some(Self::Freeze2),
            FormatId::Freeze1 => Some(Self::Freeze1),
            FormatId::Rzip => Some(Self::Rzip),
            FormatId::Lz4 => Some(Self::Lz4),
            FormatId::Lzo => Some(Self::Lzo),
            FormatId::Lzma => Some(Self::Lzma),
            FormatId::Lzma2 => Some(Self::Lzma2),
            FormatId::Szip => Some(Self::Szip),
            FormatId::Szip111 => Some(Self::Szip111),
            _ => None,
        }
    }

    /// Returns true if the given `FormatId` is supported by this capability.
    #[must_use]
    pub const fn is_supported(id: FormatId) -> bool {
        Self::from_format_id(id).is_some()
    }
}

impl From<SupportedDecompressionFormat> for FormatId {
    fn from(fmt: SupportedDecompressionFormat) -> Self {
        fmt.to_format_id()
    }
}

impl TryFrom<FormatId> for SupportedDecompressionFormat {
    type Error = anyhow::Error;

    fn try_from(id: FormatId) -> Result<Self, Self::Error> {
        Self::from_format_id(id).ok_or_else(|| anyhow::anyhow!("Format {id:?} is not a supported decompression format"))
    }
}

impl TryFrom<&str> for SupportedDecompressionFormat {
    type Error = anyhow::Error;

    fn try_from(s: &str) -> Result<Self, Self::Error> {
        let clean = s.trim().to_ascii_lowercase();
        if let Some(id) = FormatId::from_ident(&clean) {
            if let Some(fmt) = Self::from_format_id(id) {
                return Ok(fmt);
            }
        }
        anyhow::bail!("Unknown decompression format: '{s}'")
    }
}

impl TryFrom<String> for SupportedDecompressionFormat {
    type Error = anyhow::Error;

    fn try_from(s: String) -> Result<Self, Self::Error> {
        Self::try_from(s.as_str())
    }
}

impl std::str::FromStr for SupportedDecompressionFormat {
    type Err = anyhow::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Self::try_from(s)
    }
}

/// Single-stream compression formats supported for compression / encoding by the workspace.
#[expect(
    non_camel_case_types,
    reason = "Variant names align with canonical FormatId identifier naming"
)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum SupportedCompressionFormat {
    /// Brotli compressed stream (RFC 9841)
    Brotli,
    /// GNU gzip format (RFC 1952)
    Gzip,
    /// Raw DEFLATE compressed stream (RFC 1951)
    Deflate,
    /// Zlib-wrapped DEFLATE stream (RFC 1950)
    Zlib,
    /// Bzip2 compressed stream
    Bzip2,
    /// Original bzip compression
    Bzip,
    /// Zstandard compression
    Zstd,
    /// Lzip compression
    Lzip,
    /// XZ compression
    Xz,
    /// compress: SCO compress -H format (LZH)
    ScoCompress,
    /// compress format, modern LZW block format
    CompressLzw,
    /// compress 1.0 (LZW headerless format)
    CompressLzw1,
    /// compress 1.6 (LZW sorted chain format)
    CompressLzw16,
    /// compress 2.0 (LZW non-block format)
    CompressLzw2,
    /// pack format, common version (Huffman)
    Pack,
    /// pack format, early PDP-11 Unix binary tree
    OldPack,
    /// compact (McMaster Adaptive Huffman)
    Compact,
    /// freeze: Freeze 2.X format (LZSS + Dynamic Huffman)
    Freeze2,
    /// freeze: Freeze 1.0 format (LZSS + Dynamic Huffman)
    Freeze1,
    /// rzip: rzip format (long range chunk matching + bzip2)
    Rzip,
    /// LZ4
    Lz4,
    /// LZO (Lempel-Ziv-Oberhumer)
    Lzo,
    /// LZMA (Lempel–Ziv–Markov chain algorithm)
    Lzma,
    /// LZMA container format
    Lzma2,
    /// szip (Michael Schindler)
    Szip,
    /// szip (Michael Schindler) version 1.11+
    Szip111,
}

impl SupportedCompressionFormat {
    /// Ordered list of all formats supported by this capability.
    pub const ALL: &'static [SupportedCompressionFormat] = &[
        Self::Brotli,
        Self::Gzip,
        Self::Deflate,
        Self::Zlib,
        Self::Bzip2,
        Self::Bzip,
        Self::Zstd,
        Self::Lzip,
        Self::Xz,
        Self::ScoCompress,
        Self::CompressLzw,
        Self::CompressLzw1,
        Self::CompressLzw16,
        Self::CompressLzw2,
        Self::Pack,
        Self::OldPack,
        Self::Compact,
        Self::Freeze2,
        Self::Freeze1,
        Self::Rzip,
        Self::Lz4,
        Self::Lzo,
        Self::Lzma,
        Self::Lzma2,
        Self::Szip,
        Self::Szip111,
    ];

    /// Ordered list of all canonical `FormatId`s supported by this capability.
    pub const ALL_FORMAT_IDS: &'static [FormatId] = &[
        FormatId::Brotli,
        FormatId::Gzip,
        FormatId::Deflate,
        FormatId::Zlib,
        FormatId::Bzip2,
        FormatId::Bzip,
        FormatId::Zstd,
        FormatId::Lzip,
        FormatId::Xz,
        FormatId::ScoCompress,
        FormatId::CompressLzw,
        FormatId::CompressLzw1,
        FormatId::CompressLzw16,
        FormatId::CompressLzw2,
        FormatId::Pack,
        FormatId::OldPack,
        FormatId::Compact,
        FormatId::Freeze2,
        FormatId::Freeze1,
        FormatId::Rzip,
        FormatId::Lz4,
        FormatId::Lzo,
        FormatId::Lzma,
        FormatId::Lzma2,
        FormatId::Szip,
        FormatId::Szip111,
    ];

    /// Maps this variant to the canonical global `FormatId`.
    #[must_use]
    pub const fn to_format_id(&self) -> FormatId {
        match self {
            Self::Brotli => FormatId::Brotli,
            Self::Gzip => FormatId::Gzip,
            Self::Deflate => FormatId::Deflate,
            Self::Zlib => FormatId::Zlib,
            Self::Bzip2 => FormatId::Bzip2,
            Self::Bzip => FormatId::Bzip,
            Self::Zstd => FormatId::Zstd,
            Self::Lzip => FormatId::Lzip,
            Self::Xz => FormatId::Xz,
            Self::ScoCompress => FormatId::ScoCompress,
            Self::CompressLzw => FormatId::CompressLzw,
            Self::CompressLzw1 => FormatId::CompressLzw1,
            Self::CompressLzw16 => FormatId::CompressLzw16,
            Self::CompressLzw2 => FormatId::CompressLzw2,
            Self::Pack => FormatId::Pack,
            Self::OldPack => FormatId::OldPack,
            Self::Compact => FormatId::Compact,
            Self::Freeze2 => FormatId::Freeze2,
            Self::Freeze1 => FormatId::Freeze1,
            Self::Rzip => FormatId::Rzip,
            Self::Lz4 => FormatId::Lz4,
            Self::Lzo => FormatId::Lzo,
            Self::Lzma => FormatId::Lzma,
            Self::Lzma2 => FormatId::Lzma2,
            Self::Szip => FormatId::Szip,
            Self::Szip111 => FormatId::Szip111,
        }
    }

    /// Converts a global `FormatId` to `SupportedCompressionFormat` if supported.
    #[must_use]
    pub const fn from_format_id(id: FormatId) -> Option<Self> {
        match id {
            FormatId::Brotli => Some(Self::Brotli),
            FormatId::Gzip => Some(Self::Gzip),
            FormatId::Deflate => Some(Self::Deflate),
            FormatId::Zlib => Some(Self::Zlib),
            FormatId::Bzip2 => Some(Self::Bzip2),
            FormatId::Bzip => Some(Self::Bzip),
            FormatId::Zstd => Some(Self::Zstd),
            FormatId::Lzip => Some(Self::Lzip),
            FormatId::Xz => Some(Self::Xz),
            FormatId::ScoCompress => Some(Self::ScoCompress),
            FormatId::CompressLzw => Some(Self::CompressLzw),
            FormatId::CompressLzw1 => Some(Self::CompressLzw1),
            FormatId::CompressLzw16 => Some(Self::CompressLzw16),
            FormatId::CompressLzw2 => Some(Self::CompressLzw2),
            FormatId::Pack => Some(Self::Pack),
            FormatId::OldPack => Some(Self::OldPack),
            FormatId::Compact => Some(Self::Compact),
            FormatId::Freeze2 => Some(Self::Freeze2),
            FormatId::Freeze1 => Some(Self::Freeze1),
            FormatId::Rzip => Some(Self::Rzip),
            FormatId::Lz4 => Some(Self::Lz4),
            FormatId::Lzo => Some(Self::Lzo),
            FormatId::Lzma => Some(Self::Lzma),
            FormatId::Lzma2 => Some(Self::Lzma2),
            FormatId::Szip => Some(Self::Szip),
            FormatId::Szip111 => Some(Self::Szip111),
            _ => None,
        }
    }

    /// Returns true if the given `FormatId` is supported by this capability.
    #[must_use]
    pub const fn is_supported(id: FormatId) -> bool {
        Self::from_format_id(id).is_some()
    }
}

impl From<SupportedCompressionFormat> for FormatId {
    fn from(fmt: SupportedCompressionFormat) -> Self {
        fmt.to_format_id()
    }
}

impl TryFrom<FormatId> for SupportedCompressionFormat {
    type Error = anyhow::Error;

    fn try_from(id: FormatId) -> Result<Self, Self::Error> {
        Self::from_format_id(id).ok_or_else(|| anyhow::anyhow!("Format {id:?} is not a supported compression format"))
    }
}

impl TryFrom<&str> for SupportedCompressionFormat {
    type Error = anyhow::Error;

    fn try_from(s: &str) -> Result<Self, Self::Error> {
        let clean = s.trim().to_ascii_lowercase();
        if let Some(id) = FormatId::from_ident(&clean) {
            if let Some(fmt) = Self::from_format_id(id) {
                return Ok(fmt);
            }
        }
        anyhow::bail!("Unknown compression format: '{s}'")
    }
}

impl TryFrom<String> for SupportedCompressionFormat {
    type Error = anyhow::Error;

    fn try_from(s: String) -> Result<Self, Self::Error> {
        Self::try_from(s.as_str())
    }
}

impl std::str::FromStr for SupportedCompressionFormat {
    type Err = anyhow::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Self::try_from(s)
    }
}

/// Cryptographic and non-cryptographic hash algorithms supported by the workspace.
#[expect(
    non_camel_case_types,
    reason = "Variant names align with canonical FormatId identifier naming"
)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum SupportedHashFormat {
    /// xxHash32
    XxHash32,
    /// xxHash64
    XxHash64,
    /// xxHash3-64
    XxHash3_64,
    /// xxHash3-128
    XxHash3_128,
    /// SHA-256
    Sha256,
    /// FNV-0 hash, 32 bits
    Fnv0_32,
    /// FNV-0 hash, 64 bits
    Fnv0_64,
    /// FNV-0 hash, 128 bits
    Fnv0_128,
    /// FNV-0 hash, 256 bits
    Fnv0_256,
    /// FNV-0 hash, 512 bits
    Fnv0_512,
    /// FNV-0 hash, 1024 bits
    Fnv0_1024,
    /// FNV-1 hash, 32 bits
    Fnv1_32,
    /// FNV-1 hash, 64 bits
    Fnv1_64,
    /// FNV-1 hash, 128 bits
    Fnv1_128,
    /// FNV-1 hash, 256 bits
    Fnv1_256,
    /// FNV-1 hash, 512 bits
    Fnv1_512,
    /// FNV-1 hash, 1024 bits
    Fnv1_1024,
    /// FNV-1a hash, 32 bits
    Fnv1a_32,
    /// FNV-1a hash, 64 bits
    Fnv1a_64,
    /// FNV-1a hash, 128 bits
    Fnv1a_128,
    /// FNV-1a hash, 256 bits
    Fnv1a_256,
    /// FNV-1a hash, 512 bits
    Fnv1a_512,
    /// FNV-1a hash, 1024 bits
    Fnv1a_1024,
}

impl SupportedHashFormat {
    /// Ordered list of all formats supported by this capability.
    pub const ALL: &'static [SupportedHashFormat] = &[
        Self::XxHash32,
        Self::XxHash64,
        Self::XxHash3_64,
        Self::XxHash3_128,
        Self::Sha256,
        Self::Fnv0_32,
        Self::Fnv0_64,
        Self::Fnv0_128,
        Self::Fnv0_256,
        Self::Fnv0_512,
        Self::Fnv0_1024,
        Self::Fnv1_32,
        Self::Fnv1_64,
        Self::Fnv1_128,
        Self::Fnv1_256,
        Self::Fnv1_512,
        Self::Fnv1_1024,
        Self::Fnv1a_32,
        Self::Fnv1a_64,
        Self::Fnv1a_128,
        Self::Fnv1a_256,
        Self::Fnv1a_512,
        Self::Fnv1a_1024,
    ];

    /// Ordered list of all canonical `FormatId`s supported by this capability.
    pub const ALL_FORMAT_IDS: &'static [FormatId] = &[
        FormatId::XxHash32,
        FormatId::XxHash64,
        FormatId::XxHash3_64,
        FormatId::XxHash3_128,
        FormatId::Sha256,
        FormatId::Fnv0_32,
        FormatId::Fnv0_64,
        FormatId::Fnv0_128,
        FormatId::Fnv0_256,
        FormatId::Fnv0_512,
        FormatId::Fnv0_1024,
        FormatId::Fnv1_32,
        FormatId::Fnv1_64,
        FormatId::Fnv1_128,
        FormatId::Fnv1_256,
        FormatId::Fnv1_512,
        FormatId::Fnv1_1024,
        FormatId::Fnv1a_32,
        FormatId::Fnv1a_64,
        FormatId::Fnv1a_128,
        FormatId::Fnv1a_256,
        FormatId::Fnv1a_512,
        FormatId::Fnv1a_1024,
    ];

    /// Maps this variant to the canonical global `FormatId`.
    #[must_use]
    pub const fn to_format_id(&self) -> FormatId {
        match self {
            Self::XxHash32 => FormatId::XxHash32,
            Self::XxHash64 => FormatId::XxHash64,
            Self::XxHash3_64 => FormatId::XxHash3_64,
            Self::XxHash3_128 => FormatId::XxHash3_128,
            Self::Sha256 => FormatId::Sha256,
            Self::Fnv0_32 => FormatId::Fnv0_32,
            Self::Fnv0_64 => FormatId::Fnv0_64,
            Self::Fnv0_128 => FormatId::Fnv0_128,
            Self::Fnv0_256 => FormatId::Fnv0_256,
            Self::Fnv0_512 => FormatId::Fnv0_512,
            Self::Fnv0_1024 => FormatId::Fnv0_1024,
            Self::Fnv1_32 => FormatId::Fnv1_32,
            Self::Fnv1_64 => FormatId::Fnv1_64,
            Self::Fnv1_128 => FormatId::Fnv1_128,
            Self::Fnv1_256 => FormatId::Fnv1_256,
            Self::Fnv1_512 => FormatId::Fnv1_512,
            Self::Fnv1_1024 => FormatId::Fnv1_1024,
            Self::Fnv1a_32 => FormatId::Fnv1a_32,
            Self::Fnv1a_64 => FormatId::Fnv1a_64,
            Self::Fnv1a_128 => FormatId::Fnv1a_128,
            Self::Fnv1a_256 => FormatId::Fnv1a_256,
            Self::Fnv1a_512 => FormatId::Fnv1a_512,
            Self::Fnv1a_1024 => FormatId::Fnv1a_1024,
        }
    }

    /// Converts a global `FormatId` to `SupportedHashFormat` if supported.
    #[must_use]
    pub const fn from_format_id(id: FormatId) -> Option<Self> {
        match id {
            FormatId::XxHash32 => Some(Self::XxHash32),
            FormatId::XxHash64 => Some(Self::XxHash64),
            FormatId::XxHash3_64 => Some(Self::XxHash3_64),
            FormatId::XxHash3_128 => Some(Self::XxHash3_128),
            FormatId::Sha256 => Some(Self::Sha256),
            FormatId::Fnv0_32 => Some(Self::Fnv0_32),
            FormatId::Fnv0_64 => Some(Self::Fnv0_64),
            FormatId::Fnv0_128 => Some(Self::Fnv0_128),
            FormatId::Fnv0_256 => Some(Self::Fnv0_256),
            FormatId::Fnv0_512 => Some(Self::Fnv0_512),
            FormatId::Fnv0_1024 => Some(Self::Fnv0_1024),
            FormatId::Fnv1_32 => Some(Self::Fnv1_32),
            FormatId::Fnv1_64 => Some(Self::Fnv1_64),
            FormatId::Fnv1_128 => Some(Self::Fnv1_128),
            FormatId::Fnv1_256 => Some(Self::Fnv1_256),
            FormatId::Fnv1_512 => Some(Self::Fnv1_512),
            FormatId::Fnv1_1024 => Some(Self::Fnv1_1024),
            FormatId::Fnv1a_32 => Some(Self::Fnv1a_32),
            FormatId::Fnv1a_64 => Some(Self::Fnv1a_64),
            FormatId::Fnv1a_128 => Some(Self::Fnv1a_128),
            FormatId::Fnv1a_256 => Some(Self::Fnv1a_256),
            FormatId::Fnv1a_512 => Some(Self::Fnv1a_512),
            FormatId::Fnv1a_1024 => Some(Self::Fnv1a_1024),
            FormatId::Fnv0 => Some(Self::Fnv0_64),
            FormatId::Fnv1 => Some(Self::Fnv1_64),
            FormatId::Fnv1a => Some(Self::Fnv1a_64),
            FormatId::FowlerNollVo => Some(Self::Fnv1a_64),
            _ => None,
        }
    }

    /// Returns true if the given `FormatId` is supported by this capability.
    #[must_use]
    pub const fn is_supported(id: FormatId) -> bool {
        Self::from_format_id(id).is_some()
    }
}

impl From<SupportedHashFormat> for FormatId {
    fn from(fmt: SupportedHashFormat) -> Self {
        fmt.to_format_id()
    }
}

impl TryFrom<FormatId> for SupportedHashFormat {
    type Error = anyhow::Error;

    fn try_from(id: FormatId) -> Result<Self, Self::Error> {
        Self::from_format_id(id).ok_or_else(|| anyhow::anyhow!("Format {id:?} is not a supported hash algorithm"))
    }
}

impl TryFrom<&str> for SupportedHashFormat {
    type Error = anyhow::Error;

    fn try_from(s: &str) -> Result<Self, Self::Error> {
        let clean = s.trim().to_ascii_lowercase();
        if let Some(id) = FormatId::from_ident(&clean) {
            if let Some(fmt) = Self::from_format_id(id) {
                return Ok(fmt);
            }
        }
        anyhow::bail!("Unknown hash algorithm: '{s}'")
    }
}

impl TryFrom<String> for SupportedHashFormat {
    type Error = anyhow::Error;

    fn try_from(s: String) -> Result<Self, Self::Error> {
        Self::try_from(s.as_str())
    }
}

impl std::str::FromStr for SupportedHashFormat {
    type Err = anyhow::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Self::try_from(s)
    }
}

impl FormatId {
    /// Converts this `FormatId` to [`SupportedDecompressionFormat`] if supported.
    ///
    /// # Errors
    /// Returns an error if this format is not supported for decompression.
    pub fn to_supported_decompression_format(self) -> Result<SupportedDecompressionFormat> {
        SupportedDecompressionFormat::try_from(self)
    }

    /// Converts this `FormatId` to [`SupportedCompressionFormat`] if supported.
    ///
    /// # Errors
    /// Returns an error if this format is not supported for compression.
    pub fn to_supported_compression_format(self) -> Result<SupportedCompressionFormat> {
        SupportedCompressionFormat::try_from(self)
    }

    /// Converts this `FormatId` to [`SupportedHashFormat`] if supported.
    ///
    /// # Errors
    /// Returns an error if this format is not a supported hash algorithm.
    pub fn to_supported_hash_format(self) -> Result<SupportedHashFormat> {
        SupportedHashFormat::try_from(self)
    }
}
