// SPDX-License-Identifier: AGPL-3.0-or-later
/*
This file is part of Collective Toolbox, a database and document workspace and utilities.
Copyright (C) 2026 Collective Toolbox Developers
Contact: info@collectivetoolbox.com

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along
with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

//! This does a two-stage bootstrap of the version of TypeScript written in
//! TypeScript, from source. The first, non-type-checked stage uses deno_ast and
//! is quite fast (several seconds). The second stage uses the resulting tsc
//! created during the first stage, and is slow, around half an hour in release
//! mode, or several hours in debug mode. It writes the completed tsc into a
//! tar file alongside the source directory. It does not regenerate the locale
//! files.

use ctb_formats_json::jsonc::strip_jsonc_comments;
#[allow(clippy::wildcard_imports)]
pub(crate) use ctb_utilities::*;

use anyhow::{Context as AnyhowContext, Result, bail};
use deno_ast::{
    EmitOptions, MediaType, ParseParams, SourceMapOption,
    TranspileModuleOptions, TranspileOptions,
};
use std::collections::{BTreeMap, HashMap};
use std::path::{Path, PathBuf};

#[derive(serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct DiagnosticDetails {
    category: String,
    code: u32,
    reports_unnecessary: Option<serde_json::Value>,
    elided_in_compatibility_pyramid: Option<bool>,
    reports_deprecated: Option<serde_json::Value>,
}

#[derive(serde::Deserialize)]
struct LibsConfig {
    libs: Vec<String>,
    paths: HashMap<String, String>,
}

fn convert_property_name(orig_name: &str) -> String {
    let mut result = String::new();
    for c in orig_name.chars() {
        match c {
            '*' => result.push_str("_Asterisk"),
            '/' => result.push_str("_Slash"),
            ':' => result.push_str("_Colon"),
            _ if c.is_alphanumeric() || c == '_' => result.push(c),
            _ => result.push('_'),
        }
    }
    let mut cleaned = String::new();
    let mut last_was_under = false;
    for c in result.chars() {
        if c == '_' {
            if !last_was_under {
                cleaned.push('_');
                last_was_under = true;
            }
        } else {
            cleaned.push(c);
            last_was_under = false;
        }
    }
    if cleaned.starts_with('_') && cleaned.len() > 1 {
        let second = cleaned.chars().nth(1).unwrap();
        if !second.is_ascii_digit() {
            cleaned.remove(0);
        }
    }
    if cleaned.ends_with('_') {
        cleaned.pop();
    }
    cleaned
}

fn create_key(name: &str, code: u32) -> String {
    let prefix: String = name.chars().take(100).collect();
    format!("{}_{}", prefix, code)
}

fn check_for_unique_codes(
    messages: &[(String, DiagnosticDetails)],
) -> Result<()> {
    let mut seen = std::collections::HashSet::new();
    for (_, details) in messages {
        if !seen.insert(details.code) {
            bail!("Diagnostic code {} appears more than once.", details.code);
        }
    }
    Ok(())
}

fn build_info_file_output(
    messages: &[(String, DiagnosticDetails)],
    input_file_path_rel: &str,
) -> String {
    let mut result = Vec::new();
    result.push("// <auto-generated />".to_string());
    result.push(format!("// generated from '{}'", input_file_path_rel));
    result.push("".to_string());
    result.push(
        "import { DiagnosticCategory, DiagnosticMessage } from \"./types.js\";"
            .to_string(),
    );
    result.push("".to_string());
    result.push("function diag(code: number, category: DiagnosticCategory, key: string, message: string, reportsUnnecessary?: {}, elidedInCompatabilityPyramid?: boolean, reportsDeprecated?: {}): DiagnosticMessage {".to_string());
    result.push("    return { code, category, key, message, reportsUnnecessary, elidedInCompatabilityPyramid, reportsDeprecated };".to_string());
    result.push("}".to_string());
    result.push("".to_string());
    result.push(
        "/* eslint-disable @typescript-eslint/no-unnecessary-type-assertion*/"
            .to_string(),
    );
    result.push("/** @internal */".to_string());
    result.push("export const Diagnostics = {".to_string());

    for (name, details) in messages {
        let prop_name = convert_property_name(name);
        let arg_reports_unnecessary =
            if let Some(ref ru) = details.reports_unnecessary {
                format!(", /*reportsUnnecessary*/ {}", ru)
            } else {
                "".to_string()
            };
        let arg_elided_in_compatibility_pyramid = if let Some(elided) =
            details.elided_in_compatibility_pyramid
        {
            let prefix = if details.reports_unnecessary.is_none() {
                ", /*reportsUnnecessary*/ undefined"
            } else {
                ""
            };
            format!("{}, /*elidedInCompatabilityPyramid*/ {}", prefix, elided)
        } else {
            "".to_string()
        };
        let arg_reports_deprecated = if let Some(ref rd) =
            details.reports_deprecated
        {
            let prefix = if arg_elided_in_compatibility_pyramid.is_empty() {
                ", /*reportsUnnecessary*/ undefined, /*elidedInCompatabilityPyramid*/ undefined"
            } else {
                ""
            };
            format!("{}, /*reportsDeprecated*/ {}", prefix, rd)
        } else {
            "".to_string()
        };

        let escaped_name = serde_json::to_string(name).unwrap();

        result.push(format!(
            "    {}: diag({}, DiagnosticCategory.{}, \"{}\", {}{}{}{}) as DiagnosticMessage,",
            prop_name,
            details.code,
            details.category,
            create_key(&prop_name, details.code),
            escaped_name,
            arg_reports_unnecessary,
            arg_elided_in_compatibility_pyramid,
            arg_reports_deprecated
        ));
    }

    result.push("};".to_string());
    result.join("\r\n")
}

fn build_diagnostic_message_output(
    messages: &[(String, DiagnosticDetails)],
) -> String {
    let mut map = BTreeMap::new();
    for (name, details) in messages {
        let prop_name = convert_property_name(name);
        map.insert(create_key(&prop_name, details.code), name);
    }
    let serialized = serde_json::to_string_pretty(&map).unwrap();
    serialized.replace('\n', "\r\n")
}

fn transpile_ts_file(src_file_path: &Path) -> Result<String> {
    let code = std::fs::read_to_string(src_file_path).with_context(|| {
        format!("Failed to read file: {}", src_file_path.display())
    })?;

    let specifier = deno_ast::ModuleSpecifier::from_file_path(src_file_path)
        .map_err(|_| {
            anyhow::anyhow!(
                "Failed to convert path to specifier: {}",
                src_file_path.display()
            )
        })?;

    let media_type = MediaType::from_path(src_file_path);

    let parsed = deno_ast::parse_module(ParseParams {
        specifier,
        text: code.into(),
        media_type,
        capture_tokens: false,
        scope_analysis: false,
        maybe_syntax: None,
    })
    .map_err(|e| {
        anyhow::anyhow!("Parse error in {}: {}", src_file_path.display(), e)
    })?;

    let transpile_res = parsed
        .transpile(
            &TranspileOptions {
                imports_not_used_as_values:
                    deno_ast::ImportsNotUsedAsValues::Remove,
                decorators: deno_ast::DecoratorsTranspileOption::Ecma,
                ..Default::default()
            },
            &TranspileModuleOptions { module_kind: None },
            &EmitOptions {
                source_map: SourceMapOption::None,
                ..Default::default()
            },
        )
        .map_err(|e| {
            anyhow::anyhow!(
                "Transpile error in {}: {}",
                src_file_path.display(),
                e
            )
        })?;

    let res = transpile_res.into_source();
    Ok(res.text)
}

fn copy_dir_all(src: &Path, dst: &Path) -> Result<()> {
    std::fs::create_dir_all(dst)?;
    for entry in std::fs::read_dir(src)? {
        let entry = entry?;
        let ty = entry.file_type()?;
        if ty.is_dir() {
            copy_dir_all(&entry.path(), &dst.join(entry.file_name()))?;
        } else {
            std::fs::copy(entry.path(), dst.join(entry.file_name()))?;
        }
    }
    Ok(())
}

pub fn bootstrap_typescript(ts_repo_path: &Path) -> Result<Vec<u8>> {
    info_fmt!("Starting TypeScript bootstrap compilation...");
    let work_dir =
        tempfile::tempdir().context("Failed to create temp work directory")?;
    let work_path = work_dir.path();

    let ts_repo_parent = ts_repo_path
        .parent()
        .context("Could not find parent of ts_repo_path")?;
    let src_dir = ts_repo_path.join("src");
    let scripts_dir = ts_repo_path.join("scripts");

    info_fmt!("Stage 1: Preparing compiler source directories...");
    copy_dir_all(&src_dir, &work_path.join("src"))
        .context("Failed to copy src directory")?;
    if scripts_dir.exists() {
        copy_dir_all(&scripts_dir, &work_path.join("scripts"))
            .context("Failed to copy scripts directory")?;
    }

    // Set up node_modules in work_path for undici-types, source-map-support, and @types/node/deno
    let node_modules_dir = work_path.join("node_modules");
    std::fs::create_dir_all(&node_modules_dir)?;

    let types_src_dir = ts_repo_parent.join("DefinitelyTyped-partial");
    if types_src_dir.exists() {
        let at_types_dir = node_modules_dir.join("@types");
        std::fs::create_dir_all(&at_types_dir)?;

        let types_node_dest = at_types_dir.join("node");
        copy_dir_all(&types_src_dir.join("node"), &types_node_dest)
            .context("Failed to copy DefinitelyTyped-partial/node to node_modules/@types/node")?;

        let types_deno_dest = at_types_dir.join("deno");
        copy_dir_all(&types_src_dir.join("deno"), &types_deno_dest)
            .context("Failed to copy DefinitelyTyped-partial/deno to node_modules/@types/deno")?;
    }

    let undici_src_dir = ts_repo_parent.join("undici/types");
    if undici_src_dir.exists() {
        let undici_dest_dir = node_modules_dir.join("undici-types");
        copy_dir_all(&undici_src_dir, &undici_dest_dir)
            .context("Failed to copy undici-types")?;
        std::fs::write(
            undici_dest_dir.join("package.json"),
            r#"{"name": "undici-types", "main": "", "types": "index.d.ts"}"#,
        )?;
    }

    let sms_dir = node_modules_dir.join("source-map-support");
    std::fs::create_dir_all(&sms_dir)?;
    std::fs::write(
        sms_dir.join("package.json"),
        r#"{"name": "source-map-support", "main": "", "types": "index.d.ts"}"#,
    )?;
    std::fs::write(
        sms_dir.join("index.d.ts"),
        r#"export function install(): void;"#,
    )?;

    let diag_json_path = work_path.join("src/compiler/diagnosticMessages.json");
    let diag_str = std::fs::read_to_string(&diag_json_path)
        .context("Failed to read diagnosticMessages.json")?;
    let diag_map: BTreeMap<String, DiagnosticDetails> =
        serde_json::from_str(&diag_str)
            .context("Failed to parse diagnosticMessages.json")?;
    let diagnostic_messages: Vec<(String, DiagnosticDetails)> =
        diag_map.into_iter().collect();

    check_for_unique_codes(&diagnostic_messages)?;

    let info_output = build_info_file_output(
        &diagnostic_messages,
        "src/compiler/diagnosticMessages.json",
    );
    let msg_output = build_diagnostic_message_output(&diagnostic_messages);

    std::fs::write(
        work_path.join("src/compiler/diagnosticInformationMap.generated.ts"),
        info_output,
    )
    .context("Failed to write diagnosticInformationMap.generated.ts")?;

    std::fs::write(
        work_path.join("src/compiler/diagnosticMessages.generated.json"),
        msg_output,
    )
    .context("Failed to write diagnosticMessages.generated.json")?;

    let libs_config_path = work_path.join("src/lib/libs.json");
    let libs_config_str = std::fs::read_to_string(&libs_config_path)
        .context("Failed to read libs.json")?;
    let libs_config_clean = strip_jsonc_comments(&libs_config_str);
    let libs_config: LibsConfig = serde_json::from_str(&libs_config_clean)
        .context("Failed to parse libs.json")?;

    let copyright_path = work_path.join("scripts/CopyrightNotice.txt");
    let copyright = if copyright_path.exists() {
        std::fs::read_to_string(&copyright_path)?.replace("\r\n", "\n")
    } else {
        "// Copyright Notice\n".to_string()
    };

    let local_libs_dir = work_path.join("built/local");
    std::fs::create_dir_all(&local_libs_dir)?;

    for lib in &libs_config.libs {
        let source_file =
            work_path.join("src/lib").join(format!("{}.d.ts", lib));
        if source_file.exists() {
            // Reason for fallback: when optional explicit path map is missing for library lib, default filename lib.<lib>.d.ts is used.
            let dest_filename = libs_config
                .paths
                .get(lib)
                .cloned()
                .unwrap_or_else(|| format!("lib.{}.d.ts", lib));
            let content =
                std::fs::read_to_string(&source_file)?.replace("\r\n", "\n");
            let output_content = format!("{}{}\n", copyright, content);
            std::fs::write(
                local_libs_dir.join(&dest_filename),
                output_content,
            )?;
        }
    }

    let stage1_src_dir = work_path.join("stage1/src");

    // Collect all files first to show progress
    let mut files_to_process = Vec::new();
    for entry in walkdir::WalkDir::new(work_path.join("src")) {
        let entry = entry?;
        let path = entry.path();
        if path.is_file() {
            // Reason for fallback: when file path has no extension or non-UTF8 extension, empty string fallback prevents matching .ts or .json.
            let ext = path.extension().and_then(|s| s.to_str()).unwrap_or("");
            if ((ext == "ts" || ext == "tsx")
                && !path.to_string_lossy().ends_with(".d.ts"))
                || ext == "json"
            {
                files_to_process.push(path.to_path_buf());
            }
        }
    }
    let total_files = files_to_process.len();

    for (i, path) in files_to_process.iter().enumerate() {
        let rel_path = path.strip_prefix(work_path.join("src"))?;
        let percent = (i * 100) / total_files;
        info_fmt!("Transpiling: {} ({}%)", rel_path.display(), percent);

        let dest_path = stage1_src_dir.join(rel_path);

        if let Some(parent) = dest_path.parent() {
            std::fs::create_dir_all(parent)?;
        }

        // Reason for fallback: when file path has no extension or non-UTF8 extension, empty string fallback prevents matching .ts or .json.
        let ext = path.extension().and_then(|s| s.to_str()).unwrap_or("");
        if (ext == "ts" || ext == "tsx")
            && !path.to_string_lossy().ends_with(".d.ts")
        {
            let mut js_code = transpile_ts_file(path)?;
            if rel_path.to_string_lossy() == "compiler/sys.ts" {
                let before_len = js_code.len();
                js_code = js_code.replace(
                    "export let sys = (()=>{",
                    "export let sys;\nlet _sys_init = () => (() => {\n",
                );
                js_code = js_code.replace(
                    "export var sys = (()=>{",
                    "export let sys;\nlet _sys_init = () => (() => {\n",
                );
                if js_code.len() == before_len {
                    println!(
                        "WARNING: Proxy patch for sys.js did not find expected 'export let/var sys =' pattern!"
                    );
                }
                js_code.push_str(
                    "\n\
sys = new Proxy({}, {
    get(target, prop) {
        let isReady = false;
        try {
            if (typeof memoize === \"function\") {
                isReady = true;
            }
        } catch (e) {}
        if (!isReady) return undefined;
        if (typeof _sys_init === \"function\") {
            _sys_init = _sys_init();
        }
        if (!_sys_init) return undefined;
        const val = _sys_init[prop];
        if (typeof val === \"function\") {
            return function(...args) {
                return val.apply(_sys_init, args);
            };
        }
        return val;
    },
    set(target, prop, value) {
        let isReady = false;
        try {
            if (typeof memoize === \"function\") {
                isReady = true;
            }
        } catch (e) {}
        if (!isReady) return true;
        if (typeof _sys_init === \"function\") {
            _sys_init = _sys_init();
        }
        if (_sys_init) {
            _sys_init[prop] = value;
        }
        return true;
    }
});\n",
                );
            }
            let dest_js_path = dest_path.with_extension("js");
            std::fs::write(dest_js_path, js_code)?;
        } else if ext == "json" {
            std::fs::copy(path, dest_path)?;
        }
    }

    let stage1_tsc_dir = stage1_src_dir.join("tsc");
    std::fs::create_dir_all(&stage1_tsc_dir)?;
    for entry in std::fs::read_dir(&local_libs_dir)? {
        let entry = entry?;
        if entry.file_type()?.is_file() {
            let file_name = entry.file_name();
            std::fs::copy(entry.path(), stage1_tsc_dir.join(&file_name))?;
            std::fs::copy(entry.path(), stage1_src_dir.join(&file_name))?;
        }
    }

    let generated_json_path =
        work_path.join("src/compiler/diagnosticMessages.generated.json");
    if generated_json_path.exists() {
        let dest_json =
            stage1_src_dir.join("compiler/diagnosticMessages.generated.json");
        if let Some(parent) = dest_json.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::copy(generated_json_path, dest_json)?;
    }

    let types_node_path = work_path.join("node_modules/@types/node/index.d.ts");
    if !types_node_path.exists() {
        bail!(
            "Node type definitions not found at {}",
            types_node_path.display()
        );
    }
    let types_node_str = types_node_path.to_string_lossy().into_owned();

    let wrapper_point = stage1_src_dir.join("entry_wrapper.js");
    std::fs::write(
        &wrapper_point,
        r#"
console.log("Wrapper starting...");
try {
    await import("./tsc/tsc.js");
} catch (e) {
    if (String(e).includes("process.exit: 0")) {
        console.log("Wrapper saw clean exit.");
    } else {
        console.log("Wrapper CAUGHT ERROR: " + e);
        console.log("Stack trace:\n" + (e.stack || "No stack trace available"));
        throw e;
    }
}
"#,
    )
    .context("Failed to write entry_wrapper.js")?;

    let loader_root = stage1_src_dir.clone();
    let stage2_dir = work_path.join("stage2");

    let tsc_input = work_path.join("src/tsc/tsc.ts");
    let tsc_args = vec![
        tsc_input.to_string_lossy().into_owned(),
        types_node_str.clone(),
        "--target".to_string(),
        "es2020".to_string(),
        "--module".to_string(),
        "NodeNext".to_string(),
        "--moduleResolution".to_string(),
        "NodeNext".to_string(),
        "--lib".to_string(),
        "es2020".to_string(),
        "--declaration".to_string(),
        "false".to_string(),
        "--emitDeclarationOnly".to_string(),
        "false".to_string(),
        "--outDir".to_string(),
        stage2_dir.to_string_lossy().into_owned(),
        "--ignoreConfig".to_string(),
        "--strictBindCallApply".to_string(),
        "false".to_string(),
        "--useUnknownInCatchVariables".to_string(),
        "false".to_string(),
    ];

    info_fmt!("Stage 2: Running bootstrapped tsc.ts compilation...");
    ctb_formats_javascript_boa_host::run_js_module_allow_success_exit(
        &wrapper_point,
        &loader_root,
        &tsc_args,
    )
    .context("Stage 2: tsc compilation failed")?;

    let ts_input = work_path.join("src/typescript/typescript.ts");
    let ts_args = vec![
        ts_input.to_string_lossy().into_owned(),
        types_node_str,
        "--target".to_string(),
        "es2020".to_string(),
        "--module".to_string(),
        "NodeNext".to_string(),
        "--moduleResolution".to_string(),
        "NodeNext".to_string(),
        "--lib".to_string(),
        "es2020".to_string(),
        "--declaration".to_string(),
        "false".to_string(),
        "--emitDeclarationOnly".to_string(),
        "false".to_string(),
        "--outDir".to_string(),
        stage2_dir.to_string_lossy().into_owned(),
        "--ignoreConfig".to_string(),
        "--strictBindCallApply".to_string(),
        "false".to_string(),
        "--useUnknownInCatchVariables".to_string(),
        "false".to_string(),
    ];

    info_fmt!("Stage 3: Running bootstrapped typescript.ts compilation...");
    ctb_formats_javascript_boa_host::run_js_module_allow_success_exit(
        &wrapper_point,
        &loader_root,
        &ts_args,
    )
    .context("Stage 2: typescript.ts compilation failed")?;

    let final_diag_json =
        work_path.join("src/compiler/diagnosticMessages.generated.json");
    if final_diag_json.exists() {
        std::fs::copy(
            final_diag_json,
            stage2_dir.join("compiler/diagnosticMessages.generated.json"),
        )?;
    }

    info_fmt!("Stage 4: Creating compiler tarball package...");
    let mut tar_data = Vec::new();
    {
        let mut builder = tar::Builder::new(&mut tar_data);

        for entry in walkdir::WalkDir::new(&stage2_dir) {
            let entry = entry?;
            let path = entry.path();
            if path.is_file() {
                let rel_path = path.strip_prefix(&stage2_dir)?;
                builder.append_path_with_name(path, rel_path)?;
            }
        }

        for entry in std::fs::read_dir(&local_libs_dir)? {
            let entry = entry?;
            let path = entry.path();
            if path.is_file() {
                let name = entry.file_name();

                let tsc_lib_path = PathBuf::from("tsc").join(&name);
                builder.append_path_with_name(&path, &tsc_lib_path)?;

                let ts_lib_path = PathBuf::from("typescript").join(&name);
                builder.append_path_with_name(&path, &ts_lib_path)?;
            }
        }

        let types_dir = ts_repo_path
            .parent()
            .context("Could not find parent of ts_repo_path")?
            .join("DefinitelyTyped-partial");
        if types_dir.exists() {
            for entry in walkdir::WalkDir::new(&types_dir) {
                let entry = entry?;
                let path = entry.path();
                if path.is_file() {
                    let rel_path = path.strip_prefix(&types_dir)?;
                    let tar_path = PathBuf::from("types").join(rel_path);
                    builder.append_path_with_name(path, tar_path)?;
                }
            }
        }

        let undici_dir = ts_repo_path
            .parent()
            .context("Could not find parent of ts_repo_path")?
            .join("undici");
        if undici_dir.exists() {
            for entry in walkdir::WalkDir::new(&undici_dir) {
                let entry = entry?;
                let path = entry.path();
                if path.is_file() {
                    let rel_path = path.strip_prefix(&undici_dir)?;
                    let tar_path = PathBuf::from("types/undici").join(rel_path);
                    builder.append_path_with_name(path, tar_path)?;
                }
            }
        }

        builder.finish()?;
    }

    let dest_tar = ts_repo_path
        .parent()
        .context("Could not find parent directory of ts_repo_path")?
        .join("TypeScript-built.tar");
    std::fs::write(&dest_tar, &tar_data).with_context(|| {
        format!("Failed to write built tarball to {}", dest_tar.display())
    })?;
    info_fmt!("Cached built TypeScript tarball to {}", dest_tar.display());

    Ok(tar_data)
}

pub fn get_default_ts_repo_path() -> Option<PathBuf> {
    let base = std::env::var("CARGO_MANIFEST_DIR")
        .map(PathBuf::from)
        .expect("CARGO_MANIFEST_DIR was not set at compile time.");

    if base.ends_with("javascript") {
        Some(base.join("../../../vendor/TypeScript"))
    } else {
        Some(base.join("vendor/TypeScript"))
    }
}

#[cfg(test)]
#[allow(
    clippy::panic,
    clippy::expect_used,
    clippy::unwrap_used,
    clippy::unwrap_in_result,
    clippy::panic_in_result_fn,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects,
    reason = "Standard repository test boilerplate"
)]
mod tests {
    use super::*;

    #[ctb_test]
    #[ignore = "slow"]
    fn test_bootstrap_ts_compilation() {
        let repo_path =
            get_default_ts_repo_path().expect("No default TS repo path");
        assert!(
            repo_path.exists(),
            "TypeScript repo path does not exist: {}",
            repo_path.display()
        );
        let res = bootstrap_typescript(&repo_path);
        assert!(res.is_ok(), "Bootstrap failed: {:?}", res.err());
    }
}
