[package]
name = "ctb-formats-pan"
edition = "2024"
license = "MIT"

[lib]
path="pan.rs"
crate-type = ["lib"]

[[bin]]
name = "pan-ctb"
path = "bin.rs"

[profile.dev]
incremental = false

[dependencies]
ctb-utilities = { path = "../../utilities" }
ctb-formats-applescript = { path = "../../formats/applescript" }
ctb-formats-encoding = { path = "../../formats/encoding" }

regex = "1.12.2"
fancy-regex = "0.17.0"
rand = "0.9.2"
chrono = "0.4.43"
dateparser = "0.2.1"
number_to_words = "0.1.1"
nix = { version = "0.30.1", features = ["time"] }
pluralizer = "0.5.0"
malachite = "0.9.0" # arbitrary-precision math
include_dir = { version = "0.7.4", features = ["glob"] }
csv = "1.4.0"
clap = { version = "4.5.54", features = ["cargo", "derive", "unicode"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"

[lints]
workspace = true
