# This is the canonical source of config.toml, which it is copied to by the build script.

[build]
# rustflags = ["--cfg", "tokio_unstable"]
# You may need to adjust this depending on your system.
# This is to avoid overloading the system when building.
# jobs = 6
rustflags = ["-A", "warnings", "-A", "unfulfilled_lint_expectations"]

[target.i586-unknown-linux-musl]
linker = "scripts/i586-musl-gcc"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-gcc-ar"

# Must have [env] table as last entry in config.toml so config.vendored.toml can append to it
[env]
# Resolves 'scripts/i586-musl-gcc' relative to this config file
CC_i586_unknown_linux_musl = { value = "scripts/i586-musl-gcc", relative = true }
CC_x86_64_unknown_linux_musl = { value = "scripts/x86_64-musl-gcc", relative = true }

PKG_CONFIG_SYSROOT_DIR_i586_unknown_linux_musl = { value = "/usr/include/i386-linux-musl" }
PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_musl = { value = "/usr/include/x86_64-linux-musl" }
