[build]
# rustflags = ["--cfg", "tokio_unstable"]
# You may need to adjust this depending on your system.
# This is to avoid overloading the system when building.
# jobs = 6
incremental = false

[target.i586-unknown-linux-musl]
linker = "scripts/i586-musl-gcc"

[env]
# Resolves 'scripts/i586-musl-gcc' relative to this config file
CC_i586_unknown_linux_musl = { value = "scripts/i586-musl-gcc", relative = true }
CC_x86_64_unknown_linux_musl = { value = "scripts/x86_64-musl-gcc", relative = true }

PKG_CONFIG_SYSROOT_DIR_i586_unknown_linux_musl = { value = "/usr/include/i386-linux-musl" }
PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_musl = { value = "/usr/include/x86_64-linux-musl" }



[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor/ctb-vendored/vendor"

[source."https://github.com/boa-dev/boa.git"]
git = "https://github.com/boa-dev/boa.git"
rev = "ffec9244d4267406d66aef8b3c8a1d89730df5b4"
replace-with = "vendored-sources"

[source."https://github.com/rust-dark-light/dark-light.git"]
git = "https://github.com/rust-dark-light/dark-light.git"
rev = "0f18d2fbcaa5d1c175db8aae7d53428988d7e961"
replace-with = "vendored-sources"
