// SPDX-License-Identifier: AGPL-3.0-or-later
/*
This file is part of Collective Toolbox, a database and document workspace and utilities.
Copyright (C) 2026 Collective Toolbox Developers
Contact: info@collectivetoolbox.com

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along
with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// IPC service for workspace process.
//
// @generated by ctb-build-support::ipc_codegen
// Do not edit by hand.

ctb_workspace_ipc_macro::workspace_ipc_methods! {
    async fn get_crlite_artifact(relative_path: & str) -> Result < Vec < u8 > >;
    async fn get_crlite_cache_status() -> Result < String >;
    async fn get_crlite_manifest_json() -> Result < String >;
    async fn get_update_status() -> Result < String >;
    async fn ping(input: u8) -> Result < u8 >;
}
