// @generated by ctb-build-support::ipc_codegen
//
// Do not edit by hand.

ipc_service_client! {
    service: formats,
    methods: {
        async fn decode(&self, bytes: Vec < u8 >) -> Result<Option < (u128 , usize) >>
            => ::ctb_formats::utf_8e_128::DecodeIpcClientExt(bytes);
        async fn encode(&self, codepoint: u128) -> Result<Vec < u8 >>
            => ::ctb_formats::utf_8e_128::EncodeIpcClientExt(codepoint);
        async fn utf_8e_128__decode(&self, bytes: Vec < u8 >) -> Result<Option < (u128 , usize) >>
            => ::ctb_formats_utf_8e_128::DecodeIpcClientExt("decode", bytes);
        async fn utf_8e_128__encode(&self, codepoint: u128) -> Result<Vec < u8 >>
            => ::ctb_formats_utf_8e_128::EncodeIpcClientExt("encode", codepoint);
    }
}
