// SPDX-License-Identifier: AGPL-3.0-or-later
/*
Copyright (C) 2026 Collective Toolbox Developers
Contact: info@collectivetoolbox.com

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along
with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// @generated by ctb-build-support::ipc_codegen
//
// Do not edit by hand.

ipc_service_client! {
    service: formats,
    methods: {
        async fn decode(&self, bytes: Vec < u8 >) -> Result<Option < (u128 , usize) >>
            => ::ctb_formats::utf_8e_128::DecodeIpcClientExt(bytes);
        async fn encode(&self, codepoint: u128) -> Result<Vec < u8 >>
            => ::ctb_formats::utf_8e_128::EncodeIpcClientExt(codepoint);
        async fn utf_8e_128__decode(&self, bytes: Vec < u8 >) -> Result<Option < (u128 , usize) >>
            => ::ctb_formats_utf_8e_128::DecodeIpcClientExt("decode", bytes);
        async fn utf_8e_128__encode(&self, codepoint: u128) -> Result<Vec < u8 >>
            => ::ctb_formats_utf_8e_128::EncodeIpcClientExt("encode", codepoint);
    }
}
