#![allow(
    non_upper_case_globals,
    reason = "autogenerated generated file structure"
)]

#[expect(
    unused_imports,
    clippy::wildcard_imports,
    reason = "Standard workspace module prelude"
)]
use crate::utilities::*;

include!("formats.generated.rs");
