// @generated by ctb-build-support::ipc_codegen
//
// Do not edit by hand.

ipc_service_client! {
    service: io,
    methods: {
        async fn print(&self, document: Vec < u8 >) -> Result<()>
            => ::ctb_io::PrintIpcClientExt(document);
        async fn print_string(&self, document: & str) -> Result<()>
            => ::ctb_io::PrintStringIpcClientExt(document.to_string());
        async fn start_local_webui(&self) -> Result<u16>
            => ::ctb_io::StartLocalWebuiIpcClientExt();
    }
}
