// SPDX-License-Identifier: AGPL-3.0-or-later
/*
This file is part of Collective Toolbox, a database and document workspace and utilities.
Copyright (C) 2026 Collective Toolbox Developers
Contact: info@collectivetoolbox.com

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along
with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// IPC service for io process.
//
// @generated by ctb-build-support::ipc_codegen
// Do not edit by hand.

// DTO conversion helpers (service DTO -> service crate type)

fn to_ctb_io_environment_env_description(v: &::ctb_utilities::ipc::service_traits::io::EnvDescription) -> ::ctb_io_environment::EnvDescription {
    ::ctb_io_environment::EnvDescription {
        os: v.os.clone(),
        usize_width: v.usize_width.clone(),
        ctb_version: v.ctb_version.clone(),
        cwd: v.cwd.clone(),
        local_ips: v.local_ips.clone(),
        public_ips: v.public_ips.clone(),
        system_time_resolution_nanos: v.system_time_resolution_nanos.clone(),
        server_system_time_offset_nanos: v.server_system_time_offset_nanos.clone(),
        is_release_build: v.is_release_build.clone(),
        is_debug_build: v.is_debug_build.clone(),
        is_cargo_target_binary: v.is_cargo_target_binary.clone(),
        is_in_test: v.is_in_test.clone(),
        is_branded_build: v.is_branded_build.clone(),
        is_official_signed_build: v.is_official_signed_build.clone(),
        is_cli_lightweight: v.is_cli_lightweight.clone(),
        is_workspace: v.is_workspace.clone(),
        is_workspace_main_process: v.is_workspace_main_process.clone(),
        is_service_subprocess: v.is_service_subprocess.clone(),
        is_official_public_website: v.is_official_public_website.clone(),
        is_public_website: v.is_public_website.clone(),
        is_local: v.is_local.clone(),
        additional_support: v.additional_support.clone(),
        extra: v.extra.clone(),
    }
}


ipc_service_client! {
    service: io,
    methods: {
        async fn print(&self, document: Vec < u8 >) -> Result<()>
            => ::ctb_io::PrintIpcClientExt(document);
        async fn print_string(&self, document: & str) -> Result<()>
            => ::ctb_io::PrintStringIpcClientExt(document.to_string());
        async fn start_local_webui(&self) -> Result<u16>
            => ::ctb_io::StartLocalWebuiIpcClientExt();
    }
}
