// @generated by ctb-build-support::ipc_codegen
//
// Do not edit by hand.

ipc_service_client! {
    service: network,
    methods: {
        async fn echo(&self, bytes: Vec < u8 >) -> Result<Vec < u8 >>
            => ::ctb_network::EchoIpcClientExt(bytes);
        async fn fetch(&self, url: & str) -> Result<Vec < u8 >>
            => ::ctb_network::FetchIpcClientExt(url.to_string());
        async fn read_file(&self, path: & str) -> Result<Vec < u8 >>
            => ::ctb_network::ReadFileIpcClientExt(path.to_string());
    }
}
