// @generated by ctb-build-support::ipc_codegen
//
// Do not edit by hand.

// DTO conversion helpers (service DTO -> service crate type)

fn to_ctb_renderer_render_mode(v: &::ctb_utilities::ipc::service_traits::renderer::RenderMode) -> ::ctb_renderer::RenderMode {
    match v {
        ::ctb_utilities::ipc::service_traits::renderer::RenderMode::Immediate => ::ctb_renderer::RenderMode::Immediate,
        ::ctb_utilities::ipc::service_traits::renderer::RenderMode::Interactive => ::ctb_renderer::RenderMode::Interactive,
    }
}

fn to_ctb_renderer_render_settings(v: &::ctb_utilities::ipc::service_traits::renderer::RenderSettings) -> ::ctb_renderer::RenderSettings {
    ::ctb_renderer::RenderSettings {
        mode: to_ctb_renderer_render_mode(&v.mode),
        target: to_ctb_renderer_render_target(&v.target),
    }
}

fn to_ctb_renderer_render_target(v: &::ctb_utilities::ipc::service_traits::renderer::RenderTarget) -> ::ctb_renderer::RenderTarget {
    match v {
        ::ctb_utilities::ipc::service_traits::renderer::RenderTarget::Teletype => ::ctb_renderer::RenderTarget::Teletype,
        ::ctb_utilities::ipc::service_traits::renderer::RenderTarget::Videoterminal => ::ctb_renderer::RenderTarget::Videoterminal,
        ::ctb_utilities::ipc::service_traits::renderer::RenderTarget::Web => ::ctb_renderer::RenderTarget::Web,
        ::ctb_utilities::ipc::service_traits::renderer::RenderTarget::Raster => ::ctb_renderer::RenderTarget::Raster,
        ::ctb_utilities::ipc::service_traits::renderer::RenderTarget::Vector => ::ctb_renderer::RenderTarget::Vector,
        ::ctb_utilities::ipc::service_traits::renderer::RenderTarget::Print => ::ctb_renderer::RenderTarget::Print,
    }
}


ipc_service_client! {
    service: renderer,
    methods: {
        async fn render_from_string(&self, document: & str, settings: ::ctb_utilities::ipc::service_traits::renderer::RenderSettings) -> Result<String>
            => ::ctb_renderer::RenderFromStringIpcClientExt(document.to_string(), to_ctb_renderer_render_settings(&settings));
        async fn test_echo_3x(&self, document: & str) -> Result<String>
            => ::ctb_renderer::TestEcho3xIpcClientExt(document.to_string());
        async fn test_prepend(&self, document: & str, prepend: & str) -> Result<String>
            => ::ctb_renderer::TestPrependIpcClientExt(document.to_string(), prepend);
    }
}
