// SPDX-License-Identifier: AGPL-3.0-or-later
/*
This file is part of Collective Toolbox, a database and document workspace and utilities.
Copyright (C) 2026 Collective Toolbox Developers
Contact: info@collectivetoolbox.com

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along
with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// @generated by ctb-build-support::ipc_codegen
//
// Do not edit by hand.

// DTO conversion helpers (service DTO -> service crate type)

fn to_ctb_renderer_render_mode(v: &::ctb_utilities::ipc::service_traits::renderer::RenderMode) -> ::ctb_renderer::RenderMode {
    match v {
        ::ctb_utilities::ipc::service_traits::renderer::RenderMode::Immediate => ::ctb_renderer::RenderMode::Immediate,
        ::ctb_utilities::ipc::service_traits::renderer::RenderMode::Interactive => ::ctb_renderer::RenderMode::Interactive,
    }
}

fn to_ctb_renderer_render_settings(v: &::ctb_utilities::ipc::service_traits::renderer::RenderSettings) -> ::ctb_renderer::RenderSettings {
    ::ctb_renderer::RenderSettings {
        mode: to_ctb_renderer_render_mode(&v.mode),
        target: to_ctb_renderer_render_target(&v.target),
    }
}

fn to_ctb_renderer_render_target(v: &::ctb_utilities::ipc::service_traits::renderer::RenderTarget) -> ::ctb_renderer::RenderTarget {
    match v {
        ::ctb_utilities::ipc::service_traits::renderer::RenderTarget::Teletype => ::ctb_renderer::RenderTarget::Teletype,
        ::ctb_utilities::ipc::service_traits::renderer::RenderTarget::Videoterminal => ::ctb_renderer::RenderTarget::Videoterminal,
        ::ctb_utilities::ipc::service_traits::renderer::RenderTarget::Web => ::ctb_renderer::RenderTarget::Web,
        ::ctb_utilities::ipc::service_traits::renderer::RenderTarget::Raster => ::ctb_renderer::RenderTarget::Raster,
        ::ctb_utilities::ipc::service_traits::renderer::RenderTarget::Vector => ::ctb_renderer::RenderTarget::Vector,
        ::ctb_utilities::ipc::service_traits::renderer::RenderTarget::Print => ::ctb_renderer::RenderTarget::Print,
    }
}


ipc_service_client! {
    service: renderer,
    methods: {
        async fn render_from_string(&self, document: & str, settings: ::ctb_utilities::ipc::service_traits::renderer::RenderSettings) -> Result<String>
            => ::ctb_renderer::RenderFromStringIpcClientExt(document.to_string(), to_ctb_renderer_render_settings(&settings));
        async fn test_echo_3x(&self, document: & str) -> Result<String>
            => ::ctb_renderer::TestEcho3xIpcClientExt(document.to_string());
        async fn test_prepend(&self, document: & str, prepend: & str) -> Result<String>
            => ::ctb_renderer::TestPrependIpcClientExt(document.to_string(), prepend);
    }
}
