// @generated by ctb-build-support::ipc_codegen
//
// Do not edit by hand.

ipc_service_client! {
    service: runtime,
    methods: {
        async fn start(&self, document: Vec < u8 >) -> Result<i32>
            => ::ctb_runtime::StartIpcClientExt(document);
        async fn test_prepend(&self, document: & str, prepend: & str) -> Result<String>
            => ::ctb_runtime::TestPrependIpcClientExt(document.to_string(), prepend.to_string());
        async fn test_simple_nested_document(&self, document: & str, settings: RenderSettings) -> Result<i32>
            => ::ctb_runtime::TestSimpleNestedDocumentIpcClientExt(document.to_string(), settings);
    }
}
