// SPDX-License-Identifier: AGPL-3.0-or-later
/*
Copyright (C) 2026 Collective Toolbox Developers
Contact: info@collectivetoolbox.com

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along
with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// @generated by ctb-build-support::ipc_codegen
//
// Do not edit by hand.

ipc_service_client! {
    service: runtime,
    methods: {
        async fn start(&self, document: Vec < u8 >) -> Result<i32>
            => ::ctb_runtime::StartIpcClientExt(document);
        async fn test_prepend(&self, document: & str, prepend: & str) -> Result<String>
            => ::ctb_runtime::TestPrependIpcClientExt(document.to_string(), prepend.to_string());
        async fn test_simple_nested_document(&self, document: & str, settings: RenderSettings) -> Result<i32>
            => ::ctb_runtime::TestSimpleNestedDocumentIpcClientExt(document.to_string(), settings);
    }
}
