// @generated by ctb-build-support::ipc_codegen
//
// Do not edit by hand.

// DTO conversion helpers (service DTO -> service crate type)

fn to_ctb_storage_node(v: &::ctb_utilities::ipc::service_traits::storage::Node) -> ::ctb_storage::models::node::Node {
    ::ctb_storage::models::node::Node {
        id: v.id,
        graph_id: v.graph_id,
        node_type: to_ctb_storage_node_type(&v.node_type),
        data: v.data.clone(),
        checksum: v.checksum.clone(),
    }
}

fn to_ctb_storage_node_type(v: &::ctb_utilities::ipc::service_traits::storage::NodeType) -> ::ctb_storage::models::node::NodeType {
    match v {
        ::ctb_utilities::ipc::service_traits::storage::NodeType::Data => ::ctb_storage::models::node::NodeType::Data,
        ::ctb_utilities::ipc::service_traits::storage::NodeType::Statements => ::ctb_storage::models::node::NodeType::Statements,
        ::ctb_utilities::ipc::service_traits::storage::NodeType::System => ::ctb_storage::models::node::NodeType::System,
    }
}

fn to_ctb_storage_table_row(v: &::ctb_utilities::ipc::service_traits::storage::TableRow) -> ::ctb_storage::db::TableRow {
    ::ctb_storage::db::TableRow {
        columns: v.columns.clone(),
        values: v.values.clone(),
        page: v.page,
        total_pages: v.total_pages,
        total_rows: v.total_rows,
    }
}

fn to_ctb_storage_user_dto(v: &::ctb_utilities::ipc::service_traits::storage::UserDto) -> ::ctb_storage::models::user_impl::UserDto {
    ::ctb_storage::models::user_impl::UserDto {
        id: v.id,
        username: v.username.clone(),
        uuid: v.uuid.clone(),
        auth: v.auth.clone(),
        display_name: v.display_name.clone(),
        picture: v.picture.clone(),
        key_encryption_key_params: v.key_encryption_key_params.clone(),
        wrapped_dek: v.wrapped_dek.clone(),
        pubkey: v.pubkey.clone(),
        subscription_expiry: v.subscription_expiry,
        token_quota: v.token_quota,
        remote_status: v.remote_status.clone(),
    }
}


ipc_service_client! {
    service: storage,
    methods: {
        async fn allocate_next_remote_range(&self, graph_id: u128) -> Result<u64>
            => ::ctb_storage::models::sync_impl::AllocateNextRemoteRangeIpcClientExt(graph_id);
        async fn allocate_next_system_id(&self, session_token: & str) -> Result<u128>
            => ::ctb_storage::models::graph_impl::AllocateNextSystemIdIpcClientExt(session_token.to_string());
        async fn create_user(&self, user: ::ctb_utilities::ipc::service_traits::storage::UserDto) -> Result<()>
            => ::ctb_storage::models::user_impl::CreateUserIpcClientExt(to_ctb_storage_user_dto(&user));
        async fn create_user_and_session(&self, username: & str, password_bytes: Vec < u8 >, duration_secs: u64) -> Result<String>
            => ::ctb_storage::models::user::session::CreateUserAndSessionIpcClientExt(username.to_string(), password_bytes, duration_secs);
        async fn delete_local_token(&self, user_id: u64, key: u64) -> Result<()>
            => ::ctb_storage::models::sync_impl::DeleteLocalTokenIpcClientExt(user_id, key);
        async fn delete_user_by_id(&self, id: u64) -> Result<()>
            => ::ctb_storage::models::user_impl::DeleteUserByIdIpcClientExt(id);
        async fn deregister_user(&self, user_id: u64) -> Result<()>
            => ::ctb_storage::models::user::session::DeregisterUserIpcClientExt(user_id);
        async fn get_all_user_ids(&self) -> Result<Vec < u64 >>
            => ::ctb_storage::models::user_impl::GetAllUserIdsIpcClientExt();
        async fn get_formatted_table_data(&self, session_token: & str, db_name: & str, table_name: & str, page: u32) -> Result<:: ctb_utilities :: ipc :: service_traits :: storage :: TableRow>
            => ::ctb_storage::models::graph_impl::GetFormattedTableDataIpcClientExt(session_token.to_string(), db_name.to_string(), table_name.to_string(), page);
        async fn get_local_id_range(&self, user_id: u64, graph_id: u128) -> Result<Option < Vec < u8 > >>
            => ::ctb_storage::models::sync_impl::GetLocalIdRangeIpcClientExt(user_id, graph_id);
        async fn get_local_tokens(&self, user_id: u64) -> Result<Vec < (u64 , String) >>
            => ::ctb_storage::models::sync_impl::GetLocalTokensIpcClientExt(user_id);
        async fn get_node(&self, session_token: & str, graph_id: u128, id: u128) -> Result<Option < Vec < u8 > >>
            => ::ctb_storage::models::node_impl::GetNodeIpcClientExt(session_token.to_string(), graph_id, id);
        async fn get_node_dto(&self, session_token: & str, graph_id: u128, id: u128) -> Result<Option < :: ctb_utilities :: ipc :: service_traits :: storage :: Node >>
            => ::ctb_storage::models::node_impl::GetNodeDtoIpcClientExt(session_token.to_string(), graph_id, id);
        async fn get_sync_chunk(&self, hash: & str) -> Result<Option < Vec < u8 > >>
            => ::ctb_storage::models::sync_impl::GetSyncChunkIpcClientExt(hash.to_string());
        async fn get_user_by_id(&self, id: u64) -> Result<Option < :: ctb_utilities :: ipc :: service_traits :: storage :: UserDto >>
            => ::ctb_storage::models::user_impl::GetUserByIdIpcClientExt(id);
        async fn get_user_by_name(&self, name: & str) -> Result<Option < :: ctb_utilities :: ipc :: service_traits :: storage :: UserDto >>
            => ::ctb_storage::models::user_impl::GetUserByNameIpcClientExt(name.to_string());
        async fn get_voprf_key(&self) -> Result<Option < Vec < u8 > >>
            => ::ctb_storage::models::user_impl::GetVoprfKeyIpcClientExt();
        async fn increment_and_get_user_id(&self) -> Result<u64>
            => ::ctb_storage::models::user_impl::IncrementAndGetUserIdIpcClientExt();
        async fn insert_node(&self, session_token: & str, graph_id: u128, node_type: ::ctb_utilities::ipc::service_traits::storage::NodeType, data: & [u8]) -> Result<u128>
            => ::ctb_storage::models::node_impl::InsertNodeIpcClientExt(session_token.to_string(), graph_id, to_ctb_storage_node_type(&node_type), data);
        async fn invalidate_session(&self, token: & str) -> Result<()>
            => ::ctb_storage::models::user::session::InvalidateSessionIpcClientExt(token.to_string());
        async fn is_token_spent(&self, serial_hex: & str) -> Result<bool>
            => ::ctb_storage::models::sync_impl::IsTokenSpentIpcClientExt(serial_hex.to_string());
        async fn list_databases(&self, session_token: & str) -> Result<Vec < String >>
            => ::ctb_storage::models::graph_impl::ListDatabasesIpcClientExt(session_token.to_string());
        async fn list_nodes(&self, session_token: & str) -> Result<Vec < :: ctb_utilities :: ipc :: service_traits :: storage :: Node >>
            => ::ctb_storage::models::node_impl::ListNodesIpcClientExt(session_token.to_string());
        async fn list_tables(&self, session_token: & str, db_name: & str) -> Result<Vec < String >>
            => ::ctb_storage::models::graph_impl::ListTablesIpcClientExt(session_token.to_string(), db_name.to_string());
        async fn login_user(&self, username: & str, password_bytes: Vec < u8 >, duration_secs: u64) -> Result<String>
            => ::ctb_storage::models::user::session::LoginUserIpcClientExt(username.to_string(), password_bytes, duration_secs);
        async fn publish_packaged_node_to_global(&self, session_token: & str, package: Vec < u8 >, target_id: Option < u128 >) -> Result<u128>
            => ::ctb_storage::models::graph_impl::PublishPackagedNodeToGlobalIpcClientExt(session_token.to_string(), package, target_id);
        async fn refresh_session(&self, token: & str, duration_secs: u64) -> Result<()>
            => ::ctb_storage::models::user::session::RefreshSessionIpcClientExt(token.to_string(), duration_secs);
        async fn rename_user(&self, id: u64, new_username: & str) -> Result<()>
            => ::ctb_storage::models::user_impl::RenameUserIpcClientExt(id, new_username.to_string());
        async fn save_local_id_range(&self, user_id: u64, graph_id: u128, range_bytes: Vec < u8 >) -> Result<()>
            => ::ctb_storage::models::sync_impl::SaveLocalIdRangeIpcClientExt(user_id, graph_id, range_bytes);
        async fn save_local_token(&self, user_id: u64, key: u64, token: & str) -> Result<()>
            => ::ctb_storage::models::sync_impl::SaveLocalTokenIpcClientExt(user_id, key, token.to_string());
        async fn save_sync_chunk(&self, hash: & str, data: Vec < u8 >, expiry: u64) -> Result<()>
            => ::ctb_storage::models::sync_impl::SaveSyncChunkIpcClientExt(hash.to_string(), data, expiry);
        async fn save_voprf_key(&self, key: Vec < u8 >) -> Result<()>
            => ::ctb_storage::models::user_impl::SaveVoprfKeyIpcClientExt(key);
        async fn spend_token(&self, serial_hex: & str) -> Result<()>
            => ::ctb_storage::models::sync_impl::SpendTokenIpcClientExt(serial_hex.to_string());
        async fn update_node_data(&self, session_token: & str, graph_id: u128, node_id: u128, data: Vec < u8 >) -> Result<()>
            => ::ctb_storage::models::node_impl::UpdateNodeDataIpcClientExt(session_token.to_string(), graph_id, node_id, data);
        async fn update_node_type(&self, session_token: & str, graph_id: u128, node_id: u128, node_type: ::ctb_utilities::ipc::service_traits::storage::NodeType) -> Result<()>
            => ::ctb_storage::models::node_impl::UpdateNodeTypeIpcClientExt(session_token.to_string(), graph_id, node_id, to_ctb_storage_node_type(&node_type));
        async fn update_user(&self, user: ::ctb_utilities::ipc::service_traits::storage::UserDto) -> Result<()>
            => ::ctb_storage::models::user_impl::UpdateUserIpcClientExt(to_ctb_storage_user_dto(&user));
        async fn validate_session(&self, token: & str) -> Result<Option < u64 >>
            => ::ctb_storage::models::user::session::ValidateSessionIpcClientExt(token.to_string());
    }
}
