// SPDX-License-Identifier: AGPL-3.0-or-later
/*
This file is part of Collective Toolbox, a database and document workspace and utilities.
Copyright (C) 2026 Collective Toolbox Developers
Contact: info@collectivetoolbox.com

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along
with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

//! Codegen for supported compression `FormatId` list and verification from
//! `compression.csv` support data.

use anyhow::{Context, Result, ensure};
use std::fs;
use std::path::Path;

use crate::find_repository_root_from;
use crate::license_consts::DEFAULT_AGPL_HEADER;

fn write_if_changed(path: &Path, content: &str) -> Result<bool> {
    if path.is_file() {
        if let Ok(existing) = fs::read_to_string(path) {
            if existing == content {
                return Ok(false);
            }
        }
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, content)?;
    Ok(true)
}

/// A parsed compression format record with support status.
#[derive(Debug, Clone, PartialEq, Eq)]
struct CompressionRecord {
    ident: String,
    label: String,
}

/// Generates Rust code for supported compression `FormatId` list and checks.
///
/// # Errors
/// Returns an error if reading or parsing `compression.csv` fails.
pub fn generate_compression_format_code(compression_csv: &Path) -> Result<String> {
    ensure!(
        compression_csv.is_file(),
        "Could not locate compression.csv at {}",
        compression_csv.display()
    );

    let content = fs::read_to_string(compression_csv)
        .with_context(|| format!("Reading {}", compression_csv.display()))?;

    let mut records: Vec<CompressionRecord> = Vec::new();

    let mut rdr = csv::ReaderBuilder::new()
        .has_headers(true)
        .flexible(true)
        .from_reader(content.as_bytes());

    for result in rdr.records() {
        let record = result?;
        let get = |idx: usize| -> String {
            record.get(idx).unwrap_or("").trim().to_string()
        };

        let ident = get(2);
        let label = get(3);
        let import_support = get(11);
        let export_support = get(12);
        let tests_support = get(13);

        let is_supported = import_support.parse::<i32>().unwrap_or(0) >= 2
            || export_support.parse::<i32>().unwrap_or(0) >= 2
            || tests_support.parse::<i32>().unwrap_or(0) >= 2;

        if is_supported && !ident.is_empty() {
            records.push(CompressionRecord { ident, label });
        }
    }

    let mut out = String::new();
    out.push_str(DEFAULT_AGPL_HEADER);
    out.push_str("\n// @generated by ctb-build-support::compression_codegen from format category data tables.\n\n");

    out.push_str("/// Ordered list of all compression formats supported by this crate.\n");
    out.push_str("pub const SUPPORTED: &[FormatId] = &[\n");
    for r in &records {
        out.push_str(&format!("    FormatId::{},\n", r.ident));
    }
    out.push_str("];\n\n");

    out.push_str("/// Returns true if the given `FormatId` is supported for compression/decompression by this crate.\n");
    out.push_str("#[must_use]\n");
    out.push_str("pub const fn is_supported(format: FormatId) -> bool {\n");
    out.push_str("    matches!(\n");
    out.push_str("        format,\n");
    for (i, r) in records.iter().enumerate() {
        if i == 0 {
            out.push_str(&format!("        FormatId::{}", r.ident));
        } else {
            out.push_str(&format!("\n            | FormatId::{}", r.ident));
        }
    }
    out.push_str("\n    )\n");
    out.push_str("}\n");

    Ok(out)
}

/// Generates `compression_format.generated.rs` in `src/formats/compression/`.
///
/// # Errors
/// Returns an error if root lookup or writing fails.
pub fn generate_compression_format_file(base_dir: &Path) -> Result<bool> {
    let repo_root = find_repository_root_from(base_dir)?;
    let compression_csv = repo_root
        .join("src")
        .join("formats")
        .join("dcdata")
        .join("data")
        .join("categories")
        .join("formats")
        .join("compression.csv");

    ensure!(
        compression_csv.is_file(),
        "Could not locate compression.csv at {}",
        compression_csv.display()
    );

    let target_file = repo_root
        .join("src")
        .join("formats")
        .join("compression")
        .join("compression_format.generated.rs");

    let code = generate_compression_format_code(&compression_csv)?;
    write_if_changed(&target_file, &code)
}
