// SPDX-License-Identifier: AGPL-3.0-or-later
/*
Copyright (C) 2026 Collective Toolbox Developers
Contact: info@collectivetoolbox.com

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along
with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

//! Build-time IPC code generation.
//!
//! This module scans the workspace source tree for `#[ipc_method]` functions
//! and emits small glue modules into a crate-local `built/` directory.
//!
//! Today this is used to generate the workspace IPC client method list consumed
//! by `ctb-utilities` (see `ipc/workspace_client.rs`).

use anyhow::{Context, Result, anyhow, bail};
use cargo_metadata::MetadataCommand;
use quote::ToTokens as _;
use std::ffi::OsStr;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

/// IPC services that are generated from `#[ipc_method]` functions.
///
/// `parent` and `process` are intentionally excluded because they are
/// workspace-internal special cases.
const GENERATED_SERVICES: &[&str] =
    &["formats", "io", "network", "renderer", "runtime", "storage"];

fn push_generated(out: &mut String) {
    out.push_str("// @generated by ctb-build-support::ipc_codegen\n");
    out.push_str("//\n");
    out.push_str("// Do not edit by hand.\n\n");
}

fn write_if_changed(path: &Path, content: &str) -> Result<()> {
    if path.exists() {
        if let Ok(existing) = fs::read_to_string(path) {
            if existing == content {
                return Ok(());
            }
        }
    }

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).with_context(|| {
            format!("Failed to create directory {}", parent.display())
        })?;
    }

    fs::write(path, content)
        .with_context(|| format!("Failed to write file {}", path.display()))?;

    Ok(())
}

/// Generate the workspace IPC method list used by `ctb-utilities`.
///
/// This scans the `ctb-workspace` crate for `#[ipc_method]` functions that are
/// compatible with `ctb_workspace_ipc_macro::workspace_ipc_methods!` and emits a
/// Rust source file into `output_root/ipc/`.
///
/// The generated file contains a single `workspace_ipc_methods! { ... }`
/// invocation.
///
/// # Errors
/// Returns an error if metadata cannot be loaded, files cannot be read/parsed,
/// or the output file cannot be written.
#[expect(
    clippy::too_many_lines,
    reason = "generate_workspace_ipc_methods is a long code generator function"
)]
pub fn generate_workspace_ipc_methods(output_root: &Path) -> Result<()> {
    let metadata = MetadataCommand::new()
        .exec()
        .context("Failed to run cargo metadata")?;

    let workspace_pkg = metadata
        .packages
        .iter()
        .find(|p| p.name == "ctb-workspace")
        .ok_or_else(|| {
            anyhow!("Could not find package 'ctb-workspace' in workspace")
        })?;

    let crate_root = workspace_pkg
        .manifest_path
        .parent()
        .ok_or_else(|| {
            anyhow!("ctb-workspace manifest has no parent directory")
        })?
        .as_std_path();

    println!("cargo:rerun-if-changed={}", workspace_pkg.manifest_path);

    let mut rs_files = Vec::new();
    collect_rs_files(crate_root, &mut rs_files)?;
    for p in &rs_files {
        println!("cargo:rerun-if-changed={}", p.display());
    }

    let extracted = extract_ipc_methods(&rs_files)?;
    let extracted_dtos = extract_ipc_dtos(&rs_files)?;

    let mut sigs = Vec::new();
    let mut skipped = Vec::new();

    for m in extracted {
        match workspace_ipc_signature_from_item(&m.item_fn) {
            Ok(Some(sig)) => sigs.push(sig),
            Ok(None) => skipped.push(m.reason.unwrap_or_else(|| {
                format!(
                    "{}: skipped (not compatible with workspace IPC codegen)",
                    m.path.display()
                )
            })),
            Err(e) => skipped.push(format!(
                "{}: skipped (signature extraction failed: {e})",
                m.path.display()
            )),
        }
    }

    if sigs.is_empty() {
        bail!(
            "No compatible #[ipc_method] functions found in ctb-workspace; \
			 cannot generate workspace IPC method list"
        );
    }

    sigs.sort_by(|a, b| a.method_name.cmp(&b.method_name));

    let mut out = String::new();
    push_generated(&mut out);
    out.push_str("ctb_workspace_ipc_macro::workspace_ipc_methods! {\n");

    for sig in &sigs {
        out.push_str("    ");
        out.push_str(&sig.rendered);
        out.push('\n');
    }

    out.push_str("}\n");

    let ipc_dir = output_root.join("ipc");
    fs::create_dir_all(&ipc_dir).with_context(|| {
        format!(
            "Failed to create generated IPC directory {}",
            ipc_dir.display()
        )
    })?;

    let out_path = ipc_dir.join("workspace_ipc_methods.generated.rs");
    write_if_changed(&out_path, &out).with_context(|| {
        format!(
            "Failed to write generated workspace IPC method list to {}",
            out_path.display()
        )
    })?;

    // Generate a DTO fragment for the workspace client even if no DTOs are
    // currently declared. This allows callers to add `include!()` immediately
    // without surprising missing-file errors when DTOs are introduced later.
    let mut out = String::new();
    push_generated(&mut out);

    let mut sorted: Vec<ExtractedDto> =
        extracted_dtos.into_iter().map(|d| d.dto).collect();
    sorted.sort_by_key(|d| match d {
        ExtractedDto::Enum(e) => e.ident.to_string(),
        ExtractedDto::Struct(s) => s.ident.to_string(),
    });

    for d in &sorted {
        match d {
            ExtractedDto::Enum(e) => {
                write_doc_lines(&mut out, &e.doc_lines);
                let _ = writeln!(
                    out,
                    "#[derive(Debug, Clone, Copy, PartialEq, Eq, ::serde::Serialize, ::serde::Deserialize)]"
                );
                let _ = writeln!(out, "pub enum {} {{", e.ident);
                for v in &e.variants {
                    write_doc_lines(&mut out, &v.doc_lines);
                    let _ = writeln!(out, "    {},", v.ident);
                }
                out.push_str("}\n\n");
            }
            ExtractedDto::Struct(s) => {
                write_doc_lines(&mut out, &s.doc_lines);
                let _ = writeln!(
                    out,
                    "#[derive(Debug, Clone, ::serde::Serialize, ::serde::Deserialize)]"
                );
                let _ = writeln!(out, "pub struct {} {{", s.ident);
                for f in &s.fields {
                    write_doc_lines(&mut out, &f.doc_lines);
                    let ty = f.ty.to_token_stream().to_string();
                    let _ = writeln!(out, "    pub {}: {ty},", f.ident);
                }
                out.push_str("}\n\n");
            }
        }
    }

    let dtos_path = ipc_dir.join("workspace_ipc_methods.dtos.generated.rs");
    write_if_changed(&dtos_path, &out).with_context(|| {
        format!(
            "Failed to write generated workspace IPC DTO fragment to {}",
            dtos_path.display()
        )
    })?;

    for note in skipped {
        println!("cargo:warning=IPC codegen: {note}");
    }

    Ok(())
}

/// Generate IPC boilerplate for service traits and workspace service clients.
///
/// This scans all workspace crates for `#[ipc_method]` functions and emits:
///
/// - `ctb-utilities`: `ipc/service_traits/<service>.generated.rs`
///   (method lists intended to be `include!()`d inside the corresponding
///   `*ClientTrait`)
/// - `ctb-workspace`: `ipc/services/<service>.generated.rs`
///   (an `ipc_service_client! { ... }` invocation matching the service trait)
///
/// # Errors
/// Returns an error if metadata cannot be loaded, files cannot be read/parsed,
/// or any output file cannot be written.
#[expect(
    clippy::too_many_lines,
    reason = "generate_ipc_service_boilerplate is a long code generator function"
)]
pub fn generate_ipc_service_boilerplate(output_root: &Path) -> Result<()> {
    let metadata = MetadataCommand::new()
        .exec()
        .context("Failed to run cargo metadata")?;

    let utilities_pkg = metadata
        .packages
        .iter()
        .find(|p| p.name == "ctb-utilities")
        .ok_or_else(|| {
            anyhow!("Could not find package 'ctb-utilities' in workspace")
        })?;

    let workspace_pkg = metadata
        .packages
        .iter()
        .find(|p| p.name == "ctb-workspace-ipc")
        .ok_or_else(|| {
            anyhow!("Could not find package 'ctb-workspace-ipc' in workspace")
        })?;

    let utilities_root = utilities_pkg
        .manifest_path
        .parent()
        .ok_or_else(|| {
            anyhow!("ctb-utilities manifest has no parent directory")
        })?
        .as_std_path();

    let workspace_root = workspace_pkg
        .manifest_path
        .parent()
        .ok_or_else(|| {
            anyhow!("ctb-workspace-ipc manifest has no parent directory")
        })?
        .as_std_path();

    // `output_root` is passed from `ctb-utilities/build.rs`. Ensure this matches
    // the metadata-derived directory so includes resolve predictably.
    if output_root != utilities_root {
        println!(
            "cargo:warning=IPC codegen: output_root {} does not match ctb-utilities dir {}",
            output_root.display(),
            utilities_root.display()
        );
    }

    let mut rs_files_by_pkg: Vec<(String, PathBuf, Vec<PathBuf>)> = Vec::new();

    for pkg in &metadata.packages {
        let (service, _subservice) = service_and_subservice_from_pkg(&pkg.name);
        if !GENERATED_SERVICES.contains(&service.as_str()) {
            continue;
        }

        let crate_dir = pkg
            .manifest_path
            .parent()
            .ok_or_else(|| {
                anyhow!("{} manifest has no parent directory", pkg.name)
            })?
            .as_std_path();

        let lib_src = pkg
            .targets
            .iter()
            .find(|t| {
                t.kind.iter().any(|k| {
                    matches!(k, cargo_metadata::TargetKind::Lib)
                        || matches!(k, cargo_metadata::TargetKind::RLib)
                        || matches!(k, cargo_metadata::TargetKind::DyLib)
                })
            })
            .map(|t| t.src_path.clone())
            .ok_or_else(|| anyhow!("{} has no lib target", pkg.name))?;

        println!("cargo:rerun-if-changed={}", pkg.manifest_path);
        println!("cargo:rerun-if-changed={lib_src}");

        let mut rs_files = Vec::new();
        collect_rs_files(crate_dir, &mut rs_files)?;
        for p in &rs_files {
            println!("cargo:rerun-if-changed={}", p.display());
        }
        rs_files_by_pkg.push((
            pkg.name.clone().to_string(),
            lib_src.into_std_path_buf(),
            rs_files,
        ));
    }

    let mut methods: Vec<ExtractedIpcMethod> = Vec::new();
    let mut dtos: Vec<ExtractedIpcDto> = Vec::new();
    for (pkg_name, lib_src, rs_files) in rs_files_by_pkg {
        let extracted = extract_ipc_methods(&rs_files)?;
        for m in extracted {
            methods.push(ExtractedIpcMethod {
                pkg_name: pkg_name.clone(),
                lib_src: lib_src.clone(),
                path: m.path,
                item_fn: m.item_fn,
            });
        }

        let extracted_dtos = extract_ipc_dtos(&rs_files)?;
        for d in extracted_dtos {
            dtos.push(ExtractedIpcDto {
                pkg_name: pkg_name.clone(),
                lib_src: lib_src.clone(),
                path: d.path,
                dto: d.dto,
            });
        }
    }

    let mut by_service: std::collections::BTreeMap<String, Vec<IpcMethodInfo>> =
        std::collections::BTreeMap::new();
    let mut dtos_by_service: std::collections::BTreeMap<
        String,
        Vec<IpcDtoInfo>,
    > = std::collections::BTreeMap::new();

    let mut skipped: Vec<String> = Vec::new();
    for m in methods {
        match ipc_method_info_from_extracted(&m) {
            Ok(Some(info)) => {
                by_service
                    .entry(info.service.clone())
                    .or_default()
                    .push(info);
            }
            Ok(None) => {
                skipped.push(format!(
					"{}: skipped (unsupported signature for IPC boilerplate generation)",
					m.path.display()
				));
            }
            Err(e) => {
                skipped.push(format!(
                    "{}: skipped (IPC boilerplate extraction failed: {e})",
                    m.path.display()
                ));
            }
        }
    }

    for d in dtos {
        match ipc_dto_info_from_extracted(&d) {
            Ok(Some(info)) => {
                dtos_by_service
                    .entry(info.service.clone())
                    .or_default()
                    .push(info);
            }
            Ok(None) => {
                skipped.push(format!(
                    "{}: skipped (unsupported #[ipc_dto] item)",
                    d.path.display()
                ));
            }
            Err(e) => {
                skipped.push(format!(
                    "{}: skipped (IPC DTO extraction failed: {e})",
                    d.path.display()
                ));
            }
        }
    }

    // Always emit a DTO fragment for every generated service, even when no DTOs
    // currently exist. This keeps `include!("<service>.dtos.generated.rs")`
    // stable and avoids surprising missing-file errors when a DTO is introduced.
    for &service in GENERATED_SERVICES {
        let service_dtos =
            dtos_by_service.get(service).cloned().unwrap_or_default();
        write_service_dtos_fragment(utilities_root, service, &service_dtos)?;
    }

    for (service, methods) in &mut by_service {
        methods.sort_by(|a, b| a.trait_method_ident.cmp(&b.trait_method_ident));
        let service_dtos =
            dtos_by_service.get(service).cloned().unwrap_or_default();
        write_service_traits_fragment(utilities_root, service, methods)?;
        write_workspace_service_client(
            workspace_root,
            service,
            methods,
            &service_dtos,
        )?;
    }

    for note in skipped {
        println!("cargo:warning=IPC codegen: {note}");
    }

    Ok(())
}

struct ExtractedIpcMethod {
    pkg_name: String,
    lib_src: PathBuf,
    path: PathBuf,
    item_fn: syn::ItemFn,
}

struct ExtractedIpcDto {
    pkg_name: String,
    lib_src: PathBuf,
    path: PathBuf,
    dto: ExtractedDto,
}

#[derive(Clone)]
enum ExtractedDto {
    Enum(ExtractedDtoEnum),
    Struct(ExtractedDtoStruct),
}

#[derive(Clone)]
struct ExtractedDtoEnum {
    ident: syn::Ident,
    variants: Vec<ExtractedDtoEnumVariant>,
    doc_lines: Vec<String>,
}

#[derive(Clone)]
struct ExtractedDtoEnumVariant {
    ident: syn::Ident,
    doc_lines: Vec<String>,
}

#[derive(Clone)]
struct ExtractedDtoStruct {
    ident: syn::Ident,
    fields: Vec<ExtractedDtoStructField>,
    doc_lines: Vec<String>,
}

#[derive(Clone)]
struct ExtractedDtoStructField {
    ident: syn::Ident,
    ty: syn::Type,
    doc_lines: Vec<String>,
}

#[derive(Clone)]
struct IpcMethodParam {
    name: syn::Ident,
    orig_ty: syn::Type,
    trait_ty: syn::Type,
    is_shm: bool,
}

#[derive(Clone)]
struct IpcMethodInfo {
    service: String,
    trait_method_ident: String,
    original_fn_ident: String,
    original_fn_module_path: String,
    original_crate_ident: String,
    ok_ty: syn::Type,
    params: Vec<IpcMethodParam>,
    doc_lines: Vec<String>,
}

fn write_service_traits_fragment(
    utilities_root: &Path,
    service: &str,
    methods: &[IpcMethodInfo],
) -> Result<()> {
    let mut out = String::new();
    push_generated(&mut out);

    let trait_ident = match service {
        "formats" => "FormatsClientTrait",
        "io" => "IoClientTrait",
        "network" => "NetworkClientTrait",
        "renderer" => "RendererClientTrait",
        "runtime" => "RuntimeClientTrait",
        "storage" => "StorageClientTrait",
        _ => bail!("Unsupported IPC service for trait generation: {service}"),
    };

    out.push_str("#[ipc_client_trait]\n");
    out.push_str("#[async_trait]\n");
    if service == "formats" {
        out.push_str("#[expect(non_snake_case, reason = \"generated trait methods matching formats naming conventions\")]\n");
    }
    let _ = writeln!(
        out,
        "pub trait {trait_ident}: crate::ipc::registry::IpcCaller + Send + Sync + std::fmt::Debug {{"
    );

    for m in methods {
        for l in &m.doc_lines {
            out.push_str("/// ");
            out.push_str(l);
            out.push('\n');
        }

        let method_ident = &m.trait_method_ident;
        let ok_ty = m.ok_ty.to_token_stream().to_string();

        let params_rendered = render_trait_params(&m.params);
        let _ = writeln!(
            out,
            "    async fn {method_ident}(&self{params_rendered}) -> Result<{ok_ty}>;"
        );
        out.push('\n');
    }

    out.push_str("}\n");

    let out_path = utilities_root
        .join("ipc")
        .join("service_traits")
        .join(format!("{service}.generated.rs"));

    write_if_changed(&out_path, &out).with_context(|| {
        format!(
            "Failed to write generated service trait fragment to {}",
            out_path.display()
        )
    })?;

    Ok(())
}

fn write_workspace_service_client(
    workspace_root: &Path,
    service: &str,
    methods: &[IpcMethodInfo],
    dtos: &[IpcDtoInfo],
) -> Result<()> {
    let mut out = String::new();
    push_generated(&mut out);

    if !dtos.is_empty() {
        out.push_str(
            "// DTO conversion helpers (service DTO -> service crate type)\n\n",
        );
        write_workspace_dto_helpers(&mut out, service, dtos)?;
        out.push('\n');
    }
    out.push_str("ipc_service_client! {\n");
    let _ = writeln!(out, "    service: {service},");
    out.push_str("    methods: {\n");

    for m in methods {
        let method_ident = &m.trait_method_ident;
        let ok_ty = m.ok_ty.to_token_stream().to_string();
        let sig_params = render_service_sig_params(service, &m.params, dtos);

        let ext_trait = render_ext_trait_path(m);
        let call_args = render_ext_call_args(service, m, dtos);

        let _ = writeln!(
            out,
            "        async fn {method_ident}(&self{sig_params}) -> Result<{ok_ty}>"
        );
        let _ = writeln!(out, "            => {ext_trait}({call_args});");
    }

    out.push_str("    }\n");
    out.push_str("}\n");

    let out_path = workspace_root
        .join("services")
        .join(format!("{service}.generated.rs"));

    write_if_changed(&out_path, &out).with_context(|| {
        format!(
            "Failed to write generated workspace service client to {}",
            out_path.display()
        )
    })?;

    Ok(())
}

fn render_trait_params(params: &[IpcMethodParam]) -> String {
    if params.is_empty() {
        return String::new();
    }

    let mut rendered = String::new();
    for p in params {
        let ty = p.trait_ty.to_token_stream().to_string();
        rendered.push_str(", ");
        if p.is_shm {
            let _ = write!(rendered, "#[ipc(shm)] {}: {ty}", p.name);
        } else {
            let _ = write!(rendered, "{}: {ty}", p.name);
        }
    }

    rendered
}

fn render_service_sig_params(
    service: &str,
    params: &[IpcMethodParam],
    dtos: &[IpcDtoInfo],
) -> String {
    if params.is_empty() {
        return String::new();
    }

    let dto_names = dto_names(dtos);

    let mut rendered = String::new();
    for p in params {
        let mut ty = p.trait_ty.to_token_stream().to_string();
        if dto_names.contains(&ty) {
            ty = format!(
                "::ctb_utilities::ipc::service_traits::{service}::{ty}"
            );
        }
        let _ = write!(rendered, ", {}: {ty}", p.name);
    }

    rendered
}

fn render_ext_trait_path(m: &IpcMethodInfo) -> String {
    let ext =
        format!("{}IpcClientExt", snake_to_pascal_case(&m.original_fn_ident));

    let mut path = format!("::{}", m.original_crate_ident);
    if !m.original_fn_module_path.is_empty() {
        path.push_str("::");
        path.push_str(&m.original_fn_module_path);
    }
    path.push_str("::");
    path.push_str(&ext);
    path
}

fn render_ext_call_args(
    service: &str,
    m: &IpcMethodInfo,
    dtos: &[IpcDtoInfo],
) -> String {
    let needs_method_name = m.trait_method_ident != m.original_fn_ident
        && service == m.service
        && service == "formats";

    let dto_names = dto_names(dtos);

    let mut args: Vec<String> = Vec::new();
    if needs_method_name {
        args.push(format!("\"{}\"", m.original_fn_ident));
    }

    for p in &m.params {
        let arg_expr = if let Some(type_name) = type_last_ident(&p.orig_ty)
            && dto_names.contains(&type_name)
        {
            let fn_name = format!(
                "to_{}_{}",
                m.original_crate_ident,
                pascal_to_snake_case(&type_name)
            );
            format!("{fn_name}(&{})", p.name)
        } else if type_last_ident(&p.orig_ty).as_deref() == Some("String")
            && type_is_ref_str(&p.trait_ty)
        {
            format!("{}.to_string()", p.name)
        } else {
            p.name.to_string()
        };
        args.push(arg_expr);
    }

    args.join(", ")
}

#[derive(Clone)]
struct IpcDtoInfo {
    service: String,
    original_crate_ident: String,
    original_type_module_path: String,
    dto: ExtractedDto,
}

fn dto_names(dtos: &[IpcDtoInfo]) -> std::collections::BTreeSet<String> {
    let mut out = std::collections::BTreeSet::new();
    for d in dtos {
        match &d.dto {
            ExtractedDto::Enum(e) => {
                let _ = out.insert(e.ident.to_string());
            }
            ExtractedDto::Struct(s) => {
                let _ = out.insert(s.ident.to_string());
            }
        }
    }
    out
}

fn pascal_to_snake_case(s: &str) -> String {
    let mut out = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() {
            if i != 0 {
                out.push('_');
            }
            for lc in ch.to_lowercase() {
                out.push(lc);
            }
        } else {
            out.push(ch);
        }
    }
    out
}

fn write_service_dtos_fragment(
    utilities_root: &Path,
    service: &str,
    dtos: &[IpcDtoInfo],
) -> Result<()> {
    let mut out = String::new();
    push_generated(&mut out);

    let mut sorted = dtos.to_vec();
    sorted.sort_by_key(dto_type_ident);

    for d in &sorted {
        match &d.dto {
            ExtractedDto::Enum(e) => {
                write_doc_lines(&mut out, &e.doc_lines);
                let _ = writeln!(
                    out,
                    "#[derive(Debug, Clone, Copy, PartialEq, Eq, ::serde::Serialize, ::serde::Deserialize)]"
                );
                let _ = writeln!(out, "pub enum {} {{", e.ident);
                for v in &e.variants {
                    write_doc_lines(&mut out, &v.doc_lines);
                    let _ = writeln!(out, "    {},", v.ident);
                }
                out.push_str("}\n\n");
            }
            ExtractedDto::Struct(s) => {
                write_doc_lines(&mut out, &s.doc_lines);
                let _ = writeln!(
                    out,
                    "#[derive(Debug, Clone, ::serde::Serialize, ::serde::Deserialize)]"
                );
                let _ = writeln!(out, "pub struct {} {{", s.ident);
                for f in &s.fields {
                    write_doc_lines(&mut out, &f.doc_lines);
                    let ty = f.ty.to_token_stream().to_string();
                    let _ = writeln!(out, "    pub {}: {ty},", f.ident);
                }
                out.push_str("}\n\n");
            }
        }
    }

    let out_path = utilities_root
        .join("ipc")
        .join("service_traits")
        .join(format!("{service}.dtos.generated.rs"));

    write_if_changed(&out_path, &out).with_context(|| {
        format!(
            "Failed to write generated DTO fragment to {}",
            out_path.display()
        )
    })?;

    Ok(())
}

fn dto_type_ident(d: &IpcDtoInfo) -> String {
    match &d.dto {
        ExtractedDto::Enum(e) => e.ident.to_string(),
        ExtractedDto::Struct(s) => s.ident.to_string(),
    }
}

fn write_doc_lines(out: &mut String, lines: &[String]) {
    for l in lines {
        out.push_str("/// ");
        out.push_str(l);
        out.push('\n');
    }
}

fn write_workspace_dto_helpers(
    out: &mut String,
    service: &str,
    dtos: &[IpcDtoInfo],
) -> Result<()> {
    let dto_names = dto_names(dtos);
    let mut sorted = dtos.to_vec();
    sorted.sort_by_key(dto_type_ident);

    for d in &sorted {
        match &d.dto {
            ExtractedDto::Enum(e) => {
                let trait_ty = format!(
                    "::ctb_utilities::ipc::service_traits::{service}::{}",
                    e.ident
                );
                let orig_ty = original_type_path(d, &e.ident);
                let fn_name = format!(
                    "to_{}_{}",
                    d.original_crate_ident,
                    pascal_to_snake_case(&e.ident.to_string())
                );
                let _ = writeln!(
                    out,
                    "fn {fn_name}(v: &{trait_ty}) -> {orig_ty} {{"
                );
                let _ = writeln!(out, "    match v {{");
                for v in &e.variants {
                    let _ = writeln!(
                        out,
                        "        {trait_ty}::{} => {orig_ty}::{},",
                        v.ident, v.ident
                    );
                }
                out.push_str("    }\n}");
                out.push_str("\n\n");
            }
            ExtractedDto::Struct(s) => {
                let trait_ty = format!(
                    "::ctb_utilities::ipc::service_traits::{service}::{}",
                    s.ident
                );
                let orig_ty = original_type_path(d, &s.ident);
                let fn_name = format!(
                    "to_{}_{}",
                    d.original_crate_ident,
                    pascal_to_snake_case(&s.ident.to_string())
                );
                let _ = writeln!(
                    out,
                    "fn {fn_name}(v: &{trait_ty}) -> {orig_ty} {{"
                );
                let _ = writeln!(out, "    {orig_ty} {{");
                for f in &s.fields {
                    let field_ty_name = type_last_ident(&f.ty);
                    let field_expr = if field_ty_name
                        .as_ref()
                        .is_some_and(|n| dto_names.contains(n))
                    {
                        let Some(type_name) = field_ty_name else {
                            bail!(
                                "Unsupported #[ipc_dto] field type for {}::{}",
                                s.ident,
                                f.ident
                            );
                        };
                        let field_fn = format!(
                            "to_{}_{}",
                            d.original_crate_ident,
                            pascal_to_snake_case(&type_name)
                        );
                        format!("{field_fn}(&v.{})", f.ident)
                    } else {
                        format!("v.{}.clone()", f.ident)
                    };
                    let _ = writeln!(out, "        {}: {field_expr},", f.ident);
                }
                out.push_str("    }\n}");
                out.push_str("\n\n");
            }
        }
    }

    Ok(())
}

#[expect(
    clippy::needless_pass_by_value,
    reason = "original_type_path is cleaner with these parameters"
)]
fn original_type_path(d: &IpcDtoInfo, type_ident: &syn::Ident) -> String {
    let mut path = format!("::{}", d.original_crate_ident);
    if !d.original_type_module_path.is_empty() {
        path.push_str("::");
        path.push_str(&d.original_type_module_path);
    }
    path.push_str("::");
    path.push_str(&type_ident.to_string());
    path
}

fn ipc_method_info_from_extracted(
    m: &ExtractedIpcMethod,
) -> Result<Option<IpcMethodInfo>> {
    let (service, subservice) = service_and_subservice_from_pkg(&m.pkg_name);
    if !GENERATED_SERVICES.contains(&service.as_str()) {
        return Ok(None);
    }

    let fn_ident = m.item_fn.sig.ident.to_string();
    let method_key = method_key_from_parts(&subservice, &fn_ident);
    let trait_method_ident = method_key.replace('.', "__");

    let module_path = module_path_for_source_file(&m.lib_src, &m.path)?;
    let crate_ident = crate_ident_from_pkg(&m.pkg_name);

    let ok_ty = ok_type_from_sig_output(&m.item_fn.sig.output);

    let mut params = Vec::new();
    for arg in &m.item_fn.sig.inputs {
        let syn::FnArg::Typed(pat_ty) = arg else {
            return Ok(None);
        };
        let syn::Pat::Ident(pat_ident) = pat_ty.pat.as_ref() else {
            return Ok(None);
        };
        let name = pat_ident.ident.clone();
        let orig_ty = (*pat_ty.ty).clone();
        let is_shm = has_ipc_shm_attr(&pat_ty.attrs);
        let trait_ty = trait_param_type_from_orig(&orig_ty);
        params.push(IpcMethodParam {
            name,
            orig_ty,
            trait_ty,
            is_shm,
        });
    }

    let doc_lines = doc_lines_from_attrs(&m.item_fn.attrs);

    Ok(Some(IpcMethodInfo {
        service,
        trait_method_ident,
        original_fn_ident: fn_ident,
        original_fn_module_path: module_path,
        original_crate_ident: crate_ident,
        ok_ty,
        params,
        doc_lines,
    }))
}

fn ipc_dto_info_from_extracted(
    d: &ExtractedIpcDto,
) -> Result<Option<IpcDtoInfo>> {
    let (service, _subservice) = service_and_subservice_from_pkg(&d.pkg_name);
    if !GENERATED_SERVICES.contains(&service.as_str()) {
        return Ok(None);
    }

    let module_path = module_path_for_source_file(&d.lib_src, &d.path)?;
    let crate_ident = crate_ident_from_pkg(&d.pkg_name);

    Ok(Some(IpcDtoInfo {
        service,
        original_crate_ident: crate_ident,
        original_type_module_path: module_path,
        dto: d.dto.clone(),
    }))
}

fn service_and_subservice_from_pkg(pkg_name: &str) -> (String, String) {
    let pkg = pkg_name.strip_prefix("ctb-").unwrap_or(pkg_name);
    let service = pkg.split('-').next().unwrap_or(pkg);
    let service = if service.is_empty() { "ipc" } else { service };

    let subservice = pkg
        .strip_prefix(&format!("{service}-"))
        .unwrap_or("")
        .replace('-', "_");

    (service.to_string(), subservice)
}

fn crate_ident_from_pkg(pkg_name: &str) -> String {
    pkg_name.replace('-', "_")
}

fn method_key_from_parts(subservice: &str, fn_ident: &str) -> String {
    let fn_key = if fn_ident.contains("__") {
        fn_ident.replace("__", ".")
    } else {
        fn_ident.to_string()
    };

    if subservice.is_empty() {
        return fn_key;
    }

    let dot_prefix = format!("{subservice}.");
    if fn_key.starts_with(dot_prefix.as_str()) {
        fn_key
    } else {
        format!("{subservice}.{fn_key}")
    }
}

fn module_path_for_source_file(lib_src: &Path, file: &Path) -> Result<String> {
    if file == lib_src {
        return Ok(String::new());
    }

    let crate_dir = lib_src
        .parent()
        .ok_or_else(|| anyhow!("lib src has no parent directory"))?;
    let rel = file.strip_prefix(crate_dir).with_context(|| {
        format!(
            "{} is not under crate dir {}",
            file.display(),
            crate_dir.display()
        )
    })?;
    let rel = rel.to_string_lossy();

    let without_ext = rel.strip_suffix(".rs").unwrap_or(rel.as_ref());
    let without_mod = without_ext.strip_suffix("/mod").unwrap_or(without_ext);
    let mut parts: Vec<&str> =
        without_mod.split('/').filter(|p| !p.is_empty()).collect();

    // Some crates in this workspace follow the convention of having a module
    // directory and a same-named file, e.g. `utf_8e_128/utf_8e_128.rs`.
    // In Rust module paths, that should be just `utf_8e_128`, not
    // `utf_8e_128::utf_8e_128`.
    if parts.len() >= 2 {
        let Some(last) = parts.last() else {
            return Ok(String::new());
        };
        let Some(prev) = parts.get(parts.len().saturating_sub(2)) else {
            return Ok(parts.join("::"));
        };
        if last == prev {
            parts.pop();
        }
    }

    Ok(parts.join("::"))
}

fn snake_to_pascal_case(s: &str) -> String {
    let mut out = String::new();
    let mut upper_next = true;
    for ch in s.chars() {
        if ch == '_' {
            upper_next = true;
            continue;
        }
        if upper_next {
            out.extend(ch.to_uppercase());
            upper_next = false;
        } else {
            out.push(ch);
        }
    }
    out
}

fn has_ipc_shm_attr(attrs: &[syn::Attribute]) -> bool {
    for a in attrs {
        if !a.path().is_ident("ipc") {
            continue;
        }

        let syn::Meta::List(list) = &a.meta else {
            continue;
        };

        let mut found = false;
        let _ = list.parse_nested_meta(|meta| {
            if meta.path.is_ident("shm") {
                found = true;
            }
            Ok(())
        });
        if found {
            return true;
        }
    }
    false
}

fn trait_param_type_from_orig(orig: &syn::Type) -> syn::Type {
    if type_last_ident(orig).as_deref() == Some("String") {
        return syn::parse_quote! { &str };
    }

    orig.clone()
}

fn ok_type_from_sig_output(output: &syn::ReturnType) -> syn::Type {
    match output {
        syn::ReturnType::Default => syn::parse_quote! { () },
        syn::ReturnType::Type(_, ty) => {
            if let Some(ok) = parse_result_ok_type(ty.as_ref()) {
                ok
            } else {
                (**ty).clone()
            }
        }
    }
}

fn parse_result_ok_type(ty: &syn::Type) -> Option<syn::Type> {
    let syn::Type::Path(p) = ty else {
        return None;
    };
    let seg = p.path.segments.last()?;
    if seg.ident != "Result" {
        return None;
    }
    let syn::PathArguments::AngleBracketed(args) = &seg.arguments else {
        return None;
    };
    let first = args.args.first()?;
    let syn::GenericArgument::Type(ok) = first else {
        return None;
    };
    Some(ok.clone())
}

fn doc_lines_from_attrs(attrs: &[syn::Attribute]) -> Vec<String> {
    let mut out = Vec::new();
    for a in attrs {
        if !a.path().is_ident("doc") {
            continue;
        }
        let syn::Meta::NameValue(nv) = &a.meta else {
            continue;
        };
        let syn::Expr::Lit(expr_lit) = &nv.value else {
            continue;
        };
        let syn::Lit::Str(s) = &expr_lit.lit else {
            continue;
        };
        let line = s.value();
        out.push(line.trim_end().to_string());
    }
    out
}

fn type_last_ident(ty: &syn::Type) -> Option<String> {
    match ty {
        syn::Type::Path(p) => {
            p.path.segments.last().map(|s| s.ident.to_string())
        }
        syn::Type::Reference(r) => type_last_ident(r.elem.as_ref()),
        _ => None,
    }
}

fn type_is_ref_str(ty: &syn::Type) -> bool {
    let syn::Type::Reference(r) = ty else {
        return false;
    };
    matches!(r.elem.as_ref(), syn::Type::Path(p) if p.path.segments.last().is_some_and(|s| s.ident == "str"))
}

struct ExtractedMethod {
    path: PathBuf,
    item_fn: syn::ItemFn,
    /// Optional human-readable skip reason if we decide not to emit.
    reason: Option<String>,
}

struct RenderedWorkspaceSignature {
    method_name: String,
    rendered: String,
}

fn collect_rs_files(dir: &Path, out: &mut Vec<PathBuf>) -> Result<()> {
    for entry in fs::read_dir(dir)
        .with_context(|| format!("Failed to read dir {}", dir.display()))?
    {
        let entry = entry?;
        let path = entry.path();
        let file_type = entry.file_type()?;

        if file_type.is_dir() {
            collect_rs_files(&path, out)?;
            continue;
        }

        if file_type.is_file()
            && path.extension() == Some(OsStr::new("rs"))
            && path.file_name() != Some(OsStr::new("build.rs"))
        {
            out.push(path);
        }
    }

    Ok(())
}

fn extract_ipc_methods(rs_files: &[PathBuf]) -> Result<Vec<ExtractedMethod>> {
    let mut out = Vec::new();

    for path in rs_files {
        let src = fs::read_to_string(path)
            .with_context(|| format!("Failed to read {}", path.display()))?;

        let file = syn::parse_file(&src)
            .with_context(|| format!("Failed to parse {}", path.display()))?;

        extract_ipc_methods_from_items(&file.items, path, &mut out);
    }

    Ok(out)
}

struct ExtractedDtoFileItem {
    path: PathBuf,
    dto: ExtractedDto,
}

fn extract_ipc_dtos(rs_files: &[PathBuf]) -> Result<Vec<ExtractedDtoFileItem>> {
    let mut out = Vec::new();

    for path in rs_files {
        let src = fs::read_to_string(path)
            .with_context(|| format!("Failed to read {}", path.display()))?;

        let file = syn::parse_file(&src)
            .with_context(|| format!("Failed to parse {}", path.display()))?;

        extract_ipc_dtos_from_items(&file.items, path, &mut out)?;
    }

    Ok(out)
}

fn extract_ipc_dtos_from_items(
    items: &[syn::Item],
    path: &Path,
    out: &mut Vec<ExtractedDtoFileItem>,
) -> Result<()> {
    for item in items {
        match item {
            syn::Item::Enum(e) => {
                if !has_ipc_dto_attr(&e.attrs) {
                    continue;
                }
                let mut variants = Vec::new();
                for v in &e.variants {
                    match &v.fields {
                        syn::Fields::Unit => {}
                        _ => {
                            bail!(
                                "#[ipc_dto] currently only supports unit enum variants ({}::{})",
                                e.ident,
                                v.ident
                            );
                        }
                    }
                    variants.push(ExtractedDtoEnumVariant {
                        ident: v.ident.clone(),
                        doc_lines: doc_lines_from_attrs(&v.attrs),
                    });
                }
                out.push(ExtractedDtoFileItem {
                    path: path.to_path_buf(),
                    dto: ExtractedDto::Enum(ExtractedDtoEnum {
                        ident: e.ident.clone(),
                        variants,
                        doc_lines: doc_lines_from_attrs(&e.attrs),
                    }),
                });
            }
            syn::Item::Struct(s) => {
                if !has_ipc_dto_attr(&s.attrs) {
                    continue;
                }
                let syn::Fields::Named(named) = &s.fields else {
                    bail!(
                        "#[ipc_dto] currently only supports named-field structs ({})",
                        s.ident
                    );
                };
                let mut fields = Vec::new();
                for f in &named.named {
                    let Some(ident) = f.ident.clone() else {
                        bail!("#[ipc_dto] requires named fields ({})", s.ident);
                    };
                    fields.push(ExtractedDtoStructField {
                        ident,
                        ty: f.ty.clone(),
                        doc_lines: doc_lines_from_attrs(&f.attrs),
                    });
                }
                out.push(ExtractedDtoFileItem {
                    path: path.to_path_buf(),
                    dto: ExtractedDto::Struct(ExtractedDtoStruct {
                        ident: s.ident.clone(),
                        fields,
                        doc_lines: doc_lines_from_attrs(&s.attrs),
                    }),
                });
            }
            syn::Item::Mod(m) => {
                if let Some((_, inner)) = &m.content {
                    extract_ipc_dtos_from_items(inner, path, out)?;
                }
            }
            _ => {}
        }
    }

    Ok(())
}

fn extract_ipc_methods_from_items(
    items: &[syn::Item],
    path: &Path,
    out: &mut Vec<ExtractedMethod>,
) {
    for item in items {
        match item {
            syn::Item::Fn(item_fn) => {
                if has_ipc_method_attr(&item_fn.attrs) {
                    out.push(ExtractedMethod {
                        path: path.to_path_buf(),
                        item_fn: item_fn.clone(),
                        reason: None,
                    });
                }
            }
            syn::Item::Mod(m) => {
                if let Some((_, inner)) = &m.content {
                    extract_ipc_methods_from_items(inner, path, out);
                }
            }
            _ => {}
        }
    }
}

fn has_ipc_method_attr(attrs: &[syn::Attribute]) -> bool {
    attrs.iter().any(|a| {
        a.path()
            .segments
            .last()
            .is_some_and(|s| s.ident == "ipc_method")
    })
}

fn has_ipc_dto_attr(attrs: &[syn::Attribute]) -> bool {
    attrs.iter().any(|a| {
        a.path()
            .segments
            .last()
            .is_some_and(|s| s.ident == "ipc_dto")
    })
}

#[expect(
    clippy::unnecessary_wraps,
    reason = "returns Result for consistency with other signature parsers"
)]
fn workspace_ipc_signature_from_item(
    item_fn: &syn::ItemFn,
) -> Result<Option<RenderedWorkspaceSignature>> {
    // Reject generics/where clauses: workspace_ipc_methods! doesn't support.
    if !item_fn.sig.generics.params.is_empty()
        || item_fn.sig.generics.where_clause.is_some()
    {
        return Ok(None);
    }

    let method_ident = &item_fn.sig.ident;
    let method_name = method_ident.to_string();

    // Reject #[ipc(...)] params: these are data-plane/shm.
    for input in &item_fn.sig.inputs {
        let syn::FnArg::Typed(pat_type) = input else {
            continue;
        };

        for attr in &pat_type.attrs {
            if attr.path().is_ident("ipc") {
                return Ok(None);
            }
        }

        // Require identifier patterns so the helper can reference args.
        let syn::Pat::Ident(_) = pat_type.pat.as_ref() else {
            return Ok(None);
        };

        // Borrowed inputs: allow only &str and &[u8].
        if is_reference_type(pat_type.ty.as_ref())
            && !(is_ref_to_str(pat_type.ty.as_ref())
                || is_ref_to_slice_u8(pat_type.ty.as_ref()))
        {
            return Ok(None);
        }
    }

    // Render a stable signature line.
    let inputs = &item_fn.sig.inputs;
    let output = item_fn.sig.output.to_token_stream().to_string();

    let rendered = format!(
        "async fn {method_ident}({}) {output};",
        render_inputs(inputs)
    );

    Ok(Some(RenderedWorkspaceSignature {
        method_name,
        rendered,
    }))
}

fn render_inputs(
    inputs: &syn::punctuated::Punctuated<syn::FnArg, syn::Token![,]>,
) -> String {
    let mut parts = Vec::new();
    for arg in inputs {
        let syn::FnArg::Typed(pat_type) = arg else {
            continue;
        };
        let name = match pat_type.pat.as_ref() {
            syn::Pat::Ident(pat_ident) => pat_ident.ident.to_string(),
            _ => "_".to_string(),
        };
        parts.push(format!("{name}: {}", pat_type.ty.to_token_stream()));
    }

    parts.join(", ")
}

fn is_reference_type(ty: &syn::Type) -> bool {
    matches!(ty, syn::Type::Reference(_))
}

fn is_ref_to_str(ty: &syn::Type) -> bool {
    let syn::Type::Reference(r) = ty else {
        return false;
    };
    let syn::Type::Path(p) = r.elem.as_ref() else {
        return false;
    };

    p.path.segments.last().is_some_and(|s| s.ident == "str")
}

fn is_ref_to_slice_u8(ty: &syn::Type) -> bool {
    let syn::Type::Reference(r) = ty else {
        return false;
    };
    let syn::Type::Slice(slice) = r.elem.as_ref() else {
        return false;
    };
    let syn::Type::Path(p) = slice.elem.as_ref() else {
        return false;
    };

    p.path.segments.last().is_some_and(|s| s.ident == "u8")
}
