// SPDX-License-Identifier: AGPL-3.0-only AND GPL-3.0-only AND LGPL-3.0-only
// SPDX-License-Identifier for parts derived from SeaBIOS: GPL-3.0-only AND LGPL-3.0-only
/*
This file is part of Collective Toolbox, a database and document workspace and utilities.
Copyright (C) 2026 Collective Toolbox Developers
Contact: info@collectivetoolbox.com

This program is free software: you can redistribute it and/or modify it under
the terms of version 3 of the GNU Affero General Public License as published by
the Free Software Foundation.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along
with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// From Makefile:
// Copyright (C) 2008-2012  Kevin O'Connor <kevin@koconnor.net>
//
// This file may be distributed under the terms of the GNU LGPLv3 license.

// From buildversion.py:
// Copyright (C) 2015  Kevin O'Connor <kevin@koconnor.net>
//
// This file may be distributed under the terms of the GNU GPLv3 license.

// From vgafixup.py:
// Copyright (C) 2012  Kevin O'Connor <kevin@koconnor.net>
//
// This file may be distributed under the terms of the GNU GPLv3 license.

// From layoutrom.py:
// Copyright (C) 2008-2014  Kevin O'Connor <kevin@koconnor.net>
//
// This file may be distributed under the terms of the GNU GPLv3 license.

// From checkrom.py:
// Copyright (C) 2008  Kevin O'Connor <kevin@koconnor.net>
//
// This file may be distributed under the terms of the GNU GPLv3 license.

// From buildrom.py:
// Copyright (C) 2009  Kevin O'Connor <kevin@koconnor.net>
//
// This file may be distributed under the terms of the GNU GPLv3 license.

// From ldnoexec.py:
// Copyright (C) 2020  Kevin O'Connor <kevin@koconnor.net>
//
// This file may be distributed under the terms of the GNU GPLv3 license.

//! Native Rust implementation of SeaBIOS build tools.
//!
//! Replaces python scripts:
//! - buildversion.py
//! - vgafixup.py
//! - buildrom.py
//! - checkrom.py
//! - layoutrom.py
//! - ldnoexec.py

use anyhow::{Context, Result, bail};
use std::collections::{BTreeMap, HashMap, HashSet};
use std::fmt::Write;
use std::fs;
use std::path::Path;

pub const BUILD_BIOS_ADDR: usize = 0xf0000;
pub const BUILD_BIOS_SIZE: usize = 0x10000;
pub const BUILD_ROM_START: usize = 0xc0000;
pub const BUILD_LOWRAM_END: usize = 0xa0000;
pub fn run_ldnoexec(infile: &Path, outfile: &Path) -> Result<()> {
    let mut data = fs::read(infile)
        .with_context(|| format!("Failed to read {}", infile.display()))?;
    if let Some(elem) = data.get_mut(16) {
        *elem = 0x01;
    }
    if let Some(parent) = outfile.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(outfile, data)
        .with_context(|| format!("Failed to write {}", outfile.display()))?;
    Ok(())
}

fn alignpos(pos: usize, alignbytes: usize) -> usize {
    if alignbytes == 0 {
        return pos;
    }
    let mask = alignbytes.saturating_sub(1);
    (pos.saturating_add(mask)) & !mask
}

fn _aligndown(pos: usize, alignbytes: usize) -> usize {
    if alignbytes == 0 {
        return pos;
    }
    let mask = alignbytes.saturating_sub(1);
    pos & !mask
}

pub fn run_buildversion(args: &[String]) -> Result<()> {
    let mut outfile = String::new();
    let mut extraversion = String::new();
    let mut tools = String::new();

    let mut i = 0;
    while i < args.len() {
        match args.get(i).map(String::as_str) {
            Some("-e") => {
                if i.saturating_add(1) < args.len() {
                    if let Some(val) = args.get(i.saturating_add(1)) {
                        extraversion = val.clone();
                    }
                    i = i.saturating_add(1);
                }
            }
            Some("-t") => {
                if i.saturating_add(1) < args.len() {
                    if let Some(val) = args.get(i.saturating_add(1)) {
                        tools = val.clone();
                    }
                    i = i.saturating_add(1);
                }
            }
            Some(arg) if !arg.starts_with('-') => {
                outfile = arg.to_string();
            }
            _ => {}
        }
        i = i.saturating_add(1);
    }

    if outfile.is_empty() {
        bail!("buildversion: missing output header file argument");
    }

    let version = format!("rel-1.16.2{extraversion}");
    let tools_str = if tools.is_empty() {
        "gcc binutils".to_string()
    } else {
        tools
    };

    let content = format!(
        "/* DO NOT EDIT! This is an autogenerated file. See seabios-tool. */\n\
         #define BUILD_VERSION \"{version}\"\n\
         #define BUILD_TOOLS \"{tools_str}\"\n"
    );

    if let Some(parent) = Path::new(&outfile).parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&outfile, content)?;
    println!("Version: {version}");
    Ok(())
}

pub fn run_vgafixup(infilename: &Path, outfilename: &Path) -> Result<()> {
    let content = fs::read_to_string(infilename)
        .with_context(|| format!("Failed to read {}", infilename.display()))?;

    let mut out = Vec::new();
    for line in content.lines() {
        let sline = line.trim();
        if sline == "ret" {
            out.push("retw $2".to_string());
        } else if sline == "leave" {
            out.push("movl %ebp, %esp ; popl %ebp".to_string());
        } else if sline.starts_with("call") {
            let rest = sline.get(4..).unwrap_or("");
            out.push(format!("pushw %ax ; callw{rest}"));
        } else if sline.starts_with("leal") {
            out.push(handle_leal(sline));
        } else {
            out.push(line.to_string());
        }
    }

    if let Some(parent) = outfilename.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(outfilename, format!("{}\n", out.join("\n")))?;
    Ok(())
}

fn handle_leal(sline: &str) -> String {
    let rest = sline.get(4..).unwrap_or("").trim();
    if rest.contains("(%esp)") {
        return format!("leaw {}", rest.replace("%e", "%"));
    }
    format!("movl %ebp, %esp ; {sline}")
}

pub fn run_buildrom(inname: &Path, outname: &Path) -> Result<()> {
    let mut data = fs::read(inname)
        .with_context(|| format!("Failed to read {}", inname.display()))?;

    let count = data.len();
    let target_len = alignpos(count, 512);
    data.resize(target_len, 0);
    let count = data.len();

    if data.len() >= 26 {
        let pci1 = usize::from(data.get(24).copied().unwrap_or(0));
        let pci2 = usize::from(data.get(25).copied().unwrap_or(0));
        #[expect(
            clippy::expect_used,
            reason = "Shift of 8 bits fits within usize width (32/64 bit)"
        )]
        let pcidata =
            pci1 | (pci2.checked_shl(8).expect("8-bit shift fits in usize"));
        if pcidata != 0 && data.len() >= pcidata.saturating_add(18) {
            #[expect(
                clippy::expect_used,
                reason = "Division by constant 512 is non-zero and cannot fail"
            )]
            let count_blocks = count.checked_div(512).expect("512 is non-zero");
            let blocks = u16::try_from(count_blocks).unwrap_or(0).to_le_bytes();
            if let Some(slot) = data.get_mut(pcidata.saturating_add(16)) {
                *slot = blocks.first().copied().unwrap_or(0);
            }
            if let Some(slot) = data.get_mut(pcidata.saturating_add(17)) {
                *slot = blocks.get(1).copied().unwrap_or(0);
            }
        }
    }

    if data.len() >= 7 {
        if let Some(slot) = data.get_mut(2) {
            #[expect(
                clippy::expect_used,
                reason = "Division by constant 512 is non-zero and cannot fail"
            )]
            let count_blocks = count.checked_div(512).expect("512 is non-zero");
            *slot = u8::try_from(count_blocks).unwrap_or(0);
        }
        if let Some(slot) = data.get_mut(6) {
            *slot = 0;
        }

        let cksum: usize = data.iter().map(|&b| usize::from(b)).sum();
        let ckbyte = u8::try_from(
            (0x100_usize.saturating_sub(cksum.rem_euclid(256))).rem_euclid(256),
        )
        .unwrap_or(0);
        if let Some(slot) = data.get_mut(6) {
            *slot = ckbyte;
        }
    }

    if let Some(parent) = outname.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(outname, data)?;
    Ok(())
}

pub fn run_checkrom(
    _objinfo: &Path,
    finalsize_kb: usize,
    rawfile: &Path,
    outfile: &Path,
) -> Result<()> {
    let rawdata = fs::read(rawfile)
        .with_context(|| format!("Failed to read {}", rawfile.display()))?;

    let datasize = rawdata.len();
    let mut finalsize = finalsize_kb.saturating_mul(1024);
    if finalsize == 0 {
        finalsize = 64_usize.saturating_mul(1024);
        if datasize > 64_usize.saturating_mul(1024) {
            finalsize = 128_usize.saturating_mul(1024);
            if datasize > 128_usize.saturating_mul(1024) {
                finalsize = 256_usize.saturating_mul(1024);
            }
        }
    }

    if datasize > finalsize {
        bail!("ROM size error: {datasize} > {finalsize}");
    }

    let mut out = vec![0_u8; finalsize.saturating_sub(datasize)];
    out.extend_from_slice(&rawdata);

    let free = finalsize.saturating_sub(datasize);
    let datasize_u32 = u32::try_from(datasize).unwrap_or(u32::MAX);
    let finalsize_u32 = u32::try_from(finalsize).unwrap_or(u32::MAX);
    let datasize_f = f64::from(datasize_u32);
    let finalsize_f = f64::from(finalsize_u32);
    let pct = if finalsize_f > 0.0 {
        (datasize_f / finalsize_f) * 100.0
    } else {
        0.0
    };
    let kb = finalsize.checked_div(1024).unwrap_or(0);
    println!(
        "Total size: {datasize}  Fixed: {datasize}  Free: {free} (used {pct:.1}% of {kb}KiB rom)"
    );

    if let Some(parent) = outfile.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(outfile, out)?;
    Ok(())
}

const COMMONHEADER: &str = r#"/* DO NOT EDIT!  This is an autogenerated file.  See seabios-tool. */
OUTPUT_FORMAT("elf32-i386")
OUTPUT_ARCH("i386")
SECTIONS
{
"#;

const COMMONTRAILER: &str = r"
        /* Discard regular data sections to force a link error if
         * code attempts to access data not marked with VAR16 (or other
         * appropriate macro)
         */
        /DISCARD/ : {
                *(.text*) *(.data*) *(.bss*) *(.rodata*)
                *(COMMON) *(.discard*) *(.eh_frame) *(.note*)
                }
}
";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Symbol {
    pub name: String,
    pub offset: usize,
    pub size: usize,
    pub section_name: Option<String>,
    pub fileid: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Reloc {
    pub offset: usize,
    pub reloc_type: String,
    pub symbolname: String,
}

#[derive(Debug, Clone)]
pub struct Section {
    pub name: String,
    pub size: usize,
    pub align: usize,
    pub fileid: String,
    pub category: String,
    pub finalloc: Option<usize>,
    pub finalsegloc: usize,
    pub relocs: Vec<Reloc>,
}

#[derive(Default)]
pub struct LayoutInfo {
    pub sections: Vec<Section>,
    pub config: HashMap<String, usize>,
    pub genreloc: bool,
    pub sec32init_start: usize,
    pub sec32init_end: usize,
    pub sec32init_align: usize,
    pub sec32low_start: usize,
    pub sec32low_end: usize,
    pub zonelow_base: usize,
    pub final_sec32low_start: usize,
    pub zonefseg_start: usize,
    pub zonefseg_end: usize,
    pub final_readonly_start: usize,
    pub varlowsyms: Vec<Symbol>,
    pub entrysym: Option<Symbol>,
}

pub fn run_layoutrom(
    in16: &Path,
    in32seg: &Path,
    in32flat: &Path,
    cfgfile: &Path,
    out16: &Path,
    out32seg: &Path,
    out32flat: &Path,
) -> Result<()> {
    let (info16_secs, info16_syms) = parse_objdump(in16, "16")?;
    let (info32seg_secs, info32seg_syms) = parse_objdump(in32seg, "32seg")?;
    let (info32flat_secs, info32flat_syms) = parse_objdump(in32flat, "32flat")?;

    let config = scan_config(cfgfile);

    let mut symbols_by_fileid: HashMap<String, HashMap<String, Symbol>> =
        HashMap::new();
    symbols_by_fileid.insert("16".to_string(), info16_syms.clone());
    symbols_by_fileid.insert("32seg".to_string(), info32seg_syms.clone());
    symbols_by_fileid.insert("32flat".to_string(), info32flat_syms.clone());

    let entrysym = if config.get("CONFIG_COREBOOT").copied().unwrap_or(0) != 0 {
        info16_syms.get("entry_elf").cloned()
    } else if config.get("CONFIG_CSM").copied().unwrap_or(0) != 0 {
        info16_syms.get("entry_csm").cloned()
    } else {
        info16_syms.get("reset_vector").cloned()
    };

    let all_sections: Vec<Section> = info16_secs
        .into_iter()
        .chain(info32seg_secs)
        .chain(info32flat_secs)
        .collect();

    let mut anchor_secs = Vec::new();
    if let Some(ref esym) = entrysym {
        if let Some(ref sec_name) = esym.section_name {
            anchor_secs.push(("16".to_string(), sec_name.clone()));
        }
    }
    for sec in &all_sections {
        if sec.name.starts_with(".fixedaddr.") {
            anchor_secs.push((sec.fileid.clone(), sec.name.clone()));
        }
    }

    let keep_sections =
        find_reachable(&anchor_secs, &all_sections, &symbols_by_fileid);
    let mut sections: Vec<Section> = all_sections
        .into_iter()
        .filter(|sec| {
            keep_sections.contains(&(sec.fileid.clone(), sec.name.clone()))
        })
        .collect();

    let mut runtime_anchors = Vec::new();
    for sec in &sections {
        if sec.name.contains(".data.varlow.")
            || sec.name.contains(".data.varfseg.")
            || sec.name.starts_with(".fixedaddr.")
            || sec.name.contains(".runtime.")
        {
            runtime_anchors.push((sec.fileid.clone(), sec.name.clone()));
        }
    }

    let runtime_sections =
        find_runtime_reachable(&runtime_anchors, &sections, &symbols_by_fileid);

    for sec in &mut sections {
        if sec.name.starts_with(".data.varlow.") {
            sec.category = "32low".to_string();
        } else if sec.name.starts_with(".data.varfseg.") {
            sec.category = "32fseg".to_string();
        } else if sec.name.starts_with(".text.32fseg.") {
            sec.category = "32textfseg".to_string();
        } else if sec.name.starts_with(".fixedaddr.") {
            sec.category = "fixed".to_string();
        } else if sec.fileid == "32flat"
            && !runtime_sections
                .contains(&(sec.fileid.clone(), sec.name.clone()))
        {
            sec.category = "32init".to_string();
        } else {
            sec.category = sec.fileid.clone();
        }
    }

    let genreloc = symbols_by_fileid
        .get("32flat")
        .and_then(|syms| syms.get("_reloc_abs_start"))
        .is_some();

    let mut li = do_layout(sections, &config, genreloc);

    let mut varlowsyms = Vec::new();
    if let Some(flat_syms) = symbols_by_fileid.get("32flat") {
        for sym in flat_syms.values() {
            if let Some(ref sec_name) = sym.section_name {
                if sec_name.contains(".data.varlow.") && sym.name != *sec_name {
                    varlowsyms.push(sym.clone());
                }
            }
        }
    }
    li.varlowsyms = varlowsyms;
    li.entrysym = entrysym;

    write_linker_scripts(&li, &symbols_by_fileid, out16, out32seg, out32flat)?;

    Ok(())
}

fn strip_reloc_offset(name: &str) -> &str {
    let name = name.split('+').next().unwrap_or(name);
    if let Some(pos) = name.rfind('-') {
        let suffix = name.get(pos.saturating_add(1)..).unwrap_or("");
        if suffix.starts_with("0x")
            || suffix.starts_with("0X")
            || (!suffix.is_empty()
                && suffix.chars().all(|c| c.is_ascii_hexdigit()))
        {
            return name.get(..pos).unwrap_or(name);
        }
    }
    name
}

fn parse_objdump(
    path: &Path,
    fileid: &str,
) -> Result<(Vec<Section>, HashMap<String, Symbol>)> {
    let content = fs::read_to_string(path)
        .with_context(|| format!("Failed to read {}", path.display()))?;

    let mut sections = Vec::new();
    let mut section_map: HashMap<String, usize> = HashMap::new();
    let mut symbols: HashMap<String, Symbol> = HashMap::new();

    let mut state = None;
    let mut current_reloc_section_idx: Option<usize> = None;

    for raw_line in content.lines() {
        let line = raw_line.trim_end();
        if line == "Sections:" {
            state = Some("section");
            continue;
        }
        if line == "SYMBOL TABLE:" {
            state = Some("symbol");
            continue;
        }
        if line.starts_with("RELOCATION RECORDS FOR [") {
            let sec_name = line
                .trim_start_matches("RELOCATION RECORDS FOR [")
                .trim_end_matches(':')
                .trim_end_matches(']');
            if sec_name.starts_with(".debug_") {
                state = None;
                continue;
            }
            state = Some("reloc");
            current_reloc_section_idx = section_map.get(sec_name).copied();
            continue;
        }

        match state {
            Some("section") => {
                let parts: Vec<&str> = line.split_whitespace().collect();
                if parts.len() >= 7 {
                    if let Some(align_part) = parts.get(6) {
                        if align_part.starts_with("2**") {
                            let name =
                                parts.get(1).copied().unwrap_or("").to_string();
                            let size = usize::from_str_radix(
                                parts.get(2).copied().unwrap_or("0"),
                                16,
                            )
                            .unwrap_or(0);
                            let pow: u32 = align_part
                                .get(3..)
                                .unwrap_or("")
                                .parse()
                                .unwrap_or(0);
                            let align = 1_usize.checked_shl(pow).unwrap_or(1);
                            let idx = sections.len();
                            sections.push(Section {
                                name: name.clone(),
                                size,
                                align,
                                fileid: fileid.to_string(),
                                category: fileid.to_string(),
                                finalloc: None,
                                finalsegloc: 0,
                                relocs: Vec::new(),
                            });
                            section_map.insert(name, idx);
                        }
                    }
                }
            }
            Some("symbol") => {
                if raw_line.len() > 17 {
                    if let Some(offset_str) = raw_line.get(..8) {
                        if let Ok(offset) =
                            usize::from_str_radix(offset_str, 16)
                        {
                            if let Some(rest) = raw_line.get(17..) {
                                let parts: Vec<&str> =
                                    rest.split_whitespace().collect();
                                let (sec_name_opt, size_str, name) = match parts
                                    .len()
                                {
                                    2 => (
                                        parts.first().copied(),
                                        "0",
                                        parts.get(1).copied().unwrap_or(""),
                                    ),
                                    3 => (
                                        parts.first().copied(),
                                        parts.get(1).copied().unwrap_or("0"),
                                        parts.get(2).copied().unwrap_or(""),
                                    ),
                                    4 if parts.get(2) == Some(&".hidden") => (
                                        parts.first().copied(),
                                        parts.get(1).copied().unwrap_or("0"),
                                        parts.get(3).copied().unwrap_or(""),
                                    ),
                                    _ => continue,
                                };
                                let size = usize::from_str_radix(size_str, 16)
                                    .unwrap_or(0);
                                let sec_name = match sec_name_opt {
                                    Some("*UND*") | None => None,
                                    Some(s) => Some(s.to_string()),
                                };
                                symbols.insert(
                                    name.to_string(),
                                    Symbol {
                                        name: name.to_string(),
                                        offset,
                                        size,
                                        section_name: sec_name,
                                        fileid: fileid.to_string(),
                                    },
                                );
                            }
                        }
                    }
                }
            }
            Some("reloc") => {
                let parts: Vec<&str> = line.split_whitespace().collect();
                if parts.len() >= 3 {
                    if let (Some(part0), Some(reloc_type_str), Some(part2)) =
                        (parts.first(), parts.get(1), parts.get(2))
                    {
                        if let (Ok(offset), Some(sec_idx)) = (
                            usize::from_str_radix(part0, 16),
                            current_reloc_section_idx,
                        ) {
                            let reloc_type = reloc_type_str.to_string();
                            let symbolname =
                                strip_reloc_offset(part2).to_string();
                            if !symbols.contains_key(&symbolname)
                                && section_map.contains_key(&symbolname)
                            {
                                symbols.insert(
                                    symbolname.clone(),
                                    Symbol {
                                        name: symbolname.clone(),
                                        offset: 0,
                                        size: 0,
                                        section_name: Some(symbolname.clone()),
                                        fileid: fileid.to_string(),
                                    },
                                );
                            }
                            if let Some(sec) = sections.get_mut(sec_idx) {
                                sec.relocs.push(Reloc {
                                    offset,
                                    reloc_type,
                                    symbolname,
                                });
                            }
                        }
                    }
                }
            }
            _ => {}
        }
    }

    Ok((sections, symbols))
}

fn scan_config(path: &Path) -> HashMap<String, usize> {
    let mut map = HashMap::new();
    let Ok(content) = fs::read_to_string(path) else {
        return map;
    };
    for line in content.lines() {
        let parts: Vec<&str> = line.split_whitespace().collect();
        if parts.len() == 3 && parts.first() == Some(&"#define") {
            if let (Some(name_str), Some(val_str)) =
                (parts.get(1), parts.get(2))
            {
                let val =
                    if val_str.starts_with("0x") || val_str.starts_with("0X") {
                        let hex_part = val_str.get(2..).unwrap_or("");
                        usize::from_str_radix(hex_part, 16).unwrap_or(0)
                    } else {
                        val_str.parse::<usize>().unwrap_or(0)
                    };
                map.insert((*name_str).to_string(), val);
            }
        }
    }
    map
}

fn resolve_reloc_symbol<'a>(
    reloc: &Reloc,
    sec_fileid: &'a str,
    symbols_by_fileid: &'a HashMap<String, HashMap<String, Symbol>>,
) -> Option<(&'a Symbol, &'a str)> {
    let symbolname = reloc.symbolname.as_str();
    let mustbecfunc = symbolname.starts_with("_cfunc");

    if mustbecfunc {
        for fileid in ["16", "32seg", "32flat"] {
            let symprefix = format!("_cfunc{fileid}_");
            if symbolname.starts_with(&symprefix) {
                let funcname = symbolname.get(symprefix.len()..).unwrap_or("");
                if let Some(syms) = symbols_by_fileid.get(fileid) {
                    if let Some(sym) = syms.get(funcname) {
                        if let Some(ref sec_name) = sym.section_name {
                            if !sec_name.starts_with(".discard.") {
                                let isdestcfunc = sec_name
                                    .starts_with(".text.")
                                    && !sec_name.starts_with(".text.asm.");
                                if isdestcfunc {
                                    return Some((sym, fileid));
                                }
                            }
                        }
                    }
                }
            }
        }
        return None;
    }

    if let Some(syms) = symbols_by_fileid.get(sec_fileid) {
        if let Some(sym) = syms.get(symbolname) {
            if let Some(ref sec_name) = sym.section_name {
                if !sec_name.starts_with(".discard.") {
                    return Some((sym, sec_fileid));
                }
            }
        }
    }

    for fileid in ["16", "32seg", "32flat"] {
        if fileid != sec_fileid {
            if let Some(syms) = symbols_by_fileid.get(fileid) {
                if let Some(sym) = syms.get(symbolname) {
                    if let Some(ref sec_name) = sym.section_name {
                        if !sec_name.starts_with(".discard.") {
                            let isdestcfunc = sec_name.starts_with(".text.")
                                && !sec_name.starts_with(".text.asm.");
                            if !isdestcfunc {
                                return Some((sym, fileid));
                            }
                        }
                    }
                }
            }
        }
    }

    None
}

fn check_keep(
    reloc: &Reloc,
    sec_fileid: &str,
    symbols_by_fileid: &HashMap<String, HashMap<String, Symbol>>,
) -> Option<(String, String)> {
    if let Some((sym, _)) =
        resolve_reloc_symbol(reloc, sec_fileid, symbols_by_fileid)
    {
        if let Some(ref sec_name) = sym.section_name {
            return Some((sym.fileid.clone(), sec_name.clone()));
        }
    }
    None
}

fn out_xrefs(
    sections_with_relocs: &[Section],
    all_kept_sections: &[Section],
    symbols_by_fileid: &HashMap<String, HashMap<String, Symbol>>,
    export_syms: &[&Symbol],
    use_seg: bool,
    force_delta: isize,
) -> String {
    let mut xrefs: BTreeMap<String, usize> = BTreeMap::new();
    for sym in export_syms {
        if let Some(ref sec_name) = sym.section_name {
            if let Some(sec) = all_kept_sections
                .iter()
                .find(|s| s.fileid == sym.fileid && s.name == *sec_name)
            {
                let loc = if use_seg {
                    sec.finalsegloc
                } else {
                    sec.finalloc.unwrap_or(0)
                };
                let loc_isize = isize::try_from(loc).unwrap_or(0);
                let offset_isize = isize::try_from(sym.offset).unwrap_or(0);
                let final_loc_isize = loc_isize
                    .saturating_add(force_delta)
                    .saturating_add(offset_isize);
                let final_loc = usize::try_from(final_loc_isize).unwrap_or(0);
                xrefs.insert(sym.name.clone(), final_loc);
            }
        }
    }

    for sec in sections_with_relocs {
        for reloc in &sec.relocs {
            let symbolname = &reloc.symbolname;
            let res =
                resolve_reloc_symbol(reloc, &sec.fileid, symbols_by_fileid);
            if let Some((sym, fid)) = res {
                if fid != sec.fileid || sym.name != *symbolname {
                    if let Some(ref sec_name) = sym.section_name {
                        let target_sec = all_kept_sections
                            .iter()
                            .find(|s| s.fileid == fid && s.name == *sec_name);
                        if let Some(target_sec) = target_sec {
                            let loc = if use_seg {
                                target_sec.finalsegloc
                            } else {
                                target_sec.finalloc.unwrap_or(0)
                            };
                            let loc_isize = isize::try_from(loc).unwrap_or(0);
                            let offset_isize =
                                isize::try_from(sym.offset).unwrap_or(0);
                            let final_loc_isize = loc_isize
                                .saturating_add(force_delta)
                                .saturating_add(offset_isize);
                            let final_loc =
                                usize::try_from(final_loc_isize).unwrap_or(0);
                            xrefs.insert(symbolname.clone(), final_loc);
                        }
                    }
                }
            }
        }
    }

    let mut out = String::new();
    for (name, loc) in xrefs {
        let _ = writeln!(out, "{name} = 0x{loc:x} ;");
    }
    out
}

fn find_reachable(
    anchor_secs: &[(String, String)],
    all_sections: &[Section],
    symbols_by_fileid: &HashMap<String, HashMap<String, Symbol>>,
) -> HashSet<(String, String)> {
    let sec_map: HashMap<(String, String), &Section> = all_sections
        .iter()
        .map(|sec| ((sec.fileid.clone(), sec.name.clone()), sec))
        .collect();

    let mut reachable = HashSet::new();
    let mut pending = Vec::new();

    for key in anchor_secs {
        if sec_map.contains_key(key) && reachable.insert(key.clone()) {
            pending.push(key.clone());
        }
    }

    while let Some(key) = pending.pop() {
        if let Some(sec) = sec_map.get(&key) {
            for reloc in &sec.relocs {
                if let Some(target_key) =
                    check_keep(reloc, &sec.fileid, symbols_by_fileid)
                {
                    if reachable.insert(target_key.clone()) {
                        pending.push(target_key);
                    }
                }
            }
        }
    }

    reachable
}

fn find_runtime_reachable(
    anchor_secs: &[(String, String)],
    all_sections: &[Section],
    symbols_by_fileid: &HashMap<String, HashMap<String, Symbol>>,
) -> HashSet<(String, String)> {
    let sec_by_key: HashMap<(String, String), &Section> = all_sections
        .iter()
        .map(|sec| ((sec.fileid.clone(), sec.name.clone()), sec))
        .collect();

    let mut reachable = HashSet::new();
    let mut pending = Vec::new();

    for key in anchor_secs {
        if sec_by_key.contains_key(key) && reachable.insert(key.clone()) {
            pending.push(key.clone());
        }
    }

    while let Some(key) = pending.pop() {
        if let Some(sec) = sec_by_key.get(&key) {
            for reloc in &sec.relocs {
                if let Some(next_key) =
                    check_keep(reloc, &sec.fileid, symbols_by_fileid)
                {
                    if let Some(target_sec) = sec_by_key.get(&next_key) {
                        if !target_sec.name.contains(".init.")
                            && sec_by_key.contains_key(&next_key)
                            && reachable.insert(next_key.clone())
                        {
                            pending.push(next_key);
                        }
                    }
                }
            }
        }
    }

    reachable
}

fn fit_sections(
    fixed_sections: &mut [(usize, Section)],
    fill_sections: &mut [Section],
) -> usize {
    fixed_sections.sort_by_key(|k| k.0);
    let firstfixed = fixed_sections.first().map_or(BUILD_BIOS_SIZE, |f| f.0);

    let mut fixed_addr = Vec::new();
    for i in 0..fixed_sections.len() {
        let Some((addr, sec)) = fixed_sections.get(i).map(|(a, s)| (*a, s))
        else {
            continue;
        };
        let nextaddr = if i.saturating_add(1) == fixed_sections.len() {
            BUILD_BIOS_SIZE
        } else {
            fixed_sections
                .get(i.saturating_add(1))
                .map_or(BUILD_BIOS_SIZE, |k| k.0)
        };
        let avail = nextaddr.saturating_sub(addr).saturating_sub(sec.size);
        fixed_addr.push((avail, addr, sec.size));
    }

    let mut can_relocate: Vec<(usize, usize, String, usize)> = fill_sections
        .iter()
        .enumerate()
        .map(|(idx, sec)| (sec.size, sec.align, sec.name.clone(), idx))
        .collect();
    can_relocate.sort();

    let mut used_indices = HashSet::new();

    for (freespace, fixed_addr_start, fixed_sec_size) in fixed_addr {
        let mut addpos = fixed_addr_start.saturating_add(fixed_sec_size);
        let nextfixedaddr = addpos.saturating_add(freespace);
        loop {
            let mut canfit = None;
            for &(size, align, _, idx) in &can_relocate {
                if used_indices.contains(&idx) {
                    continue;
                }
                if addpos.saturating_add(size) > nextfixedaddr {
                    break;
                }
                let fitnextaddr = alignpos(addpos, align).saturating_add(size);
                if fitnextaddr > nextfixedaddr {
                    continue;
                }
                canfit = Some((fitnextaddr, idx));
            }
            let Some((fitnextaddr, idx)) = canfit else {
                break;
            };
            used_indices.insert(idx);
            if let Some(target) = fill_sections.get_mut(idx) {
                target.finalloc = Some(addpos.saturating_add(BUILD_BIOS_ADDR));
                target.finalsegloc = addpos;
            }
            addpos = fitnextaddr;
        }
    }

    firstfixed.saturating_add(BUILD_BIOS_ADDR)
}

fn set_sections_start(
    sections: &mut [Section],
    endaddr: usize,
    minalign: usize,
    segoffset: usize,
) -> (usize, usize) {
    let mut totspace = 0_usize;
    let mut align = minalign;
    for sec in sections.iter() {
        align = align.max(sec.align);
        totspace = alignpos(totspace, sec.align).saturating_add(sec.size);
    }
    let startaddr = if align == 0 {
        endaddr.saturating_sub(totspace)
    } else {
        (endaddr
            .saturating_sub(totspace)
            .checked_div(align)
            .unwrap_or(0))
        .saturating_mul(align)
    };
    let mut curaddr = startaddr;
    for sec in sections.iter_mut() {
        curaddr = alignpos(curaddr, sec.align);
        sec.finalloc = Some(curaddr);
        sec.finalsegloc = curaddr.saturating_sub(segoffset);
        curaddr = curaddr.saturating_add(sec.size);
    }
    (startaddr, align)
}

fn get_sections_category(sections: &[Section], category: &str) -> Vec<Section> {
    sections
        .iter()
        .filter(|s| s.category == category)
        .cloned()
        .collect()
}

fn get_sections_prefix(sections: &[Section], prefix: &str) -> Vec<Section> {
    sections
        .iter()
        .filter(|s| s.name.starts_with(prefix))
        .cloned()
        .collect()
}

fn get_sections_fileid(sections: &[Section], fileid: &str) -> Vec<Section> {
    sections
        .iter()
        .filter(|s| s.fileid == fileid)
        .cloned()
        .collect()
}

fn do_layout(
    mut sections: Vec<Section>,
    config: &HashMap<String, usize>,
    genreloc: bool,
) -> LayoutInfo {
    let min_biostable =
        if config.get("CONFIG_ROM_SIZE").copied().unwrap_or(0) >= 256 {
            8192
        } else {
            2048
        };

    let sections16 = get_sections_category(&sections, "16");
    let mut textsections16 = get_sections_prefix(&sections16, ".text.");
    let rodatasections16 = get_sections_prefix(&sections16, ".rodata");
    let datasections16 = get_sections_prefix(&sections16, ".data16.");

    let mut fixedsections: Vec<(usize, Section)> = Vec::new();
    for sec in &sections {
        if sec.category == "fixed" {
            if let Ok(addr) = usize::from_str_radix(
                sec.name.trim_start_matches(".fixedaddr."),
                16,
            ) {
                fixedsections.push((addr, sec.clone()));
            }
        }
    }

    let firstfixed = fit_sections(&mut fixedsections, &mut textsections16);

    for sec in &mut sections {
        if sec.fileid == "16" && sec.name.starts_with(".text.") {
            if let Some(match_sec) =
                textsections16.iter().find(|s| s.name == sec.name)
            {
                sec.finalloc = match_sec.finalloc;
                sec.finalsegloc = match_sec.finalsegloc;
            }
        }
    }

    let mut remsections: Vec<Section> = textsections16
        .into_iter()
        .chain(rodatasections16)
        .chain(datasections16)
        .filter(|s| s.finalloc.is_none())
        .collect();

    let (sec16_start, _) =
        set_sections_start(&mut remsections, firstfixed, 1, BUILD_BIOS_ADDR);

    for sec in &remsections {
        if let Some(target) = sections
            .iter_mut()
            .find(|s| s.fileid == "16" && s.name == sec.name)
        {
            target.finalloc = sec.finalloc;
            target.finalsegloc = sec.finalsegloc;
        }
    }

    let sections32seg = get_sections_category(&sections, "32seg");
    let textsections32seg = get_sections_prefix(&sections32seg, ".text.");
    let rodatasections32seg = get_sections_prefix(&sections32seg, ".rodata");
    let datasections32seg = get_sections_prefix(&sections32seg, ".data32seg.");
    let mut sec32seg_all: Vec<Section> = textsections32seg
        .into_iter()
        .chain(rodatasections32seg)
        .chain(datasections32seg)
        .collect();
    let (sec32seg_start, _) =
        set_sections_start(&mut sec32seg_all, sec16_start, 1, BUILD_BIOS_ADDR);
    for sec in &sec32seg_all {
        if let Some(target) = sections
            .iter_mut()
            .find(|s| s.fileid == "32seg" && s.name == sec.name)
        {
            target.finalloc = sec.finalloc;
            target.finalsegloc = sec.finalsegloc;
        }
    }

    let mut sections32textfseg = get_sections_category(&sections, "32textfseg");
    let (sec32textfseg_start, _) =
        set_sections_start(&mut sections32textfseg, sec32seg_start, 16, 0);
    for sec in &sections32textfseg {
        if let Some(target) = sections
            .iter_mut()
            .find(|s| s.category == "32textfseg" && s.name == sec.name)
        {
            target.finalloc = sec.finalloc;
            target.finalsegloc = sec.finalsegloc;
        }
    }

    let mut sections32fseg = get_sections_category(&sections, "32fseg");
    let (sec32fseg_start, _) = set_sections_start(
        &mut sections32fseg,
        sec32textfseg_start,
        16,
        BUILD_BIOS_ADDR,
    );
    for sec in &sections32fseg {
        if let Some(target) = sections
            .iter_mut()
            .find(|s| s.category == "32fseg" && s.name == sec.name)
        {
            target.finalloc = sec.finalloc;
            target.finalsegloc = sec.finalsegloc;
        }
    }

    let sections32flat = get_sections_category(&sections, "32flat");
    let textsections32flat = get_sections_prefix(&sections32flat, ".text.");
    let rodatasections32flat = get_sections_prefix(&sections32flat, ".rodata");
    let datasections32flat = get_sections_prefix(&sections32flat, ".data.");
    let bsssections32flat = get_sections_prefix(&sections32flat, ".bss.");
    let mut sec32flat_all: Vec<Section> = textsections32flat
        .into_iter()
        .chain(rodatasections32flat)
        .chain(datasections32flat)
        .chain(bsssections32flat)
        .collect();
    let (mut sec32flat_start, _) =
        set_sections_start(&mut sec32flat_all, sec32fseg_start, 16, 0);

    let sections32init = get_sections_category(&sections, "32init");
    let init_text = get_sections_prefix(&sections32init, ".text.");
    let init_rodata = get_sections_prefix(&sections32init, ".rodata");
    let init_data = get_sections_prefix(&sections32init, ".data.");
    let init_bss = get_sections_prefix(&sections32init, ".bss.");
    let mut sec32init_all: Vec<Section> = init_text
        .into_iter()
        .chain(init_rodata)
        .chain(init_data)
        .chain(init_bss)
        .collect();
    let (mut sec32init_start, mut sec32init_align) =
        set_sections_start(&mut sec32init_all, sec32flat_start, 16, 0);

    let mut zonefseg_end = if genreloc {
        sec32flat_start
    } else {
        sec32init_start
    };
    let mut zonefseg_start = BUILD_BIOS_ADDR;
    if zonefseg_start.saturating_add(min_biostable) > zonefseg_end {
        zonefseg_end = sec32fseg_start;
        zonefseg_start = zonefseg_end.saturating_sub(min_biostable);
        let res_flat =
            set_sections_start(&mut sec32flat_all, zonefseg_start, 16, 0);
        sec32flat_start = res_flat.0;
        let res_init =
            set_sections_start(&mut sec32init_all, sec32flat_start, 16, 0);
        sec32init_start = res_init.0;
        sec32init_align = res_init.1;
    }

    for sec in &sec32flat_all {
        if let Some(target) = sections
            .iter_mut()
            .find(|s| s.fileid == "32flat" && s.name == sec.name)
        {
            target.finalloc = sec.finalloc;
            target.finalsegloc = sec.finalsegloc;
        }
    }
    for sec in &sec32init_all {
        if let Some(target) = sections
            .iter_mut()
            .find(|s| s.category == "32init" && s.name == sec.name)
        {
            target.finalloc = sec.finalloc;
            target.finalsegloc = sec.finalsegloc;
        }
    }

    let final_readonly_start = if genreloc {
        BUILD_BIOS_ADDR.min(sec32flat_start)
    } else {
        BUILD_BIOS_ADDR.min(sec32init_start)
    };

    let mut sections32low = get_sections_category(&sections, "32low");
    let sec32low_end = sec32init_start;
    let (final_sec32low_end, zonelow_base) = if config
        .get("CONFIG_MALLOC_UPPERMEMORY")
        .copied()
        .unwrap_or(0)
        != 0
    {
        let f_end = final_readonly_start;
        let base = max_align(
            BUILD_ROM_START,
            alignpos(f_end.saturating_sub(64 * 1024), 2 * 1024),
        );
        (f_end, base)
    } else {
        let f_end = BUILD_LOWRAM_END;
        let base = f_end.saturating_sub(64 * 1024);
        (f_end, base)
    };

    let final_end_isize = isize::try_from(final_sec32low_end).unwrap_or(0);
    let sec32low_end_isize = isize::try_from(sec32low_end).unwrap_or(0);
    let relocdelta = final_end_isize.saturating_sub(sec32low_end_isize);
    let zonelow_base_isize = isize::try_from(zonelow_base).unwrap_or(0);
    let segoff_isize = zonelow_base_isize.saturating_sub(relocdelta);
    let segoff = usize::try_from(segoff_isize).unwrap_or(0);
    let (sec32low_start, _) =
        set_sections_start(&mut sections32low, sec32low_end, 16, segoff);

    for sec in &sections32low {
        if let Some(target) = sections
            .iter_mut()
            .find(|s| s.category == "32low" && s.name == sec.name)
        {
            target.finalloc = sec.finalloc;
            target.finalsegloc = sec.finalsegloc;
        }
    }

    let sec32low_start_isize = isize::try_from(sec32low_start).unwrap_or(0);
    let final_sec32low_start =
        usize::try_from(sec32low_start_isize.saturating_add(relocdelta))
            .unwrap_or(0);

    let size16 = BUILD_BIOS_ADDR
        .saturating_add(BUILD_BIOS_SIZE)
        .saturating_sub(sec16_start);
    let size32seg = sec16_start.saturating_sub(sec32seg_start);
    let size32textfseg = sec32seg_start.saturating_sub(sec32textfseg_start);
    let size32fseg = sec32textfseg_start.saturating_sub(sec32fseg_start);
    let size32flat = sec32fseg_start.saturating_sub(sec32flat_start);
    let size32init = sec32flat_start.saturating_sub(sec32init_start);
    let sizelow = sec32low_end.saturating_sub(sec32low_start);
    println!("16bit size:           {size16}");
    println!("32bit segmented size: {size32seg}");
    println!(
        "32bit flat size:      {}",
        size32flat.saturating_add(size32textfseg)
    );
    println!("32bit flat init size: {size32init}");
    println!("Lowmem size:          {sizelow}");
    println!("f-segment var size:   {size32fseg}");

    LayoutInfo {
        sections,
        config: config.clone(),
        genreloc,
        sec32init_start,
        sec32init_end: sec32flat_start,
        sec32init_align,
        sec32low_start,
        sec32low_end,
        zonelow_base,
        final_sec32low_start,
        zonefseg_start,
        zonefseg_end,
        final_readonly_start,
        varlowsyms: Vec::new(),
        entrysym: None,
    }
}

fn max_align(a: usize, b: usize) -> usize {
    a.max(b)
}

fn out_sections(sections: &[Section], use_seg: bool) -> String {
    let mut out = String::new();
    for sec in sections {
        let loc = if use_seg {
            sec.finalsegloc
        } else {
            sec.finalloc.unwrap_or(0)
        };
        let _ = writeln!(out, "{} 0x{loc:x} : {{ *({}) }}", sec.name, sec.name);
    }
    out
}

fn out_rel_sections(
    sections: &[Section],
    startsym: &str,
    use_seg: bool,
) -> String {
    let mut sorted_sections: Vec<(usize, &Section)> = sections
        .iter()
        .filter_map(|sec| {
            let loc = if use_seg {
                sec.finalsegloc
            } else {
                sec.finalloc?
            };
            Some((loc, sec))
        })
        .collect();
    sorted_sections.sort_by_key(|k| k.0);

    let mut out = String::new();
    for (loc, sec) in sorted_sections {
        let _ = writeln!(out, ". = ( 0x{loc:x} - {startsym} ) ;");
        if sec.name == ".rodata.str1.1" || sec.name == ".rodata" {
            let _ = writeln!(out, "_rodata{} = . ;", sec.fileid);
        }
        let _ = writeln!(out, "*{}.*({})", sec.fileid, sec.name);
    }
    out
}

fn get_relocs(
    sections: &[Section],
    to_section_set: &HashSet<(String, String)>,
    target_type: Option<&str>,
) -> Vec<usize> {
    let mut list = Vec::new();
    for sec in sections {
        if let Some(sec_loc) = sec.finalloc {
            for reloc in &sec.relocs {
                if target_type.is_none_or(|t| reloc.reloc_type == t) {
                    if to_section_set.contains(&(
                        sec.fileid.clone(),
                        reloc.symbolname.clone(),
                    )) {
                        list.push(sec_loc.saturating_add(reloc.offset));
                    }
                }
            }
        }
    }
    list
}

fn str_relocs(outname: &str, outrel: &str, relocs: &mut [usize]) -> String {
    relocs.sort_unstable();
    let mut out = format!("        {outname}_start = ABSOLUTE(.) ;\n");
    for pos in relocs {
        let _ = writeln!(out, "LONG(0x{pos:x} - {outrel})");
    }
    let _ = writeln!(out, "        {outname}_end = ABSOLUTE(.) ;\n");
    out
}

fn write_linker_scripts(
    li: &LayoutInfo,
    symbols_by_fileid: &HashMap<String, HashMap<String, Symbol>>,
    out16: &Path,
    out32seg: &Path,
    out32flat: &Path,
) -> Result<()> {
    let filesections16 = get_sections_fileid(&li.sections, "16");
    let out_16_str = format!(
        "{}{}\n    zonelow_base = 0x{:x} ;\n    _zonelow_seg = 0x{:x} ;\n\n{}\n{}",
        COMMONHEADER,
        out_xrefs(
            &filesections16,
            &li.sections,
            symbols_by_fileid,
            &[],
            true,
            0
        ),
        li.zonelow_base,
        li.zonelow_base / 16,
        out_sections(&filesections16, true),
        COMMONTRAILER
    );

    if let Some(parent) = out16.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(out16, out_16_str)?;

    let filesections32seg = get_sections_fileid(&li.sections, "32seg");
    let out_32seg_str = format!(
        "{}{}{}\n{}",
        COMMONHEADER,
        out_xrefs(
            &filesections32seg,
            &li.sections,
            symbols_by_fileid,
            &[],
            true,
            0
        ),
        out_sections(&filesections32seg, true),
        COMMONTRAILER
    );
    if let Some(parent) = out32seg.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(out32seg, out_32seg_str)?;

    let mut relocstr = String::new();
    let mut sec32all_start = li.sec32low_start;
    if li.genreloc {
        let init_set: HashSet<(String, String)> =
            get_sections_category(&li.sections, "32init")
                .into_iter()
                .map(|s| (s.fileid, s.name))
                .collect();
        let non_init_set: HashSet<(String, String)> = li
            .sections
            .iter()
            .filter(|s| !init_set.contains(&(s.fileid.clone(), s.name.clone())))
            .map(|s| (s.fileid.clone(), s.name.clone()))
            .collect();

        let init_sections = get_sections_category(&li.sections, "32init");
        let non_init_sections: Vec<Section> = li
            .sections
            .iter()
            .filter(|s| !init_set.contains(&(s.fileid.clone(), s.name.clone())))
            .cloned()
            .collect();

        let mut absrelocs =
            get_relocs(&init_sections, &init_set, Some("R_386_32"));
        let mut relrelocs =
            get_relocs(&init_sections, &non_init_set, Some("R_386_PC32"));
        let mut initrelocs = get_relocs(&non_init_sections, &init_set, None);

        let numrelocs = absrelocs
            .len()
            .saturating_add(relrelocs.len())
            .saturating_add(initrelocs.len());
        sec32all_start =
            sec32all_start.saturating_sub(numrelocs.saturating_mul(4));

        relocstr = format!(
            "{}{}{}",
            str_relocs("_reloc_abs", "code32init_start", &mut absrelocs),
            str_relocs("_reloc_rel", "code32init_start", &mut relrelocs),
            str_relocs("_reloc_init", "code32flat_start", &mut initrelocs)
        );
    }

    let export_varlow: Vec<&Symbol> = li.varlowsyms.iter().collect();
    let final_low_isize = isize::try_from(li.final_sec32low_start).unwrap_or(0);
    let low_start_isize = isize::try_from(li.sec32low_start).unwrap_or(0);
    let force_delta = final_low_isize.saturating_sub(low_start_isize);
    let mut out_32flat_prefix = out_xrefs(
        &[],
        &li.sections,
        symbols_by_fileid,
        &export_varlow,
        false,
        force_delta,
    );

    let multiboot_header =
        if li.config.get("CONFIG_MULTIBOOT").copied().unwrap_or(0) != 0 {
            sec32all_start = sec32all_start.saturating_sub(12);
            "LONG(0x1BADB002) LONG(0) LONG(-0x1BADB002)"
        } else {
            ""
        };

    let max_align = li.sections.iter().map(|s| s.align).max().unwrap_or(1);
    let mask = max_align.saturating_sub(1);
    sec32all_start &= !mask;

    let entry_export =
        li.entrysym.as_ref().map(|s| vec![s]).unwrap_or_default();
    out_32flat_prefix.push_str(&out_xrefs(
        &get_sections_fileid(&li.sections, "32flat"),
        &li.sections,
        symbols_by_fileid,
        &entry_export,
        false,
        0,
    ));

    let filesections32flat = get_sections_fileid(&li.sections, "32flat");
    let rel_sections_str =
        out_rel_sections(&filesections32flat, "code32flat_start", false);

    let entry_name = li
        .entrysym
        .as_ref()
        .map_or("reset_vector", |s| s.name.as_str());

    let out_32flat_str = format!(
        "{COMMONHEADER}{out_32flat_prefix}    _reloc_min_align = 0x{:x} ;\n    zonefseg_start = 0x{:x} ;\n    zonefseg_end = 0x{:x} ;\n    zonelow_base = 0x{:x} ;\n    final_varlow_start = 0x{:x} ;\n    final_readonly_start = 0x{:x} ;\n    varlow_start = 0x{:x} ;\n    varlow_end = 0x{:x} ;\n    code32init_start = 0x{:x} ;\n    code32init_end = 0x{:x} ;\n\n    code32flat_start = 0x{:x} ;\n    .text code32flat_start : {{\n{}\n{}\n{}\n        code32flat_end = ABSOLUTE(.) ;\n    }} :text\n{COMMONTRAILER}\nENTRY({entry_name})\nPHDRS\n{{\n        text PT_LOAD AT ( code32flat_start ) ;\n}}\n",
        li.sec32init_align,
        li.zonefseg_start,
        li.zonefseg_end,
        li.zonelow_base,
        li.final_sec32low_start,
        li.final_readonly_start,
        li.sec32low_start,
        li.sec32low_end,
        li.sec32init_start,
        li.sec32init_end,
        sec32all_start,
        multiboot_header,
        relocstr,
        rel_sections_str
    );

    if let Some(parent) = out32flat.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(out32flat, out_32flat_str)?;

    Ok(())
}

/*

Licenses from SeaBIOS:

COPYING:

```
                    GNU GENERAL PUBLIC LICENSE
                       Version 3, 29 June 2007

 Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/>
 Everyone is permitted to copy and distribute verbatim copies
 of this license document, but changing it is not allowed.

                            Preamble

  The GNU General Public License is a free, copyleft license for
software and other kinds of works.

  The licenses for most software and other practical works are designed
to take away your freedom to share and change the works.  By contrast,
the GNU General Public License is intended to guarantee your freedom to
share and change all versions of a program--to make sure it remains free
software for all its users.  We, the Free Software Foundation, use the
GNU General Public License for most of our software; it applies also to
any other work released this way by its authors.  You can apply it to
your programs, too.

  When we speak of free software, we are referring to freedom, not
price.  Our General Public Licenses are designed to make sure that you
have the freedom to distribute copies of free software (and charge for
them if you wish), that you receive source code or can get it if you
want it, that you can change the software or use pieces of it in new
free programs, and that you know you can do these things.

  To protect your rights, we need to prevent others from denying you
these rights or asking you to surrender the rights.  Therefore, you have
certain responsibilities if you distribute copies of the software, or if
you modify it: responsibilities to respect the freedom of others.

  For example, if you distribute copies of such a program, whether
gratis or for a fee, you must pass on to the recipients the same
freedoms that you received.  You must make sure that they, too, receive
or can get the source code.  And you must show them these terms so they
know their rights.

  Developers that use the GNU GPL protect your rights with two steps:
(1) assert copyright on the software, and (2) offer you this License
giving you legal permission to copy, distribute and/or modify it.

  For the developers' and authors' protection, the GPL clearly explains
that there is no warranty for this free software.  For both users' and
authors' sake, the GPL requires that modified versions be marked as
changed, so that their problems will not be attributed erroneously to
authors of previous versions.

  Some devices are designed to deny users access to install or run
modified versions of the software inside them, although the manufacturer
can do so.  This is fundamentally incompatible with the aim of
protecting users' freedom to change the software.  The systematic
pattern of such abuse occurs in the area of products for individuals to
use, which is precisely where it is most unacceptable.  Therefore, we
have designed this version of the GPL to prohibit the practice for those
products.  If such problems arise substantially in other domains, we
stand ready to extend this provision to those domains in future versions
of the GPL, as needed to protect the freedom of users.

  Finally, every program is threatened constantly by software patents.
States should not allow patents to restrict development and use of
software on general-purpose computers, but in those that do, we wish to
avoid the special danger that patents applied to a free program could
make it effectively proprietary.  To prevent this, the GPL assures that
patents cannot be used to render the program non-free.

  The precise terms and conditions for copying, distribution and
modification follow.

                       TERMS AND CONDITIONS

  0. Definitions.

  "This License" refers to version 3 of the GNU General Public License.

  "Copyright" also means copyright-like laws that apply to other kinds of
works, such as semiconductor masks.

  "The Program" refers to any copyrightable work licensed under this
License.  Each licensee is addressed as "you".  "Licensees" and
"recipients" may be individuals or organizations.

  To "modify" a work means to copy from or adapt all or part of the work
in a fashion requiring copyright permission, other than the making of an
exact copy.  The resulting work is called a "modified version" of the
earlier work or a work "based on" the earlier work.

  A "covered work" means either the unmodified Program or a work based
on the Program.

  To "propagate" a work means to do anything with it that, without
permission, would make you directly or secondarily liable for
infringement under applicable copyright law, except executing it on a
computer or modifying a private copy.  Propagation includes copying,
distribution (with or without modification), making available to the
public, and in some countries other activities as well.

  To "convey" a work means any kind of propagation that enables other
parties to make or receive copies.  Mere interaction with a user through
a computer network, with no transfer of a copy, is not conveying.

  An interactive user interface displays "Appropriate Legal Notices"
to the extent that it includes a convenient and prominently visible
feature that (1) displays an appropriate copyright notice, and (2)
tells the user that there is no warranty for the work (except to the
extent that warranties are provided), that licensees may convey the
work under this License, and how to view a copy of this License.  If
the interface presents a list of user commands or options, such as a
menu, a prominent item in the list meets this criterion.

  1. Source Code.

  The "source code" for a work means the preferred form of the work
for making modifications to it.  "Object code" means any non-source
form of a work.

  A "Standard Interface" means an interface that either is an official
standard defined by a recognized standards body, or, in the case of
interfaces specified for a particular programming language, one that
is widely used among developers working in that language.

  The "System Libraries" of an executable work include anything, other
than the work as a whole, that (a) is included in the normal form of
packaging a Major Component, but which is not part of that Major
Component, and (b) serves only to enable use of the work with that
Major Component, or to implement a Standard Interface for which an
implementation is available to the public in source code form.  A
"Major Component", in this context, means a major essential component
(kernel, window system, and so on) of the specific operating system
(if any) on which the executable work runs, or a compiler used to
produce the work, or an object code interpreter used to run it.

  The "Corresponding Source" for a work in object code form means all
the source code needed to generate, install, and (for an executable
work) run the object code and to modify the work, including scripts to
control those activities.  However, it does not include the work's
System Libraries, or general-purpose tools or generally available free
programs which are used unmodified in performing those activities but
which are not part of the work.  For example, Corresponding Source
includes interface definition files associated with source files for
the work, and the source code for shared libraries and dynamically
linked subprograms that the work is specifically designed to require,
such as by intimate data communication or control flow between those
subprograms and other parts of the work.

  The Corresponding Source need not include anything that users
can regenerate automatically from other parts of the Corresponding
Source.

  The Corresponding Source for a work in source code form is that
same work.

  2. Basic Permissions.

  All rights granted under this License are granted for the term of
copyright on the Program, and are irrevocable provided the stated
conditions are met.  This License explicitly affirms your unlimited
permission to run the unmodified Program.  The output from running a
covered work is covered by this License only if the output, given its
content, constitutes a covered work.  This License acknowledges your
rights of fair use or other equivalent, as provided by copyright law.

  You may make, run and propagate covered works that you do not
convey, without conditions so long as your license otherwise remains
in force.  You may convey covered works to others for the sole purpose
of having them make modifications exclusively for you, or provide you
with facilities for running those works, provided that you comply with
the terms of this License in conveying all material for which you do
not control copyright.  Those thus making or running the covered works
for you must do so exclusively on your behalf, under your direction
and control, on terms that prohibit them from making any copies of
your copyrighted material outside their relationship with you.

  Conveying under any other circumstances is permitted solely under
the conditions stated below.  Sublicensing is not allowed; section 10
makes it unnecessary.

  3. Protecting Users' Legal Rights From Anti-Circumvention Law.

  No covered work shall be deemed part of an effective technological
measure under any applicable law fulfilling obligations under article
11 of the WIPO copyright treaty adopted on 20 December 1996, or
similar laws prohibiting or restricting circumvention of such
measures.

  When you convey a covered work, you waive any legal power to forbid
circumvention of technological measures to the extent such circumvention
is effected by exercising rights under this License with respect to
the covered work, and you disclaim any intention to limit operation or
modification of the work as a means of enforcing, against the work's
users, your or third parties' legal rights to forbid circumvention of
technological measures.

  4. Conveying Verbatim Copies.

  You may convey verbatim copies of the Program's source code as you
receive it, in any medium, provided that you conspicuously and
appropriately publish on each copy an appropriate copyright notice;
keep intact all notices stating that this License and any
non-permissive terms added in accord with section 7 apply to the code;
keep intact all notices of the absence of any warranty; and give all
recipients a copy of this License along with the Program.

  You may charge any price or no price for each copy that you convey,
and you may offer support or warranty protection for a fee.

  5. Conveying Modified Source Versions.

  You may convey a work based on the Program, or the modifications to
produce it from the Program, in the form of source code under the
terms of section 4, provided that you also meet all of these conditions:

    a) The work must carry prominent notices stating that you modified
    it, and giving a relevant date.

    b) The work must carry prominent notices stating that it is
    released under this License and any conditions added under section
    7.  This requirement modifies the requirement in section 4 to
    "keep intact all notices".

    c) You must license the entire work, as a whole, under this
    License to anyone who comes into possession of a copy.  This
    License will therefore apply, along with any applicable section 7
    additional terms, to the whole of the work, and all its parts,
    regardless of how they are packaged.  This License gives no
    permission to license the work in any other way, but it does not
    invalidate such permission if you have separately received it.

    d) If the work has interactive user interfaces, each must display
    Appropriate Legal Notices; however, if the Program has interactive
    interfaces that do not display Appropriate Legal Notices, your
    work need not make them do so.

  A compilation of a covered work with other separate and independent
works, which are not by their nature extensions of the covered work,
and which are not combined with it such as to form a larger program,
in or on a volume of a storage or distribution medium, is called an
"aggregate" if the compilation and its resulting copyright are not
used to limit the access or legal rights of the compilation's users
beyond what the individual works permit.  Inclusion of a covered work
in an aggregate does not cause this License to apply to the other
parts of the aggregate.

  6. Conveying Non-Source Forms.

  You may convey a covered work in object code form under the terms
of sections 4 and 5, provided that you also convey the
machine-readable Corresponding Source under the terms of this License,
in one of these ways:

    a) Convey the object code in, or embodied in, a physical product
    (including a physical distribution medium), accompanied by the
    Corresponding Source fixed on a durable physical medium
    customarily used for software interchange.

    b) Convey the object code in, or embodied in, a physical product
    (including a physical distribution medium), accompanied by a
    written offer, valid for at least three years and valid for as
    long as you offer spare parts or customer support for that product
    model, to give anyone who possesses the object code either (1) a
    copy of the Corresponding Source for all the software in the
    product that is covered by this License, on a durable physical
    medium customarily used for software interchange, for a price no
    more than your reasonable cost of physically performing this
    conveying of source, or (2) access to copy the
    Corresponding Source from a network server at no charge.

    c) Convey individual copies of the object code with a copy of the
    written offer to provide the Corresponding Source.  This
    alternative is allowed only occasionally and noncommercially, and
    only if you received the object code with such an offer, in accord
    with subsection 6b.

    d) Convey the object code by offering access from a designated
    place (gratis or for a charge), and offer equivalent access to the
    Corresponding Source in the same way through the same place at no
    further charge.  You need not require recipients to copy the
    Corresponding Source along with the object code.  If the place to
    copy the object code is a network server, the Corresponding Source
    may be on a different server (operated by you or a third party)
    that supports equivalent copying facilities, provided you maintain
    clear directions next to the object code saying where to find the
    Corresponding Source.  Regardless of what server hosts the
    Corresponding Source, you remain obligated to ensure that it is
    available for as long as needed to satisfy these requirements.

    e) Convey the object code using peer-to-peer transmission, provided
    you inform other peers where the object code and Corresponding
    Source of the work are being offered to the general public at no
    charge under subsection 6d.

  A separable portion of the object code, whose source code is excluded
from the Corresponding Source as a System Library, need not be
included in conveying the object code work.

  A "User Product" is either (1) a "consumer product", which means any
tangible personal property which is normally used for personal, family,
or household purposes, or (2) anything designed or sold for incorporation
into a dwelling.  In determining whether a product is a consumer product,
doubtful cases shall be resolved in favor of coverage.  For a particular
product received by a particular user, "normally used" refers to a
typical or common use of that class of product, regardless of the status
of the particular user or of the way in which the particular user
actually uses, or expects or is expected to use, the product.  A product
is a consumer product regardless of whether the product has substantial
commercial, industrial or non-consumer uses, unless such uses represent
the only significant mode of use of the product.

  "Installation Information" for a User Product means any methods,
procedures, authorization keys, or other information required to install
and execute modified versions of a covered work in that User Product from
a modified version of its Corresponding Source.  The information must
suffice to ensure that the continued functioning of the modified object
code is in no case prevented or interfered with solely because
modification has been made.

  If you convey an object code work under this section in, or with, or
specifically for use in, a User Product, and the conveying occurs as
part of a transaction in which the right of possession and use of the
User Product is transferred to the recipient in perpetuity or for a
fixed term (regardless of how the transaction is characterized), the
Corresponding Source conveyed under this section must be accompanied
by the Installation Information.  But this requirement does not apply
if neither you nor any third party retains the ability to install
modified object code on the User Product (for example, the work has
been installed in ROM).

  The requirement to provide Installation Information does not include a
requirement to continue to provide support service, warranty, or updates
for a work that has been modified or installed by the recipient, or for
the User Product in which it has been modified or installed.  Access to a
network may be denied when the modification itself materially and
adversely affects the operation of the network or violates the rules and
protocols for communication across the network.

  Corresponding Source conveyed, and Installation Information provided,
in accord with this section must be in a format that is publicly
documented (and with an implementation available to the public in
source code form), and must require no special password or key for
unpacking, reading or copying.

  7. Additional Terms.

  "Additional permissions" are terms that supplement the terms of this
License by making exceptions from one or more of its conditions.
Additional permissions that are applicable to the entire Program shall
be treated as though they were included in this License, to the extent
that they are valid under applicable law.  If additional permissions
apply only to part of the Program, that part may be used separately
under those permissions, but the entire Program remains governed by
this License without regard to the additional permissions.

  When you convey a copy of a covered work, you may at your option
remove any additional permissions from that copy, or from any part of
it.  (Additional permissions may be written to require their own
removal in certain cases when you modify the work.)  You may place
additional permissions on material, added by you to a covered work,
for which you have or can give appropriate copyright permission.

  Notwithstanding any other provision of this License, for material you
add to a covered work, you may (if authorized by the copyright holders of
that material) supplement the terms of this License with terms:

    a) Disclaiming warranty or limiting liability differently from the
    terms of sections 15 and 16 of this License; or

    b) Requiring preservation of specified reasonable legal notices or
    author attributions in that material or in the Appropriate Legal
    Notices displayed by works containing it; or

    c) Prohibiting misrepresentation of the origin of that material, or
    requiring that modified versions of such material be marked in
    reasonable ways as different from the original version; or

    d) Limiting the use for publicity purposes of names of licensors or
    authors of the material; or

    e) Declining to grant rights under trademark law for use of some
    trade names, trademarks, or service marks; or

    f) Requiring indemnification of licensors and authors of that
    material by anyone who conveys the material (or modified versions of
    it) with contractual assumptions of liability to the recipient, for
    any liability that these contractual assumptions directly impose on
    those licensors and authors.

  All other non-permissive additional terms are considered "further
restrictions" within the meaning of section 10.  If the Program as you
received it, or any part of it, contains a notice stating that it is
governed by this License along with a term that is a further
restriction, you may remove that term.  If a license document contains
a further restriction but permits relicensing or conveying under this
License, you may add to a covered work material governed by the terms
of that license document, provided that the further restriction does
not survive such relicensing or conveying.

  If you add terms to a covered work in accord with this section, you
must place, in the relevant source files, a statement of the
additional terms that apply to those files, or a notice indicating
where to find the applicable terms.

  Additional terms, permissive or non-permissive, may be stated in the
form of a separately written license, or stated as exceptions;
the above requirements apply either way.

  8. Termination.

  You may not propagate or modify a covered work except as expressly
provided under this License.  Any attempt otherwise to propagate or
modify it is void, and will automatically terminate your rights under
this License (including any patent licenses granted under the third
paragraph of section 11).

  However, if you cease all violation of this License, then your
license from a particular copyright holder is reinstated (a)
provisionally, unless and until the copyright holder explicitly and
finally terminates your license, and (b) permanently, if the copyright
holder fails to notify you of the violation by some reasonable means
prior to 60 days after the cessation.

  Moreover, your license from a particular copyright holder is
reinstated permanently if the copyright holder notifies you of the
violation by some reasonable means, this is the first time you have
received notice of violation of this License (for any work) from that
copyright holder, and you cure the violation prior to 30 days after
your receipt of the notice.

  Termination of your rights under this section does not terminate the
licenses of parties who have received copies or rights from you under
this License.  If your rights have been terminated and not permanently
reinstated, you do not qualify to receive new licenses for the same
material under section 10.

  9. Acceptance Not Required for Having Copies.

  You are not required to accept this License in order to receive or
run a copy of the Program.  Ancillary propagation of a covered work
occurring solely as a consequence of using peer-to-peer transmission
to receive a copy likewise does not require acceptance.  However,
nothing other than this License grants you permission to propagate or
modify any covered work.  These actions infringe copyright if you do
not accept this License.  Therefore, by modifying or propagating a
covered work, you indicate your acceptance of this License to do so.

  10. Automatic Licensing of Downstream Recipients.

  Each time you convey a covered work, the recipient automatically
receives a license from the original licensors, to run, modify and
propagate that work, subject to this License.  You are not responsible
for enforcing compliance by third parties with this License.

  An "entity transaction" is a transaction transferring control of an
organization, or substantially all assets of one, or subdividing an
organization, or merging organizations.  If propagation of a covered
work results from an entity transaction, each party to that
transaction who receives a copy of the work also receives whatever
licenses to the work the party's predecessor in interest had or could
give under the previous paragraph, plus a right to possession of the
Corresponding Source of the work from the predecessor in interest, if
the predecessor has it or can get it with reasonable efforts.

  You may not impose any further restrictions on the exercise of the
rights granted or affirmed under this License.  For example, you may
not impose a license fee, royalty, or other charge for exercise of
rights granted under this License, and you may not initiate litigation
(including a cross-claim or counterclaim in a lawsuit) alleging that
any patent claim is infringed by making, using, selling, offering for
sale, or importing the Program or any portion of it.

  11. Patents.

  A "contributor" is a copyright holder who authorizes use under this
License of the Program or a work on which the Program is based.  The
work thus licensed is called the contributor's "contributor version".

  A contributor's "essential patent claims" are all patent claims
owned or controlled by the contributor, whether already acquired or
hereafter acquired, that would be infringed by some manner, permitted
by this License, of making, using, or selling its contributor version,
but do not include claims that would be infringed only as a
consequence of further modification of the contributor version.  For
purposes of this definition, "control" includes the right to grant
patent sublicenses in a manner consistent with the requirements of
this License.

  Each contributor grants you a non-exclusive, worldwide, royalty-free
patent license under the contributor's essential patent claims, to
make, use, sell, offer for sale, import and otherwise run, modify and
propagate the contents of its contributor version.

  In the following three paragraphs, a "patent license" is any express
agreement or commitment, however denominated, not to enforce a patent
(such as an express permission to practice a patent or covenant not to
sue for patent infringement).  To "grant" such a patent license to a
party means to make such an agreement or commitment not to enforce a
patent against the party.

  If you convey a covered work, knowingly relying on a patent license,
and the Corresponding Source of the work is not available for anyone
to copy, free of charge and under the terms of this License, through a
publicly available network server or other readily accessible means,
then you must either (1) cause the Corresponding Source to be so
available, or (2) arrange to deprive yourself of the benefit of the
patent license for this particular work, or (3) arrange, in a manner
consistent with the requirements of this License, to extend the patent
license to downstream recipients.  "Knowingly relying" means you have
actual knowledge that, but for the patent license, your conveying the
covered work in a country, or your recipient's use of the covered work
in a country, would infringe one or more identifiable patents in that
country that you have reason to believe are valid.

  If, pursuant to or in connection with a single transaction or
arrangement, you convey, or propagate by procuring conveyance of, a
covered work, and grant a patent license to some of the parties
receiving the covered work authorizing them to use, propagate, modify
or convey a specific copy of the covered work, then the patent license
you grant is automatically extended to all recipients of the covered
work and works based on it.

  A patent license is "discriminatory" if it does not include within
the scope of its coverage, prohibits the exercise of, or is
conditioned on the non-exercise of one or more of the rights that are
specifically granted under this License.  You may not convey a covered
work if you are a party to an arrangement with a third party that is
in the business of distributing software, under which you make payment
to the third party based on the extent of your activity of conveying
the work, and under which the third party grants, to any of the
parties who would receive the covered work from you, a discriminatory
patent license (a) in connection with copies of the covered work
conveyed by you (or copies made from those copies), or (b) primarily
for and in connection with specific products or compilations that
contain the covered work, unless you entered into that arrangement,
or that patent license was granted, prior to 28 March 2007.

  Nothing in this License shall be construed as excluding or limiting
any implied license or other defenses to infringement that may
otherwise be available to you under applicable patent law.

  12. No Surrender of Others' Freedom.

  If conditions are imposed on you (whether by court order, agreement or
otherwise) that contradict the conditions of this License, they do not
excuse you from the conditions of this License.  If you cannot convey a
covered work so as to satisfy simultaneously your obligations under this
License and any other pertinent obligations, then as a consequence you may
not convey it at all.  For example, if you agree to terms that obligate you
to collect a royalty for further conveying from those to whom you convey
the Program, the only way you could satisfy both those terms and this
License would be to refrain entirely from conveying the Program.

  13. Use with the GNU Affero General Public License.

  Notwithstanding any other provision of this License, you have
permission to link or combine any covered work with a work licensed
under version 3 of the GNU Affero General Public License into a single
combined work, and to convey the resulting work.  The terms of this
License will continue to apply to the part which is the covered work,
but the special requirements of the GNU Affero General Public License,
section 13, concerning interaction through a network will apply to the
combination as such.

  14. Revised Versions of this License.

  The Free Software Foundation may publish revised and/or new versions of
the GNU General Public License from time to time.  Such new versions will
be similar in spirit to the present version, but may differ in detail to
address new problems or concerns.

  Each version is given a distinguishing version number.  If the
Program specifies that a certain numbered version of the GNU General
Public License "or any later version" applies to it, you have the
option of following the terms and conditions either of that numbered
version or of any later version published by the Free Software
Foundation.  If the Program does not specify a version number of the
GNU General Public License, you may choose any version ever published
by the Free Software Foundation.

  If the Program specifies that a proxy can decide which future
versions of the GNU General Public License can be used, that proxy's
public statement of acceptance of a version permanently authorizes you
to choose that version for the Program.

  Later license versions may give you additional or different
permissions.  However, no additional obligations are imposed on any
author or copyright holder as a result of your choosing to follow a
later version.

  15. Disclaimer of Warranty.

  THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY
APPLICABLE LAW.  EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT
HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY
OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO,
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE.  THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM
IS WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF
ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

  16. Limitation of Liability.

  IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING
WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR CONVEYS
THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY
GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE
USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF
DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD
PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS),
EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF
SUCH DAMAGES.

  17. Interpretation of Sections 15 and 16.

  If the disclaimer of warranty and limitation of liability provided
above cannot be given local legal effect according to their terms,
reviewing courts shall apply local law that most closely approximates
an absolute waiver of all civil liability in connection with the
Program, unless a warranty or assumption of liability accompanies a
copy of the Program in return for a fee.

                     END OF TERMS AND CONDITIONS

            How to Apply These Terms to Your New Programs

  If you develop a new program, and you want it to be of the greatest
possible use to the public, the best way to achieve this is to make it
free software which everyone can redistribute and change under these terms.

  To do so, attach the following notices to the program.  It is safest
to attach them to the start of each source file to most effectively
state the exclusion of warranty; and each file should have at least
the "copyright" line and a pointer to where the full notice is found.

    <one line to give the program's name and a brief idea of what it does.>
    Copyright (C) <year>  <name of author>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

Also add information on how to contact you by electronic and paper mail.

  If the program does terminal interaction, make it output a short
notice like this when it starts in an interactive mode:

    <program>  Copyright (C) <year>  <name of author>
    This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'.
    This is free software, and you are welcome to redistribute it
    under certain conditions; type `show c' for details.

The hypothetical commands `show w' and `show c' should show the appropriate
parts of the General Public License.  Of course, your program's commands
might be different; for a GUI interface, you would use an "about box".

  You should also get your employer (if you work as a programmer) or school,
if any, to sign a "copyright disclaimer" for the program, if necessary.
For more information on this, and how to apply and follow the GNU GPL, see
<http://www.gnu.org/licenses/>.

  The GNU General Public License does not permit incorporating your program
into proprietary programs.  If your program is a subroutine library, you
may consider it more useful to permit linking proprietary applications with
the library.  If this is what you want to do, use the GNU Lesser General
Public License instead of this License.  But first, please read
<http://www.gnu.org/philosophy/why-not-lgpl.html>.
```

COPYING.LESSER:

```
           GNU LESSER GENERAL PUBLIC LICENSE
                       Version 3, 29 June 2007

 Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/>
 Everyone is permitted to copy and distribute verbatim copies
 of this license document, but changing it is not allowed.


  This version of the GNU Lesser General Public License incorporates
the terms and conditions of version 3 of the GNU General Public
License, supplemented by the additional permissions listed below.

  0. Additional Definitions.

  As used herein, "this License" refers to version 3 of the GNU Lesser
General Public License, and the "GNU GPL" refers to version 3 of the GNU
General Public License.

  "The Library" refers to a covered work governed by this License,
other than an Application or a Combined Work as defined below.

  An "Application" is any work that makes use of an interface provided
by the Library, but which is not otherwise based on the Library.
Defining a subclass of a class defined by the Library is deemed a mode
of using an interface provided by the Library.

  A "Combined Work" is a work produced by combining or linking an
Application with the Library.  The particular version of the Library
with which the Combined Work was made is also called the "Linked
Version".

  The "Minimal Corresponding Source" for a Combined Work means the
Corresponding Source for the Combined Work, excluding any source code
for portions of the Combined Work that, considered in isolation, are
based on the Application, and not on the Linked Version.

  The "Corresponding Application Code" for a Combined Work means the
object code and/or source code for the Application, including any data
and utility programs needed for reproducing the Combined Work from the
Application, but excluding the System Libraries of the Combined Work.

  1. Exception to Section 3 of the GNU GPL.

  You may convey a covered work under sections 3 and 4 of this License
without being bound by section 3 of the GNU GPL.

  2. Conveying Modified Versions.

  If you modify a copy of the Library, and, in your modifications, a
facility refers to a function or data to be supplied by an Application
that uses the facility (other than as an argument passed when the
facility is invoked), then you may convey a copy of the modified
version:

   a) under this License, provided that you make a good faith effort to
   ensure that, in the event an Application does not supply the
   function or data, the facility still operates, and performs
   whatever part of its purpose remains meaningful, or

   b) under the GNU GPL, with none of the additional permissions of
   this License applicable to that copy.

  3. Object Code Incorporating Material from Library Header Files.

  The object code form of an Application may incorporate material from
a header file that is part of the Library.  You may convey such object
code under terms of your choice, provided that, if the incorporated
material is not limited to numerical parameters, data structure
layouts and accessors, or small macros, inline functions and templates
(ten or fewer lines in length), you do both of the following:

   a) Give prominent notice with each copy of the object code that the
   Library is used in it and that the Library and its use are
   covered by this License.

   b) Accompany the object code with a copy of the GNU GPL and this license
   document.

  4. Combined Works.

  You may convey a Combined Work under terms of your choice that,
taken together, effectively do not restrict modification of the
portions of the Library contained in the Combined Work and reverse
engineering for debugging such modifications, if you also do each of
the following:

   a) Give prominent notice with each copy of the Combined Work that
   the Library is used in it and that the Library and its use are
   covered by this License.

   b) Accompany the Combined Work with a copy of the GNU GPL and this license
   document.

   c) For a Combined Work that displays copyright notices during
   execution, include the copyright notice for the Library among
   these notices, as well as a reference directing the user to the
   copies of the GNU GPL and this license document.

   d) Do one of the following:

       0) Convey the Minimal Corresponding Source under the terms of this
       License, and the Corresponding Application Code in a form
       suitable for, and under terms that permit, the user to
       recombine or relink the Application with a modified version of
       the Linked Version to produce a modified Combined Work, in the
       manner specified by section 6 of the GNU GPL for conveying
       Corresponding Source.

       1) Use a suitable shared library mechanism for linking with the
       Library.  A suitable mechanism is one that (a) uses at run time
       a copy of the Library already present on the user's computer
       system, and (b) will operate properly with a modified version
       of the Library that is interface-compatible with the Linked
       Version.

   e) Provide Installation Information, but only if you would otherwise
   be required to provide such information under section 6 of the
   GNU GPL, and only to the extent that such information is
   necessary to install and execute a modified version of the
   Combined Work produced by recombining or relinking the
   Application with a modified version of the Linked Version. (If
   you use option 4d0, the Installation Information must accompany
   the Minimal Corresponding Source and Corresponding Application
   Code. If you use option 4d1, you must provide the Installation
   Information in the manner specified by section 6 of the GNU GPL
   for conveying Corresponding Source.)

  5. Combined Libraries.

  You may place library facilities that are a work based on the
Library side by side in a single library together with other library
facilities that are not Applications and are not covered by this
License, and convey such a combined library under terms of your
choice, if you do both of the following:

   a) Accompany the combined library with a copy of the same work based
   on the Library, uncombined with any other library facilities,
   conveyed under the terms of this License.

   b) Give prominent notice with the combined library that part of it
   is a work based on the Library, and explaining where to find the
   accompanying uncombined form of the same work.

  6. Revised Versions of the GNU Lesser General Public License.

  The Free Software Foundation may publish revised and/or new versions
of the GNU Lesser General Public License from time to time. Such new
versions will be similar in spirit to the present version, but may
differ in detail to address new problems or concerns.

  Each version is given a distinguishing version number. If the
Library as you received it specifies that a certain numbered version
of the GNU Lesser General Public License "or any later version"
applies to it, you have the option of following the terms and
conditions either of that published version or of any later version
published by the Free Software Foundation. If the Library as you
received it does not specify a version number of the GNU Lesser
General Public License, you may choose any version of the GNU Lesser
General Public License ever published by the Free Software Foundation.

  If the Library as you received it specifies that a proxy can decide
whether future versions of the GNU Lesser General Public License shall
apply, that proxy's public statement of acceptance of any version is
permanent authorization for you to choose that version for the
Library.
```
*/
