[package]
name = "ctb-formats-dctext"
edition = "2024"

[lib]
path="dctext.rs"
crate-type = ["lib"]

[dependencies]
ctb-utilities = { path = "../../utilities" }
ctb-formats-utf-8e-128 = { path = "../utf_8e_128" }
ctb-formats-utilities = { path = "../utilities" }
ctb-formats-eite = { path = "../eite" }
ctb-formats-math = { path = "../math" }
ctb-formats-unicode = { path = "../unicode" }
ctb-formats-utf8 = { path = "../utf8" }
ctb-storage-minimal = { path = "../../storage/minimal" }
malachite = "0.9.0"
const-default = { version = "1.0", features = ["derive"] }
clap = { version = "4.5.54", features = ["derive"] }

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
