// @generated by ctb-build-support::ipc_codegen
//
// Do not edit by hand.

#[ipc_client_trait]
#[async_trait]
#[expect(non_snake_case, reason = "generated trait methods matching formats naming conventions")]
pub trait FormatsClientTrait: crate::ipc::registry::IpcCaller + Send + Sync + std::fmt::Debug {
///  Decode bytes using the `utf_8e_128` format.
/// 
///  Returns `(value, used_len)` on success, or `None` if the bytes are not a
///  valid prefix for the encoding.
    async fn decode(&self, bytes: Vec < u8 >) -> Result<Option < (u128 , usize) >>;

///  Encode a u128 codepoint using the `utf_8e_128` format.
    async fn encode(&self, codepoint: u128) -> Result<Vec < u8 >>;

///  Decode bytes using the `utf_8e_128` format.
/// 
///  Returns `(value, used_len)` on success, or `None` if the bytes are not a
///  valid prefix for the encoding.
    async fn utf_8e_128__decode(&self, bytes: Vec < u8 >) -> Result<Option < (u128 , usize) >>;

///  Encode a u128 codepoint using the `utf_8e_128` format.
    async fn utf_8e_128__encode(&self, codepoint: u128) -> Result<Vec < u8 >>;

}
