// SPDX-License-Identifier: AGPL-3.0-or-later
/*
This file is part of Collective Toolbox, a database and document workspace and utilities.
Copyright (C) 2026 Collective Toolbox Developers
Contact: info@collectivetoolbox.com

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along
with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// IPC service for formats process.
//
// @generated by ctb-build-support::ipc_codegen
// Do not edit by hand.

#[ipc_client_trait]
#[async_trait]
#[expect(non_snake_case, reason = "generated trait methods matching formats naming conventions")]
pub trait FormatsClientTrait: crate::ipc::registry::IpcCaller + Send + Sync + std::fmt::Debug {
///  Decode bytes using the `utf_8e_128` format.
/// 
///  Returns `(value, used_len)` on success, or `None` if the bytes are not a
///  valid prefix for the encoding.
    async fn decode(&self, bytes: Vec < u8 >) -> Result<Option < (u128 , usize) >>;

///  Encode a u128 codepoint using the `utf_8e_128` format.
    async fn encode(&self, codepoint: u128) -> Result<Vec < u8 >>;

///  Decode bytes using the `utf_8e_128` format.
/// 
///  Returns `(value, used_len)` on success, or `None` if the bytes are not a
///  valid prefix for the encoding.
    async fn utf_8e_128__decode(&self, bytes: Vec < u8 >) -> Result<Option < (u128 , usize) >>;

///  Encode a u128 codepoint using the `utf_8e_128` format.
    async fn utf_8e_128__encode(&self, codepoint: u128) -> Result<Vec < u8 >>;

}
