// SPDX-License-Identifier: AGPL-3.0-or-later
/*
This file is part of Collective Toolbox, a database and document workspace and utilities.
Copyright (C) 2026 Collective Toolbox Developers
Contact: info@collectivetoolbox.com

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along
with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// IPC service for io process.
//
// @generated by ctb-build-support::ipc_codegen
// Do not edit by hand.

#[allow(unused_imports, reason = "Generated DTO imports may not be needed by all services")]
use std::collections::BTreeMap;
#[allow(unused_imports, reason = "Generated DTO imports may not be needed by all services")]
use std::net::{IpAddr, Ipv4Addr, Ipv6Addr};
#[allow(unused_imports, reason = "Generated DTO imports may not be needed by all services")]
use crate::format_id::FormatId;

///  Detailed snapshot of the current application and platform environment.
/// 
///  Serializes to a format where omitted fields assume default values on
///  deserialization, and unknown fields are preserved during roundtrips for
///  forward and backward extensibility.
#[derive(Debug, Clone, ::serde::Serialize, ::serde::Deserialize)]
pub struct EnvDescription {
    pub os: String,
    pub usize_width: u8,
    pub ctb_version: String,
    pub cwd: Option < String >,
    pub local_ips: Vec < IpAddr >,
    pub public_ips: Vec < IpAddr >,
    pub system_time_resolution_nanos: Option < u128 >,
    pub server_system_time_offset_nanos: Option < i128 >,
    pub is_release_build: bool,
    pub is_debug_build: bool,
    pub is_cargo_target_binary: bool,
    pub is_in_test: bool,
    pub is_branded_build: bool,
    pub is_official_signed_build: bool,
    pub is_cli_lightweight: bool,
    pub is_workspace: bool,
    pub is_workspace_main_process: bool,
    pub is_service_subprocess: bool,
    pub is_official_public_website: bool,
    pub is_public_website: bool,
    pub is_local: bool,
    pub additional_support: Vec < FormatId >,
    pub extra: BTreeMap < String , serde_json :: Value >,
}

