// @generated by ctb-build-support::ipc_codegen
//
// Do not edit by hand.

#[ipc_client_trait]
#[async_trait]
pub trait NetworkClientTrait: crate::ipc::registry::IpcCaller + Send + Sync + std::fmt::Debug {
///  Echo bytes back.
    async fn echo(&self, bytes: Vec < u8 >) -> Result<Vec < u8 >>;

///  Fetch bytes from a URL.
    async fn fetch(&self, url: & str) -> Result<Vec < u8 >>;

///  Read a file into memory.
    async fn read_file(&self, path: & str) -> Result<Vec < u8 >>;

}
