// SPDX-License-Identifier: AGPL-3.0-or-later
/*
This file is part of Collective Toolbox, a database and document workspace and utilities.
Copyright (C) 2026 Collective Toolbox Developers
Contact: info@collectivetoolbox.com

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along
with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// IPC service for network process.
//
// @generated by ctb-build-support::ipc_codegen
// Do not edit by hand.

#[ipc_client_trait]
#[async_trait]
pub trait NetworkClientTrait: crate::ipc::registry::IpcCaller + Send + Sync + std::fmt::Debug {
///  Echo bytes back.
    async fn echo(&self, bytes: Vec < u8 >) -> Result<Vec < u8 >>;

///  Fetch bytes from a URL.
    async fn fetch(&self, url: & str) -> Result<Vec < u8 >>;

///  Read a file into memory.
    async fn read_file(&self, path: & str) -> Result<Vec < u8 >>;

}
