// @generated by ctb-build-support::ipc_codegen
//
// Do not edit by hand.

///  Render mode for the renderer service.
/// 
///  This type is marked as an IPC DTO source so `ctb-utilities` can generate a
///  dependency-free mirror for IPC service traits.
#[derive(Debug, Clone, Copy, PartialEq, Eq, ::serde::Serialize, ::serde::Deserialize)]
pub enum RenderMode {
///  Render everything immediately without interactive features.
    Immediate,
///  Render with interactive features enabled.
    Interactive,
}

///  Render settings for the renderer service.
/// 
///  This is marked as an IPC DTO source so `ctb-utilities` can generate a
///  dependency-free mirror for IPC service traits.
#[derive(Debug, Clone, ::serde::Serialize, ::serde::Deserialize)]
pub struct RenderSettings {
///  The rendering mode.
    pub mode: RenderMode,
///  The rendering target.
    pub target: RenderTarget,
}

///  Render target for the renderer service.
/// 
///  This is marked as an IPC DTO source so `ctb-utilities` can generate a
///  dependency-free mirror for IPC service traits.
#[derive(Debug, Clone, Copy, PartialEq, Eq, ::serde::Serialize, ::serde::Deserialize)]
pub enum RenderTarget {
///  Character-based output similar to a teletype (plain text).
    Teletype,
///  Video terminal with cursor control and escape sequences.
    Videoterminal,
///  Web-based output (HTML/CSS/JS).
    Web,
///  Raster graphics (bitmap images).
    Raster,
///  Vector graphics (SVG, PDF).
    Vector,
///  Print-ready output.
    Print,
}

