// @generated by ctb-build-support::ipc_codegen
//
// Do not edit by hand.

#[ipc_client_trait]
#[async_trait]
pub trait RendererClientTrait: crate::ipc::registry::IpcCaller + Send + Sync + std::fmt::Debug {
///  Render the provided document string according to the provided settings.
///  Stub for now.
    async fn render_from_string(&self, #[ipc(shm)] document: & str, settings: RenderSettings) -> Result<String>;

///  Test helper that echoes the document 3 times.
    async fn test_echo_3x(&self, #[ipc(shm)] document: & str) -> Result<String>;

///  Prepend a string to the document and return the result.
    async fn test_prepend(&self, #[ipc(shm)] document: & str, prepend: & str) -> Result<String>;

}
