// @generated by ctb-build-support::ipc_codegen
//
// Do not edit by hand.

#[derive(Debug, Clone, ::serde::Serialize, ::serde::Deserialize)]
pub struct Node {
    pub id: u128,
    pub graph_id: u128,
    pub node_type: NodeType,
    pub data: Vec < u8 >,
    pub checksum: Option < Vec < u8 > >,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, ::serde::Serialize, ::serde::Deserialize)]
pub enum NodeType {
    Data,
    Statements,
    System,
}

#[derive(Debug, Clone, ::serde::Serialize, ::serde::Deserialize)]
pub struct TableRow {
    pub columns: Vec < String >,
    pub values: Vec < Vec < String > >,
    pub page: u32,
    pub total_pages: u32,
    pub total_rows: u32,
}

#[derive(Debug, Clone, ::serde::Serialize, ::serde::Deserialize)]
pub struct UserDto {
    pub id: u64,
    pub username: String,
    pub uuid: Vec < u8 >,
    pub auth: Option < String >,
    pub display_name: Option < Vec < u8 > >,
    pub picture: Option < Vec < u8 > >,
    pub key_encryption_key_params: Option < Vec < u8 > >,
    pub wrapped_dek: Option < Vec < u8 > >,
    pub pubkey: Option < Vec < u8 > >,
    pub subscription_expiry: Option < u64 >,
    pub token_quota: Option < u64 >,
    pub remote_status: Option < String >,
}

