// @generated by ctb-build-support::ipc_codegen
//
// Do not edit by hand.

#[ipc_client_trait]
#[async_trait]
pub trait StorageClientTrait: crate::ipc::registry::IpcCaller + Send + Sync + std::fmt::Debug {
///  [SERVER-SIDE] Allocates a block of 10,000 unique IDs for the given graph.
    async fn allocate_next_remote_range(&self, graph_id: u128) -> Result<u64>;

///  Allocate the next system ID in the global graph layout.
    async fn allocate_next_system_id(&self, session_token: & str) -> Result<u128>;

    async fn create_user(&self, user: UserDto) -> Result<()>;

///  Create user and session: creates a new user, registers session, and returns session token.
    async fn create_user_and_session(&self, username: & str, password_bytes: Vec < u8 >, duration_secs: u64) -> Result<String>;

///  [CLIENT-SIDE] Deletes a spent local token from the user's database.
    async fn delete_local_token(&self, user_id: u64, key: u64) -> Result<()>;

    async fn delete_user_by_id(&self, id: u64) -> Result<()>;

///  Deregister a user's decrypted DEK and close/clear their database connections.
    async fn deregister_user(&self, user_id: u64) -> Result<()>;

    async fn get_all_user_ids(&self) -> Result<Vec < u64 >>;

///  Get raw columns and row values for a table, formatted specifically for display
///  in the Web UI (e.g. converting node IDs/checksums to string, handling blobs,
///  and truncation).
/// 
///  This is used by the Web UI.
    async fn get_formatted_table_data(&self, session_token: & str, db_name: & str, table_name: & str, page: u32) -> Result<:: ctb_utilities :: ipc :: service_traits :: storage :: TableRow>;

///  [CLIENT-SIDE] Retrieves the reserved local ID range for a graph from the user's database.
    async fn get_local_id_range(&self, user_id: u64, graph_id: u128) -> Result<Option < Vec < u8 > >>;

///  [CLIENT-SIDE] Fetches all unspent local blind tokens from the user's database.
    async fn get_local_tokens(&self, user_id: u64) -> Result<Vec < (u64 , String) >>;

///  Retrieve a node's raw data by ID.
    async fn get_node(&self, session_token: & str, graph_id: u128, id: u128) -> Result<Option < Vec < u8 > >>;

///  Retrieve a node's full data by ID.
    async fn get_node_dto(&self, session_token: & str, graph_id: u128, id: u128) -> Result<Option < :: ctb_utilities :: ipc :: service_traits :: storage :: Node >>;

///  [SERVER-SIDE] Retrieves an encrypted graph/node chunk payload from the server.
    async fn get_sync_chunk(&self, hash: & str) -> Result<Option < Vec < u8 > >>;

    async fn get_user_by_id(&self, id: u64) -> Result<Option < :: ctb_utilities :: ipc :: service_traits :: storage :: UserDto >>;

    async fn get_user_by_name(&self, name: & str) -> Result<Option < :: ctb_utilities :: ipc :: service_traits :: storage :: UserDto >>;

    async fn get_voprf_key(&self) -> Result<Option < Vec < u8 > >>;

///  Atomically increment and get next user ID using a SQLite transaction.
    async fn increment_and_get_user_id(&self) -> Result<u64>;

///  Insert a node into the user's graph database.
    async fn insert_node(&self, session_token: & str, graph_id: u128, node_type: NodeType, data: & [u8]) -> Result<u128>;

///  Invalidate a session.
    async fn invalidate_session(&self, token: & str) -> Result<()>;

///  [SERVER-SIDE] Checks if a blind token's serial hex is marked as spent.
    async fn is_token_spent(&self, serial_hex: & str) -> Result<bool>;

///  List all database names/paths available to the user.
    async fn list_databases(&self, session_token: & str) -> Result<Vec < String >>;

///  List all nodes for a user.
    async fn list_nodes(&self, session_token: & str) -> Result<Vec < :: ctb_utilities :: ipc :: service_traits :: storage :: Node >>;

///  List all table names in the specified database.
    async fn list_tables(&self, session_token: & str, db_name: & str) -> Result<Vec < String >>;

///  Login user: verifies password, derives keys, registers session, and returns session token.
    async fn login_user(&self, username: & str, password_bytes: Vec < u8 >, duration_secs: u64) -> Result<String>;

///  Publish a packaged node to the global graph.
    async fn publish_packaged_node_to_global(&self, session_token: & str, package: Vec < u8 >, target_id: Option < u128 >) -> Result<u128>;

///  Refresh an active session.
    async fn refresh_session(&self, token: & str, duration_secs: u64) -> Result<()>;

    async fn rename_user(&self, id: u64, new_username: & str) -> Result<()>;

///  [CLIENT-SIDE] Saves the reserved local ID range for a graph in the user's database.
    async fn save_local_id_range(&self, user_id: u64, graph_id: u128, range_bytes: Vec < u8 >) -> Result<()>;

///  [CLIENT-SIDE] Stores a newly finalized blind token locally in the user's database.
    async fn save_local_token(&self, user_id: u64, key: u64, token: & str) -> Result<()>;

///  [SERVER-SIDE] Stores an encrypted graph/node chunk payload on the server.
    async fn save_sync_chunk(&self, hash: & str, data: Vec < u8 >, expiry: u64) -> Result<()>;

    async fn save_voprf_key(&self, key: Vec < u8 >) -> Result<()>;

///  [SERVER-SIDE] Marks a blind token as spent to prevent double-spending.
    async fn spend_token(&self, serial_hex: & str) -> Result<()>;

///  Update the node data of an existing node in the database.
    async fn update_node_data(&self, session_token: & str, graph_id: u128, node_id: u128, data: Vec < u8 >) -> Result<()>;

///  Update the node type of an existing node in the database.
    async fn update_node_type(&self, session_token: & str, graph_id: u128, node_id: u128, node_type: NodeType) -> Result<()>;

    async fn update_user(&self, user: UserDto) -> Result<()>;

///  Validate a session and return the user ID.
    async fn validate_session(&self, token: & str) -> Result<Option < u64 >>;

}
