#!/usr/bin/env bash

set -euo pipefail

# Usage: ./scripts/import-kaitai-formats path/to/kaitai_struct_formats/
# Get updated formats library from https://github.com/kaitai-io/kaitai_struct_formats

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

cargo run \
    --manifest-path "${REPO_ROOT}/src/formats/kaitai/Cargo.toml" \
    --bin import-kaitai-formats \
    -- "$@"
