#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This file is part of Collective Toolbox, a database and document workspace and utilities.
# Copyright (C) 2026 Collective Toolbox Developers
# Contact: info@collectivetoolbox.com
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program.  If not, see <https://www.gnu.org/licenses/>.
set -euo pipefail

cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/.." || exit 1

# Search assets/views/ recursively for utility font-* or text-* classes in Handlebars templates
# Excluded: text-start, text-end, text-center, text-justify
# Matches are outputted, and the script exits with 1 if any match is found.
if grep -P -r '(?<=^|[\s"'\'':])(?!(?:text-start|text-end|text-center|text-justify)\b)(?:font|text)-[a-zA-Z0-9_-]+' assets/views/; then
    echo ""
    echo "Non-layout EncreCSS classes detected. Font family and color should be"
    echo "omitted so they can be managed by the theming system. Monospace/small/bold/large/headings"
    echo "should use semantic HTML, with styling managed by tag-level CSS. Particularly"
    echo "weird cases of styling may need a dedicated CSS class, but that's a last resort as it won't be presented to CLI users anyway."
    exit 1
fi
