#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This file is part of Collective Toolbox, a database and document workspace and utilities.
# Copyright (C) 2026 Collective Toolbox Developers
# Contact: info@collectivetoolbox.com
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program.  If not, see <https://www.gnu.org/licenses/>.
# For some reason rustup seems to lose my targets every time I update.
set -euo pipefail

cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/.." || exit 1

default='1.92'
versions=( '1.90' '1.92' )
targets=( x86_64-pc-windows-gnu x86_64-unknown-linux-musl i586-unknown-linux-musl x86_64-unknown-linux-gnu i586-unknown-linux-gnu )

for target in "${targets[@]}"; do
    for version in "${versions[@]}"; do
        rustup target add "$target" --toolchain "$version"
    done
done

rustup default "$default"
