#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This file is part of Collective Toolbox, a database and document workspace and utilities.
# Copyright (C) 2026 Collective Toolbox Developers
# Contact: info@collectivetoolbox.com
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program.  If not, see <https://www.gnu.org/licenses/>.
set -euxo pipefail

cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/.." || exit 1


trap 'mv src/installer/locales/en-US.ftl.bak src/installer/locales/en-US.ftl' ERR

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd "$SCRIPT_DIR/.." || exit 1

# Moving it won't work; it has to be copied because it will error with "Downloaded translations don't match the current project configuration." if the source file does not exist.
cp src/installer/locales/en-US.ftl src/installer/locales/en-US.ftl.bak
crowdin download
mv src/installer/locales/en-US.ftl.bak src/installer/locales/en-US.ftl

# In all files in src/installer/locales that aren't en-US.ftl, delete lines beginning with
# `# English (US) - Primary translation file for`
# and
# `# This is the reference file`.

find src/installer/locales -type f ! -name "en-US.ftl" -exec sed -i '/^# English (US) - Primary translation file for/d' {} + -exec sed -i '/^# This is the reference file/d' {} +
