#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This file is part of Collective Toolbox, a database and document workspace and utilities.
# Copyright (C) 2026 Collective Toolbox Developers
# Contact: info@collectivetoolbox.com
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program.  If not, see <https://www.gnu.org/licenses/>.
set -euxo pipefail

cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/.." || exit 1


cd vendor/ctb-vendored || exit 1
cargo vendor --frozen --manifest-path ../../Cargo.toml
git add . || true
git commit -m 'deps: Automatically update dependencies' || true
find vendor -name '*.gitignore' -exec mv {} {}-2528979c-1cdc-49a3-83ec-a1cdea2ed741.moved \;
git add . || true
git commit -m 'deps: Automatically update dependencies (reset .gitignores)' || true
git add . || true
git commit -m 'deps: Automatically update dependencies (post resetting .gitignores)' || true
cd .. || exit 1
git add ctb-vendored || true
git commit -m 'deps: Automatically update dependencies' || true
