[package]
name = "ctb-formats-dc-data"
edition = "2024"

[lib]
path="dc_data.rs"
crate-type = ["lib"]

[[bin]]
name = "validate-data-tables"
path = "bin/validate_data_tables.rs"

[dependencies]
ctb-utilities = { path = "../../utilities" }
ctb-formats-utilities = { path = "../utilities" }
ctb-formats-unicode = { path = "../unicode" }
ctb-storage-minimal = { path = "../../storage/minimal" }
include_dir = { version = "0.7.4", features = ["glob"] }
regex = "1.12.2"
tempfile = "3.24.0"
csv = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lints]
workspace = true

