[package]
name = "ctb-formats-kaitai"
edition = "2024"

[lib]
path="kaitai.rs"
crate-type = ["lib"]

[[bin]]
name = "import-kaitai-formats"
path = "bin/import_formats.rs"

[[bin]]
name = "generate-kaitai-tests"
path = "bin/generate_tests.rs"

[dependencies]
ctb-utilities = { path = "../../utilities" }
ctb-formats-utilities = { path = "../utilities" }
include_dir = { version = "0.7.4", features = ["glob"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
indexmap = { version = "2.14.0", features = ["serde"] }
clap = { version = "4.5.60", features = ["derive"] }
walkdir = "2.5.0"
ctb-formats-encoding = { path = "../encoding" }
ctb-formats-rust = { path = "../rust" }
encoding_rs = "0.8.35"
flate2 = "1.0.31"
unicode-segmentation = "1.12.0"
kaitai = { path = "runtime" }

[build-dependencies]
anyhow = "1.0.100"
ctb-build-support = { path = "../../build_support" }
ctb-formats-rust = { path = "../rust" }
indexmap = { version = "2.14.0", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
walkdir = "2.5.0"

[lints]
workspace = true

