// SPDX-License-Identifier: AGPL-3.0-or-later
/*
This file is part of Collective Toolbox, a database and document workspace and utilities.
Copyright (C) 2026 Collective Toolbox Developers
Contact: info@collectivetoolbox.com

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along
with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

//! Generated Kaitai format modules.

// @generated by ctb-formats-kaitai::codegen

#[path = "generated/archive.generated.rs"]
pub mod archive;
pub use archive::*;
#[path = "generated/cad.generated.rs"]
pub mod cad;
pub use cad::*;
#[path = "generated/common.generated.rs"]
pub mod common;
pub use common::*;
#[path = "generated/database.generated.rs"]
pub mod database;
pub use database::*;
#[path = "generated/executable.generated.rs"]
pub mod executable;
pub use executable::*;
#[path = "generated/filesystem.generated.rs"]
pub mod filesystem;
pub use filesystem::*;
#[path = "generated/firmware.generated.rs"]
pub mod firmware;
pub use firmware::*;
#[path = "generated/font.generated.rs"]
pub mod font;
pub use font::*;
#[path = "generated/game.generated.rs"]
pub mod game;
pub use game::*;
#[path = "generated/geospatial.generated.rs"]
pub mod geospatial;
pub use geospatial::*;
#[path = "generated/hardware.generated.rs"]
pub mod hardware;
pub use hardware::*;
#[path = "generated/image.generated.rs"]
pub mod image;
pub use image::*;
#[path = "generated/log.generated.rs"]
pub mod log;
pub use log::*;
#[path = "generated/machine_code.generated.rs"]
pub mod machine_code;
pub use machine_code::*;
#[path = "generated/media.generated.rs"]
pub mod media;
pub use media::*;
#[path = "generated/network.generated.rs"]
pub mod network;
pub use network::*;
#[path = "generated/scientific.generated.rs"]
pub mod scientific;
pub use scientific::*;
#[path = "generated/security.generated.rs"]
pub mod security;
pub use security::*;
#[path = "generated/serialization.generated.rs"]
pub mod serialization;
pub use serialization::*;
#[path = "generated/windows.generated.rs"]
pub mod windows;
pub use windows::*;
