[package]
name = "ctb-formats-compression"
edition = "2024"

[lib]
path="compression.rs"
crate-type = ["lib"]

[dependencies]
ctb-utilities = { path = "../../utilities" }
ctb-formats-compression-bzip = { path = "./bzip" }
ctb-formats-compression-compact = { path = "./compact" }
ctb-formats-compression-compress = { path = "./compress" }
ctb-formats-compression-pack = { path = "./pack" }
ctb-formats-compression-sco-compress = { path = "./sco_compress" }
ctb-formats-compression-libraries = { path = "./libraries" }
ctb-formats-utilities = { path = "../utilities" }
ctb-formats-detection = { path = "../detection" }
ctb-io-file = { path = "../../io/file" }

include_dir = { version = "0.7.4", features = ["glob"] }
clap = { version = "4.5.54", features = ["derive"] }

[lints]
workspace = true


