[package]
name = "ctb-formats-compression"
edition = "2024"

[lib]
path="compression.rs"
crate-type = ["lib"]

[dependencies]
ctb-utilities = { path = "../../utilities" }
ctb-formats-utilities = { path = "../utilities" }

brotli = "8.0.3"
flate2 = "1.1.9"
include_dir = { version = "0.7.4", features = ["glob"] }
bzip2 = "0.6.1"
lz4_flex = "0.14.0"
lzma-rust2 = "0.18.1"
lzokay-native = "0.1.0"
zstd = "0.13.3"
clap = { version = "4.5.54", features = ["derive"] }

[lints]
workspace = true


