// SPDX-License-Identifier: AGPL-3.0-or-later
/*
This file is part of Collective Toolbox, a database and document workspace and utilities.
Copyright (C) 2026 Collective Toolbox Developers
Contact: info@collectivetoolbox.com

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along
with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
// @generated by ctb-build-support::compression_codegen from format category data tables.

/// Ordered list of all compression formats supported by this crate.
pub const SUPPORTED: &'static [FormatId] = &[
    FormatId::Brotli,
    FormatId::Gzip,
    FormatId::Deflate,
    FormatId::Zlib,
    FormatId::Bzip2,
    FormatId::Bzip,
    FormatId::Zstd,
    FormatId::Lzip,
    FormatId::Xz,
    FormatId::ScoCompress,
    FormatId::CompressLzw,
    FormatId::CompressLzw1,
    FormatId::CompressLzw16,
    FormatId::CompressLzw2,
    FormatId::Pack,
    FormatId::OldPack,
    FormatId::Compact,
    FormatId::Freeze2,
    FormatId::Freeze1,
    FormatId::Rzip,
    FormatId::Lz4,
    FormatId::Lzo,
    FormatId::Lzma,
    FormatId::Lzma2,
    FormatId::Szip,
    FormatId::Szip111,
];

/// Returns true if the given `FormatId` is supported for compression/decompression by this crate.
#[must_use]
pub const fn is_supported(format: FormatId) -> bool {
    matches!(
        format,
        FormatId::Brotli
            | FormatId::Gzip
            | FormatId::Deflate
            | FormatId::Zlib
            | FormatId::Bzip2
            | FormatId::Bzip
            | FormatId::Zstd
            | FormatId::Lzip
            | FormatId::Xz
            | FormatId::ScoCompress
            | FormatId::CompressLzw
            | FormatId::CompressLzw1
            | FormatId::CompressLzw16
            | FormatId::CompressLzw2
            | FormatId::Pack
            | FormatId::OldPack
            | FormatId::Compact
            | FormatId::Freeze2
            | FormatId::Freeze1
            | FormatId::Rzip
            | FormatId::Lz4
            | FormatId::Lzo
            | FormatId::Lzma
            | FormatId::Lzma2
            | FormatId::Szip
            | FormatId::Szip111
    )
}
