[package]
name = "ctb-workspace-x11-client"
edition = "2024"

[lib]
path="x11_client.rs"
crate-type = ["lib"]

[dependencies]
ctb-utilities = { path = "../../utilities" }
ctb-storage-minimal = { path = "../../storage/minimal" }

yaxi = { path = "../../../vendor/yaxi", features = [ "clipboard" ] }

[lints]
workspace = true
