// @generated by ctb-formats-kaitai::build

#[path = "generated/test_bcd_user_type_be.generated.rs"]
mod test_bcd_user_type_be;
#[path = "generated/test_bcd_user_type_le.generated.rs"]
mod test_bcd_user_type_le;
#[path = "generated/test_bits_byte_aligned.generated.rs"]
mod test_bits_byte_aligned;
#[path = "generated/test_bits_byte_aligned_eof_be.generated.rs"]
mod test_bits_byte_aligned_eof_be;
#[path = "generated/test_bits_byte_aligned_eof_le.generated.rs"]
mod test_bits_byte_aligned_eof_le;
#[path = "generated/test_bits_enum.generated.rs"]
mod test_bits_enum;
#[path = "generated/test_bits_seq_endian_combo.generated.rs"]
mod test_bits_seq_endian_combo;
#[path = "generated/test_bits_shift_by_b32_le.generated.rs"]
mod test_bits_shift_by_b32_le;
#[path = "generated/test_bits_shift_by_b64_le.generated.rs"]
mod test_bits_shift_by_b64_le;
#[path = "generated/test_bits_signed_res_b32_be.generated.rs"]
mod test_bits_signed_res_b32_be;
#[path = "generated/test_bits_signed_res_b32_le.generated.rs"]
mod test_bits_signed_res_b32_le;
#[path = "generated/test_bits_signed_shift_b32_le.generated.rs"]
mod test_bits_signed_shift_b32_le;
#[path = "generated/test_bits_signed_shift_b64_le.generated.rs"]
mod test_bits_signed_shift_b64_le;
#[path = "generated/test_bits_simple.generated.rs"]
mod test_bits_simple;
#[path = "generated/test_bits_simple_le.generated.rs"]
mod test_bits_simple_le;
#[path = "generated/test_bits_unaligned_b32_be.generated.rs"]
mod test_bits_unaligned_b32_be;
#[path = "generated/test_bits_unaligned_b32_le.generated.rs"]
mod test_bits_unaligned_b32_le;
#[path = "generated/test_bits_unaligned_b64_be.generated.rs"]
mod test_bits_unaligned_b64_be;
#[path = "generated/test_bits_unaligned_b64_le.generated.rs"]
mod test_bits_unaligned_b64_le;
#[path = "generated/test_buffered_struct.generated.rs"]
mod test_buffered_struct;
#[path = "generated/test_bytes_eos_pad_term.generated.rs"]
mod test_bytes_eos_pad_term;
#[path = "generated/test_bytes_pad_term.generated.rs"]
mod test_bytes_pad_term;
#[path = "generated/test_bytes_pad_term_empty.generated.rs"]
mod test_bytes_pad_term_empty;
#[path = "generated/test_bytes_pad_term_equal.generated.rs"]
mod test_bytes_pad_term_equal;
#[path = "generated/test_bytes_pad_term_roundtrip.generated.rs"]
mod test_bytes_pad_term_roundtrip;
#[path = "generated/test_bytes_pad_term_zero_size.generated.rs"]
mod test_bytes_pad_term_zero_size;
#[path = "generated/test_combine_bool.generated.rs"]
mod test_combine_bool;
#[path = "generated/test_combine_enum.generated.rs"]
mod test_combine_enum;
#[path = "generated/test_debug_0.generated.rs"]
mod test_debug_0;
#[path = "generated/test_debug_array_user.generated.rs"]
mod test_debug_array_user;
#[path = "generated/test_debug_array_user_current_excluded.generated.rs"]
mod test_debug_array_user_current_excluded;
#[path = "generated/test_debug_array_user_eof_exception.generated.rs"]
mod test_debug_array_user_eof_exception;
#[path = "generated/test_debug_enum_name.generated.rs"]
mod test_debug_enum_name;
#[path = "generated/test_default_big_endian.generated.rs"]
mod test_default_big_endian;
#[path = "generated/test_default_bit_endian_mod.generated.rs"]
mod test_default_bit_endian_mod;
#[path = "generated/test_default_endian_mod.generated.rs"]
mod test_default_endian_mod;
#[path = "generated/test_docstrings.generated.rs"]
mod test_docstrings;
#[path = "generated/test_docstrings_docref.generated.rs"]
mod test_docstrings_docref;
#[path = "generated/test_docstrings_docref_multi.generated.rs"]
mod test_docstrings_docref_multi;
#[path = "generated/test_enum_0.generated.rs"]
mod test_enum_0;
#[path = "generated/test_enum_1.generated.rs"]
mod test_enum_1;
#[path = "generated/test_enum_deep.generated.rs"]
mod test_enum_deep;
#[path = "generated/test_enum_fancy.generated.rs"]
mod test_enum_fancy;
#[path = "generated/test_enum_if.generated.rs"]
mod test_enum_if;
#[path = "generated/test_enum_import_seq.generated.rs"]
mod test_enum_import_seq;
#[path = "generated/test_enum_int_range_s.generated.rs"]
mod test_enum_int_range_s;
#[path = "generated/test_enum_int_range_u.generated.rs"]
mod test_enum_int_range_u;
#[path = "generated/test_enum_long_range_s.generated.rs"]
mod test_enum_long_range_s;
#[path = "generated/test_enum_negative.generated.rs"]
mod test_enum_negative;
#[path = "generated/test_enum_of_value_inst.generated.rs"]
mod test_enum_of_value_inst;
#[path = "generated/test_enum_to_i.generated.rs"]
mod test_enum_to_i;
#[path = "generated/test_eof_exception_bits_be.generated.rs"]
mod test_eof_exception_bits_be;
#[path = "generated/test_eof_exception_bits_be2.generated.rs"]
mod test_eof_exception_bits_be2;
#[path = "generated/test_eof_exception_bits_le.generated.rs"]
mod test_eof_exception_bits_le;
#[path = "generated/test_eof_exception_bits_le2.generated.rs"]
mod test_eof_exception_bits_le2;
#[path = "generated/test_eof_exception_bytes.generated.rs"]
mod test_eof_exception_bytes;
#[path = "generated/test_eof_exception_sized.generated.rs"]
mod test_eof_exception_sized;
#[path = "generated/test_eof_exception_switch_user.generated.rs"]
mod test_eof_exception_switch_user;
#[path = "generated/test_eof_exception_u4.generated.rs"]
mod test_eof_exception_u4;
#[path = "generated/test_eos_exception_bytes.generated.rs"]
mod test_eos_exception_bytes;
#[path = "generated/test_eos_exception_sized.generated.rs"]
mod test_eos_exception_sized;
#[path = "generated/test_eos_exception_u4.generated.rs"]
mod test_eos_exception_u4;
#[path = "generated/test_expr_0.generated.rs"]
mod test_expr_0;
#[path = "generated/test_expr_1.generated.rs"]
mod test_expr_1;
#[path = "generated/test_expr_2.generated.rs"]
mod test_expr_2;
#[path = "generated/test_expr_3.generated.rs"]
mod test_expr_3;
#[path = "generated/test_expr_bytes_non_literal.generated.rs"]
mod test_expr_bytes_non_literal;
#[path = "generated/test_expr_bytes_ops.generated.rs"]
mod test_expr_bytes_ops;
#[path = "generated/test_expr_enum.generated.rs"]
mod test_expr_enum;
#[path = "generated/test_expr_if_int_eq.generated.rs"]
mod test_expr_if_int_eq;
#[path = "generated/test_expr_if_int_ops.generated.rs"]
mod test_expr_if_int_ops;
#[path = "generated/test_expr_int_div.generated.rs"]
mod test_expr_int_div;
#[path = "generated/test_expr_io_pos_bits.generated.rs"]
mod test_expr_io_pos_bits;
#[path = "generated/test_expr_mod.generated.rs"]
mod test_expr_mod;
#[path = "generated/test_expr_sizeof_type_0.generated.rs"]
mod test_expr_sizeof_type_0;
#[path = "generated/test_expr_sizeof_type_1.generated.rs"]
mod test_expr_sizeof_type_1;
#[path = "generated/test_expr_sizeof_value_0.generated.rs"]
mod test_expr_sizeof_value_0;
#[path = "generated/test_expr_sizeof_value_sized.generated.rs"]
mod test_expr_sizeof_value_sized;
#[path = "generated/test_expr_str_encodings.generated.rs"]
mod test_expr_str_encodings;
#[path = "generated/test_expr_to_i_trailing.generated.rs"]
mod test_expr_to_i_trailing;
#[path = "generated/test_fixed_contents.generated.rs"]
mod test_fixed_contents;
#[path = "generated/test_fixed_struct.generated.rs"]
mod test_fixed_struct;
#[path = "generated/test_float_to_i.generated.rs"]
mod test_float_to_i;
#[path = "generated/test_floating_points.generated.rs"]
mod test_floating_points;
#[path = "generated/test_hello_world.generated.rs"]
mod test_hello_world;
#[path = "generated/test_if_struct.generated.rs"]
mod test_if_struct;
#[path = "generated/test_imports0.generated.rs"]
mod test_imports0;
#[path = "generated/test_imports_abs_abs.generated.rs"]
mod test_imports_abs_abs;
#[path = "generated/test_imports_abs_rel.generated.rs"]
mod test_imports_abs_rel;
#[path = "generated/test_imports_circular_a.generated.rs"]
mod test_imports_circular_a;
#[path = "generated/test_imports_rel_1.generated.rs"]
mod test_imports_rel_1;
#[path = "generated/test_index_sizes.generated.rs"]
mod test_index_sizes;
#[path = "generated/test_index_to_param_eos.generated.rs"]
mod test_index_to_param_eos;
#[path = "generated/test_index_to_param_expr.generated.rs"]
mod test_index_to_param_expr;
#[path = "generated/test_index_to_param_until.generated.rs"]
mod test_index_to_param_until;
#[path = "generated/test_instance_in_repeat_expr.generated.rs"]
mod test_instance_in_repeat_expr;
#[path = "generated/test_instance_in_repeat_until.generated.rs"]
mod test_instance_in_repeat_until;
#[path = "generated/test_instance_in_sized.generated.rs"]
mod test_instance_in_sized;
#[path = "generated/test_instance_io_user.generated.rs"]
mod test_instance_io_user;
#[path = "generated/test_instance_std.generated.rs"]
mod test_instance_std;
#[path = "generated/test_instance_std_array.generated.rs"]
mod test_instance_std_array;
#[path = "generated/test_instance_user_array.generated.rs"]
mod test_instance_user_array;
#[path = "generated/test_integers.generated.rs"]
mod test_integers;
#[path = "generated/test_integers_double_overflow.generated.rs"]
mod test_integers_double_overflow;
#[path = "generated/test_integers_min_max.generated.rs"]
mod test_integers_min_max;
#[path = "generated/test_js_signed_right_shift.generated.rs"]
mod test_js_signed_right_shift;
#[path = "generated/test_meta_tags.generated.rs"]
mod test_meta_tags;
#[path = "generated/test_meta_xref.generated.rs"]
mod test_meta_xref;
#[path = "generated/test_multiple_use.generated.rs"]
mod test_multiple_use;
#[path = "generated/test_name_clash_import_vs_inst.generated.rs"]
mod test_name_clash_import_vs_inst;
#[path = "generated/test_nav_parent.generated.rs"]
mod test_nav_parent;
#[path = "generated/test_nav_parent_false2.generated.rs"]
mod test_nav_parent_false2;
#[path = "generated/test_nav_parent_override.generated.rs"]
mod test_nav_parent_override;
#[path = "generated/test_nav_parent_vs_value_inst.generated.rs"]
mod test_nav_parent_vs_value_inst;
#[path = "generated/test_nav_root.generated.rs"]
mod test_nav_root;
#[path = "generated/test_nav_root_recursive.generated.rs"]
mod test_nav_root_recursive;
#[path = "generated/test_nested_same_name.generated.rs"]
mod test_nested_same_name;
#[path = "generated/test_nested_same_name2.generated.rs"]
mod test_nested_same_name2;
#[path = "generated/test_nested_types.generated.rs"]
mod test_nested_types;
#[path = "generated/test_nested_types2.generated.rs"]
mod test_nested_types2;
#[path = "generated/test_nested_types3.generated.rs"]
mod test_nested_types3;
#[path = "generated/test_non_standard.generated.rs"]
mod test_non_standard;
#[path = "generated/test_optional_id.generated.rs"]
mod test_optional_id;
#[path = "generated/test_params_enum.generated.rs"]
mod test_params_enum;
#[path = "generated/test_params_pass_bool.generated.rs"]
mod test_params_pass_bool;
#[path = "generated/test_params_pass_io.generated.rs"]
mod test_params_pass_io;
#[path = "generated/test_params_pass_usertype.generated.rs"]
mod test_params_pass_usertype;
#[path = "generated/test_position_abs.generated.rs"]
mod test_position_abs;
#[path = "generated/test_position_in_seq.generated.rs"]
mod test_position_in_seq;
#[path = "generated/test_process_bytes_pad_term.generated.rs"]
mod test_process_bytes_pad_term;
#[path = "generated/test_process_coerce_bytes.generated.rs"]
mod test_process_coerce_bytes;
#[path = "generated/test_process_coerce_usertype1.generated.rs"]
mod test_process_coerce_usertype1;
#[path = "generated/test_process_coerce_usertype2.generated.rs"]
mod test_process_coerce_usertype2;
#[path = "generated/test_process_custom.generated.rs"]
mod test_process_custom;
#[path = "generated/test_process_custom_no_args.generated.rs"]
mod test_process_custom_no_args;
#[path = "generated/test_process_repeat_bytes.generated.rs"]
mod test_process_repeat_bytes;
#[path = "generated/test_process_repeat_usertype.generated.rs"]
mod test_process_repeat_usertype;
#[path = "generated/test_process_repeat_usertype_dynarg_custom.generated.rs"]
mod test_process_repeat_usertype_dynarg_custom;
#[path = "generated/test_process_repeat_usertype_dynarg_rotate.generated.rs"]
mod test_process_repeat_usertype_dynarg_rotate;
#[path = "generated/test_process_repeat_usertype_dynarg_xor.generated.rs"]
mod test_process_repeat_usertype_dynarg_xor;
#[path = "generated/test_process_rotate.generated.rs"]
mod test_process_rotate;
#[path = "generated/test_process_struct_pad_term.generated.rs"]
mod test_process_struct_pad_term;
#[path = "generated/test_process_term_struct.generated.rs"]
mod test_process_term_struct;
#[path = "generated/test_process_to_user.generated.rs"]
mod test_process_to_user;
#[path = "generated/test_process_xor4_const.generated.rs"]
mod test_process_xor4_const;
#[path = "generated/test_process_xor4_value.generated.rs"]
mod test_process_xor4_value;
#[path = "generated/test_process_xor_const.generated.rs"]
mod test_process_xor_const;
#[path = "generated/test_process_xor_value.generated.rs"]
mod test_process_xor_value;
#[path = "generated/test_repeat_eos_bits_b1.generated.rs"]
mod test_repeat_eos_bits_b1;
#[path = "generated/test_repeat_eos_bits_b4.generated.rs"]
mod test_repeat_eos_bits_b4;
#[path = "generated/test_repeat_eos_bytes.generated.rs"]
mod test_repeat_eos_bytes;
#[path = "generated/test_repeat_eos_bytes_pad.generated.rs"]
mod test_repeat_eos_bytes_pad;
#[path = "generated/test_repeat_eos_bytes_pad_term.generated.rs"]
mod test_repeat_eos_bytes_pad_term;
#[path = "generated/test_repeat_eos_struct.generated.rs"]
mod test_repeat_eos_struct;
#[path = "generated/test_repeat_eos_term_bytes.generated.rs"]
mod test_repeat_eos_term_bytes;
#[path = "generated/test_repeat_eos_term_struct.generated.rs"]
mod test_repeat_eos_term_struct;
#[path = "generated/test_repeat_eos_u4.generated.rs"]
mod test_repeat_eos_u4;
#[path = "generated/test_repeat_n_bytes.generated.rs"]
mod test_repeat_n_bytes;
#[path = "generated/test_repeat_n_bytes_pad.generated.rs"]
mod test_repeat_n_bytes_pad;
#[path = "generated/test_repeat_n_bytes_pad_term.generated.rs"]
mod test_repeat_n_bytes_pad_term;
#[path = "generated/test_repeat_n_struct.generated.rs"]
mod test_repeat_n_struct;
#[path = "generated/test_repeat_n_strz.generated.rs"]
mod test_repeat_n_strz;
#[path = "generated/test_repeat_n_strz_double.generated.rs"]
mod test_repeat_n_strz_double;
#[path = "generated/test_repeat_n_term_bytes.generated.rs"]
mod test_repeat_n_term_bytes;
#[path = "generated/test_repeat_n_term_struct.generated.rs"]
mod test_repeat_n_term_struct;
#[path = "generated/test_repeat_until_bytes.generated.rs"]
mod test_repeat_until_bytes;
#[path = "generated/test_repeat_until_bytes_pad.generated.rs"]
mod test_repeat_until_bytes_pad;
#[path = "generated/test_repeat_until_bytes_pad_term.generated.rs"]
mod test_repeat_until_bytes_pad_term;
#[path = "generated/test_repeat_until_term_bytes.generated.rs"]
mod test_repeat_until_term_bytes;
#[path = "generated/test_repeat_until_term_struct.generated.rs"]
mod test_repeat_until_term_struct;
#[path = "generated/test_str_encodings.generated.rs"]
mod test_str_encodings;
#[path = "generated/test_str_encodings_default.generated.rs"]
mod test_str_encodings_default;
#[path = "generated/test_str_encodings_escaping_enc.generated.rs"]
mod test_str_encodings_escaping_enc;
#[path = "generated/test_str_encodings_escaping_to_s.generated.rs"]
mod test_str_encodings_escaping_to_s;
#[path = "generated/test_str_encodings_utf16.generated.rs"]
mod test_str_encodings_utf16;
#[path = "generated/test_str_eos.generated.rs"]
mod test_str_eos;
#[path = "generated/test_str_eos_pad_term.generated.rs"]
mod test_str_eos_pad_term;
#[path = "generated/test_str_eos_pad_term_empty.generated.rs"]
mod test_str_eos_pad_term_empty;
#[path = "generated/test_str_eos_pad_term_equal.generated.rs"]
mod test_str_eos_pad_term_equal;
#[path = "generated/test_str_literals2.generated.rs"]
mod test_str_literals2;
#[path = "generated/test_str_literals_latin1.generated.rs"]
mod test_str_literals_latin1;
#[path = "generated/test_str_pad_term.generated.rs"]
mod test_str_pad_term;
#[path = "generated/test_str_pad_term_empty.generated.rs"]
mod test_str_pad_term_empty;
#[path = "generated/test_str_pad_term_equal.generated.rs"]
mod test_str_pad_term_equal;
#[path = "generated/test_str_pad_term_roundtrip.generated.rs"]
mod test_str_pad_term_roundtrip;
#[path = "generated/test_str_pad_term_utf16.generated.rs"]
mod test_str_pad_term_utf16;
#[path = "generated/test_str_pad_term_zero_size.generated.rs"]
mod test_str_pad_term_zero_size;
#[path = "generated/test_struct_pad_term.generated.rs"]
mod test_struct_pad_term;
#[path = "generated/test_struct_pad_term_equal.generated.rs"]
mod test_struct_pad_term_equal;
#[path = "generated/test_switch_integers.generated.rs"]
mod test_switch_integers;
#[path = "generated/test_switch_multi_bool_ops.generated.rs"]
mod test_switch_multi_bool_ops;
#[path = "generated/test_term_bytes.generated.rs"]
mod test_term_bytes;
#[path = "generated/test_term_bytes2.generated.rs"]
mod test_term_bytes2;
#[path = "generated/test_term_bytes3.generated.rs"]
mod test_term_bytes3;
#[path = "generated/test_term_bytes4.generated.rs"]
mod test_term_bytes4;
#[path = "generated/test_term_struct.generated.rs"]
mod test_term_struct;
#[path = "generated/test_term_struct2.generated.rs"]
mod test_term_struct2;
#[path = "generated/test_term_struct3.generated.rs"]
mod test_term_struct3;
#[path = "generated/test_term_struct4.generated.rs"]
mod test_term_struct4;
#[path = "generated/test_term_strz.generated.rs"]
mod test_term_strz;
#[path = "generated/test_term_strz2.generated.rs"]
mod test_term_strz2;
#[path = "generated/test_term_strz3.generated.rs"]
mod test_term_strz3;
#[path = "generated/test_term_strz4.generated.rs"]
mod test_term_strz4;
#[path = "generated/test_term_strz_utf16_v1.generated.rs"]
mod test_term_strz_utf16_v1;
#[path = "generated/test_term_strz_utf16_v2.generated.rs"]
mod test_term_strz_utf16_v2;
#[path = "generated/test_term_strz_utf16_v3.generated.rs"]
mod test_term_strz_utf16_v3;
#[path = "generated/test_term_strz_utf16_v4.generated.rs"]
mod test_term_strz_utf16_v4;
#[path = "generated/test_term_u1_val.generated.rs"]
mod test_term_u1_val;
#[path = "generated/test_ts_packet_header.generated.rs"]
mod test_ts_packet_header;
#[path = "generated/test_type_int_unary_op.generated.rs"]
mod test_type_int_unary_op;
#[path = "generated/test_type_ternary.generated.rs"]
mod test_type_ternary;
#[path = "generated/test_type_ternary_2nd_falsy.generated.rs"]
mod test_type_ternary_2nd_falsy;
#[path = "generated/test_user_type.generated.rs"]
mod test_user_type;
#[path = "generated/test_valid_eq_str_encodings.generated.rs"]
mod test_valid_eq_str_encodings;
#[path = "generated/test_valid_fail_anyof_int.generated.rs"]
mod test_valid_fail_anyof_int;
#[path = "generated/test_valid_fail_contents.generated.rs"]
mod test_valid_fail_contents;
#[path = "generated/test_valid_fail_contents_inst.generated.rs"]
mod test_valid_fail_contents_inst;
#[path = "generated/test_valid_fail_eq_bytes.generated.rs"]
mod test_valid_fail_eq_bytes;
#[path = "generated/test_valid_fail_eq_int.generated.rs"]
mod test_valid_fail_eq_int;
#[path = "generated/test_valid_fail_eq_str.generated.rs"]
mod test_valid_fail_eq_str;
#[path = "generated/test_valid_fail_expr.generated.rs"]
mod test_valid_fail_expr;
#[path = "generated/test_valid_fail_in_enum.generated.rs"]
mod test_valid_fail_in_enum;
#[path = "generated/test_valid_fail_inst.generated.rs"]
mod test_valid_fail_inst;
#[path = "generated/test_valid_fail_max_int.generated.rs"]
mod test_valid_fail_max_int;
#[path = "generated/test_valid_fail_min_int.generated.rs"]
mod test_valid_fail_min_int;
#[path = "generated/test_valid_fail_range_bytes.generated.rs"]
mod test_valid_fail_range_bytes;
#[path = "generated/test_valid_fail_range_float.generated.rs"]
mod test_valid_fail_range_float;
#[path = "generated/test_valid_fail_range_int.generated.rs"]
mod test_valid_fail_range_int;
#[path = "generated/test_valid_fail_range_str.generated.rs"]
mod test_valid_fail_range_str;
#[path = "generated/test_valid_fail_repeat_anyof_int.generated.rs"]
mod test_valid_fail_repeat_anyof_int;
#[path = "generated/test_valid_fail_repeat_contents.generated.rs"]
mod test_valid_fail_repeat_contents;
#[path = "generated/test_valid_fail_repeat_eq_int.generated.rs"]
mod test_valid_fail_repeat_eq_int;
#[path = "generated/test_valid_fail_repeat_expr.generated.rs"]
mod test_valid_fail_repeat_expr;
#[path = "generated/test_valid_fail_repeat_inst.generated.rs"]
mod test_valid_fail_repeat_inst;
#[path = "generated/test_valid_fail_repeat_max_int.generated.rs"]
mod test_valid_fail_repeat_max_int;
#[path = "generated/test_valid_fail_repeat_min_int.generated.rs"]
mod test_valid_fail_repeat_min_int;
#[path = "generated/test_valid_long.generated.rs"]
mod test_valid_long;
#[path = "generated/test_valid_not_parsed_if.generated.rs"]
mod test_valid_not_parsed_if;
#[path = "generated/test_valid_optional_id.generated.rs"]
mod test_valid_optional_id;
#[path = "generated/test_valid_short.generated.rs"]
mod test_valid_short;
#[path = "generated/test_yaml_ints.generated.rs"]
mod test_yaml_ints;
#[path = "generated/test_zlib_surrounded.generated.rs"]
mod test_zlib_surrounded;
#[path = "generated/test_zlib_with_header_78.generated.rs"]
mod test_zlib_with_header_78;
