#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This file is part of Collective Toolbox, a database and document workspace and utilities.
# Copyright (C) 2026 Collective Toolbox Developers
# Contact: info@collectivetoolbox.com
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program.  If not, see <https://www.gnu.org/licenses/>.
set -euxo pipefail

cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/.." || exit 1


mkdir -p built/src

git archive HEAD -o built/src/src.zip
HASH_SRC="$(guix hash built/src/src.zip)"

tar -cf built/src/vendor.tar ./vendor
HASH_VENDOR="$(guix hash built/src/vendor.tar)"

cp packaging/guix/generated/ctoolbox-workspace-rust-crates.scm packaging/guix/generated/ctoolbox_1.scm
template="$(<packaging/guix/ctoolbox.scm)"

echo "${template//0placeholder1/"$HASH_SRC"}" >> packaging/guix/generated/ctoolbox_1.scm

template="$(<packaging/guix/generated/ctoolbox_1.scm)"
echo "${template//0placeholder2/"$HASH_VENDOR"}" > packaging/guix/generated/ctoolbox.scm
rm packaging/guix/generated/ctoolbox_1.scm

# Keep failed build directory:
# Note that you may have to delete the retained directory from /tmp manually, if
# later builds start failing.
# guix build -K -f packaging/guix/generated/ctoolbox.scm
guix build -f packaging/guix/generated/ctoolbox.scm

rm built/src/vendor.tar
