[package]
name = "ctb-formats-utilities"
edition = "2024"
build = "build.rs"

[lib]
path="utilities.rs"
crate-type = ["lib"]

[dependencies]
ctb-utilities = { path = "../../utilities" }
ctb-formats-dcdata = { path = "../dcdata" }

[build-dependencies]
anyhow = "1.0"
ctb-formats-dcdata = { path = "../dcdata" }

[lints]
workspace = true
