// SPDX-License-Identifier: AGPL-3.0-or-later
/*
This file is part of Collective Toolbox, a database and document workspace and utilities.
Copyright (C) 2026 Collective Toolbox Developers
Contact: info@collectivetoolbox.com

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along
with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

//! Centralized registry of file extension rules across format types.
//! @generated by ctb-build-support::extension_codegen from format category data tables.
//! Do not edit by hand.

use crate::detection::extension::ExtensionRule;
use crate::format_id::FormatId;
#[expect(
    unused_imports,
    clippy::wildcard_imports,
    reason = "Standard workspace module prelude"
)]
use ctb_utilities::*;

/// An entry associating a `FormatId` with an `ExtensionRule`.
#[derive(Debug, Clone, Copy)]
pub struct ExtensionEntry {
    pub format_id: FormatId,
    pub rule: ExtensionRule,
}

/// Global static registry of single file extension mappings.
pub static EXTENSION_REGISTRY: &[ExtensionEntry] = &[
    ExtensionEntry {
        format_id: FormatId::BaseNb,
        rule: ExtensionRule::insensitive("basenb"),
    },
    ExtensionEntry {
        format_id: FormatId::Base64Standard,
        rule: ExtensionRule::insensitive("b64"),
    },
    ExtensionEntry {
        format_id: FormatId::Base64Standard,
        rule: ExtensionRule::insensitive("base64"),
    },
    ExtensionEntry {
        format_id: FormatId::HexByteString,
        rule: ExtensionRule::insensitive("hex"),
    },
    ExtensionEntry {
        format_id: FormatId::Unknown,
        rule: ExtensionRule::insensitive("bin"),
    },
    ExtensionEntry {
        format_id: FormatId::Uuencode,
        rule: ExtensionRule::insensitive("uue"),
    },
    ExtensionEntry {
        format_id: FormatId::Uuencode,
        rule: ExtensionRule::insensitive("uu"),
    },
    ExtensionEntry {
        format_id: FormatId::YEnc,
        rule: ExtensionRule::insensitive("ync"),
    },
    ExtensionEntry {
        format_id: FormatId::YEnc,
        rule: ExtensionRule::insensitive("yenc"),
    },
    ExtensionEntry {
        format_id: FormatId::BinHex,
        rule: ExtensionRule::insensitive("hqx"),
    },
    ExtensionEntry {
        format_id: FormatId::BinHexTrs80,
        rule: ExtensionRule::insensitive("hex"),
    },
    ExtensionEntry {
        format_id: FormatId::BinHex2,
        rule: ExtensionRule::insensitive("hcx"),
    },
    ExtensionEntry {
        format_id: FormatId::MacBinary,
        rule: ExtensionRule::insensitive("bin"),
    },
    ExtensionEntry {
        format_id: FormatId::MacBinary,
        rule: ExtensionRule::insensitive("macbin"),
    },
    ExtensionEntry {
        format_id: FormatId::Xxencode,
        rule: ExtensionRule::insensitive("xxe"),
    },
    ExtensionEntry {
        format_id: FormatId::Xxencode,
        rule: ExtensionRule::insensitive("xx"),
    },
    ExtensionEntry {
        format_id: FormatId::Brotli,
        rule: ExtensionRule::insensitive("br"),
    },
    ExtensionEntry {
        format_id: FormatId::Gzip,
        rule: ExtensionRule::insensitive("gz"),
    },
    ExtensionEntry {
        format_id: FormatId::Gzip,
        rule: ExtensionRule::insensitive("gzip"),
    },
    ExtensionEntry {
        format_id: FormatId::Deflate,
        rule: ExtensionRule::insensitive("deflate"),
    },
    ExtensionEntry {
        format_id: FormatId::Zlib,
        rule: ExtensionRule::insensitive("zz"),
    },
    ExtensionEntry {
        format_id: FormatId::Zlib,
        rule: ExtensionRule::insensitive("zl"),
    },
    ExtensionEntry {
        format_id: FormatId::Bzip2,
        rule: ExtensionRule::insensitive("bz2"),
    },
    ExtensionEntry {
        format_id: FormatId::Bzip2,
        rule: ExtensionRule::insensitive("bzip2"),
    },
    ExtensionEntry {
        format_id: FormatId::Bzip,
        rule: ExtensionRule::insensitive("bz"),
    },
    ExtensionEntry {
        format_id: FormatId::Bzip,
        rule: ExtensionRule::insensitive("bzip"),
    },
    ExtensionEntry {
        format_id: FormatId::Zstd,
        rule: ExtensionRule::insensitive("zst"),
    },
    ExtensionEntry {
        format_id: FormatId::Zstd,
        rule: ExtensionRule::insensitive("zstd"),
    },
    ExtensionEntry {
        format_id: FormatId::Lzip,
        rule: ExtensionRule::insensitive("lz"),
    },
    ExtensionEntry {
        format_id: FormatId::Lzip,
        rule: ExtensionRule::insensitive("lzip"),
    },
    ExtensionEntry {
        format_id: FormatId::Xz,
        rule: ExtensionRule::insensitive("xz"),
    },
    ExtensionEntry {
        format_id: FormatId::ScoCompress,
        rule: ExtensionRule::sensitive("Z"),
    },
    ExtensionEntry {
        format_id: FormatId::CompressLzw,
        rule: ExtensionRule::sensitive("Z"),
    },
    ExtensionEntry {
        format_id: FormatId::CompressLzw1,
        rule: ExtensionRule::sensitive("Z"),
    },
    ExtensionEntry {
        format_id: FormatId::CompressLzw16,
        rule: ExtensionRule::sensitive("Z"),
    },
    ExtensionEntry {
        format_id: FormatId::CompressLzw2,
        rule: ExtensionRule::sensitive("Z"),
    },
    ExtensionEntry {
        format_id: FormatId::Pack,
        rule: ExtensionRule::sensitive("z"),
    },
    ExtensionEntry {
        format_id: FormatId::OldPack,
        rule: ExtensionRule::sensitive("z"),
    },
    ExtensionEntry {
        format_id: FormatId::Compact,
        rule: ExtensionRule::sensitive("C"),
    },
    ExtensionEntry {
        format_id: FormatId::Lz4,
        rule: ExtensionRule::insensitive("lz4"),
    },
    ExtensionEntry {
        format_id: FormatId::Lzo,
        rule: ExtensionRule::insensitive("lzo"),
    },
    ExtensionEntry {
        format_id: FormatId::Lzma,
        rule: ExtensionRule::insensitive("lzma"),
    },
    ExtensionEntry {
        format_id: FormatId::Lzma2,
        rule: ExtensionRule::insensitive("lzma"),
    },
    ExtensionEntry {
        format_id: FormatId::Lzma2,
        rule: ExtensionRule::insensitive("lzma2"),
    },
    ExtensionEntry {
        format_id: FormatId::Tar,
        rule: ExtensionRule::insensitive("tar"),
    },
    ExtensionEntry {
        format_id: FormatId::Zip,
        rule: ExtensionRule::insensitive("zip"),
    },
    ExtensionEntry {
        format_id: FormatId::CtbAssetBundle,
        rule: ExtensionRule::insensitive("rsrc"),
    },
    ExtensionEntry {
        format_id: FormatId::Shar,
        rule: ExtensionRule::insensitive("shar"),
    },
    ExtensionEntry {
        format_id: FormatId::Cpio,
        rule: ExtensionRule::insensitive("cpio"),
    },
    ExtensionEntry {
        format_id: FormatId::Pax,
        rule: ExtensionRule::insensitive("pax"),
    },
    ExtensionEntry {
        format_id: FormatId::TarGz,
        rule: ExtensionRule::insensitive("tar.gz"),
    },
    ExtensionEntry {
        format_id: FormatId::TarGz,
        rule: ExtensionRule::insensitive("tgz"),
    },
    ExtensionEntry {
        format_id: FormatId::TarZ,
        rule: ExtensionRule::insensitive("tar.Z"),
    },
    ExtensionEntry {
        format_id: FormatId::TarZ,
        rule: ExtensionRule::insensitive("taz"),
    },
    ExtensionEntry {
        format_id: FormatId::TarBz2,
        rule: ExtensionRule::insensitive("tar.bz2"),
    },
    ExtensionEntry {
        format_id: FormatId::TarBz2,
        rule: ExtensionRule::insensitive("tbz2"),
    },
    ExtensionEntry {
        format_id: FormatId::TarLzo,
        rule: ExtensionRule::insensitive("tar.lzo"),
    },
    ExtensionEntry {
        format_id: FormatId::TarLzo,
        rule: ExtensionRule::insensitive("tzo"),
    },
    ExtensionEntry {
        format_id: FormatId::CtbAssetBundleV1,
        rule: ExtensionRule::insensitive("rsrc"),
    },
    ExtensionEntry {
        format_id: FormatId::CtbAssetBundleV2,
        rule: ExtensionRule::insensitive("rsrc"),
    },
    ExtensionEntry {
        format_id: FormatId::CtbAssetBundleV3,
        rule: ExtensionRule::insensitive("rsrc"),
    },
    ExtensionEntry {
        format_id: FormatId::CtbAssetBundleV4,
        rule: ExtensionRule::insensitive("rsrc"),
    },
    ExtensionEntry {
        format_id: FormatId::CtbFileMetadataJson,
        rule: ExtensionRule::insensitive("json"),
    },
    ExtensionEntry {
        format_id: FormatId::Csv,
        rule: ExtensionRule::insensitive("csv"),
    },
    ExtensionEntry {
        format_id: FormatId::Tsv,
        rule: ExtensionRule::insensitive("tsv"),
    },
    ExtensionEntry {
        format_id: FormatId::Ssv,
        rule: ExtensionRule::insensitive("ssv"),
    },
    ExtensionEntry {
        format_id: FormatId::Json,
        rule: ExtensionRule::insensitive("json"),
    },
    ExtensionEntry {
        format_id: FormatId::Jsonc,
        rule: ExtensionRule::insensitive("json"),
    },
    ExtensionEntry {
        format_id: FormatId::Xml,
        rule: ExtensionRule::insensitive("xml"),
    },
    ExtensionEntry {
        format_id: FormatId::Warc,
        rule: ExtensionRule::insensitive("warc"),
    },
    ExtensionEntry {
        format_id: FormatId::Pan,
        rule: ExtensionRule::insensitive("pan"),
    },
    ExtensionEntry {
        format_id: FormatId::Sqlite,
        rule: ExtensionRule::insensitive("sqlite"),
    },
    ExtensionEntry {
        format_id: FormatId::IaMetaJson,
        rule: ExtensionRule::insensitive("json"),
    },
    ExtensionEntry {
        format_id: FormatId::Pem,
        rule: ExtensionRule::insensitive("pem"),
    },
    ExtensionEntry {
        format_id: FormatId::Pem,
        rule: ExtensionRule::insensitive("crt"),
    },
    ExtensionEntry {
        format_id: FormatId::Pkcs8PrivateKey,
        rule: ExtensionRule::insensitive("p8"),
    },
    ExtensionEntry {
        format_id: FormatId::Pkcs8PrivateKey,
        rule: ExtensionRule::insensitive("key"),
    },
    ExtensionEntry {
        format_id: FormatId::Pkcs10Csr,
        rule: ExtensionRule::insensitive("p10"),
    },
    ExtensionEntry {
        format_id: FormatId::Pkcs10Csr,
        rule: ExtensionRule::insensitive("csr"),
    },
    ExtensionEntry {
        format_id: FormatId::PkixCert,
        rule: ExtensionRule::insensitive("cer"),
    },
    ExtensionEntry {
        format_id: FormatId::PkixCert,
        rule: ExtensionRule::insensitive("crt"),
    },
    ExtensionEntry {
        format_id: FormatId::PkixCrl,
        rule: ExtensionRule::insensitive("crl"),
    },
    ExtensionEntry {
        format_id: FormatId::Pkcs7Mime,
        rule: ExtensionRule::insensitive("p7c"),
    },
    ExtensionEntry {
        format_id: FormatId::Pkcs7Mime,
        rule: ExtensionRule::insensitive("p7b"),
    },
    ExtensionEntry {
        format_id: FormatId::Pkcs7Mime,
        rule: ExtensionRule::insensitive("spc"),
    },
    ExtensionEntry {
        format_id: FormatId::Pkcs7Mime,
        rule: ExtensionRule::insensitive("p7r"),
    },
    ExtensionEntry {
        format_id: FormatId::Pkcs12,
        rule: ExtensionRule::insensitive("p12"),
    },
    ExtensionEntry {
        format_id: FormatId::Pkcs12,
        rule: ExtensionRule::insensitive("pfx"),
    },
    ExtensionEntry {
        format_id: FormatId::CscJournal,
        rule: ExtensionRule::insensitive("cscjournal"),
    },
    ExtensionEntry {
        format_id: FormatId::CscDesc,
        rule: ExtensionRule::insensitive("cscdesc"),
    },
    ExtensionEntry {
        format_id: FormatId::CscIndex,
        rule: ExtensionRule::insensitive("cscindex.sqlite"),
    },
    ExtensionEntry {
        format_id: FormatId::CscIndexMeta,
        rule: ExtensionRule::insensitive("cscidxmeta"),
    },
    ExtensionEntry {
        format_id: FormatId::Redb,
        rule: ExtensionRule::insensitive("redb"),
    },
    ExtensionEntry {
        format_id: FormatId::Videoterminal,
        rule: ExtensionRule::insensitive("txt"),
    },
    ExtensionEntry {
        format_id: FormatId::Teleprinter,
        rule: ExtensionRule::insensitive("txt"),
    },
    ExtensionEntry {
        format_id: FormatId::DcIntegerList,
        rule: ExtensionRule::insensitive("dcil"),
    },
    ExtensionEntry {
        format_id: FormatId::Html,
        rule: ExtensionRule::insensitive("htm"),
    },
    ExtensionEntry {
        format_id: FormatId::Html,
        rule: ExtensionRule::insensitive("html"),
    },
    ExtensionEntry {
        format_id: FormatId::Sems,
        rule: ExtensionRule::insensitive("sems"),
    },
    ExtensionEntry {
        format_id: FormatId::HtmlFragment,
        rule: ExtensionRule::insensitive("htmfrag"),
    },
    ExtensionEntry {
        format_id: FormatId::Text,
        rule: ExtensionRule::insensitive("txt"),
    },
    ExtensionEntry {
        format_id: FormatId::Elad,
        rule: ExtensionRule::insensitive("elad"),
    },
    ExtensionEntry {
        format_id: FormatId::EiteColorCoded,
        rule: ExtensionRule::insensitive("htm"),
    },
    ExtensionEntry {
        format_id: FormatId::Pdf,
        rule: ExtensionRule::insensitive("pdf"),
    },
    ExtensionEntry {
        format_id: FormatId::Markdown,
        rule: ExtensionRule::insensitive("md"),
    },
    ExtensionEntry {
        format_id: FormatId::Troff,
        rule: ExtensionRule::insensitive("troff"),
    },
    ExtensionEntry {
        format_id: FormatId::Rss,
        rule: ExtensionRule::insensitive("rss"),
    },
    ExtensionEntry {
        format_id: FormatId::Rss09,
        rule: ExtensionRule::insensitive("rdf"),
    },
    ExtensionEntry {
        format_id: FormatId::Rss091Netscape,
        rule: ExtensionRule::insensitive("xml"),
    },
    ExtensionEntry {
        format_id: FormatId::Rss091UserLand,
        rule: ExtensionRule::insensitive("xml"),
    },
    ExtensionEntry {
        format_id: FormatId::Rss092,
        rule: ExtensionRule::insensitive("xml"),
    },
    ExtensionEntry {
        format_id: FormatId::Rss1,
        rule: ExtensionRule::insensitive("xml"),
    },
    ExtensionEntry {
        format_id: FormatId::ScriptingNews10,
        rule: ExtensionRule::insensitive("xml"),
    },
    ExtensionEntry {
        format_id: FormatId::ScriptingNews20,
        rule: ExtensionRule::insensitive("xml"),
    },
    ExtensionEntry {
        format_id: FormatId::Atom,
        rule: ExtensionRule::insensitive("atom"),
    },
    ExtensionEntry {
        format_id: FormatId::HAtom,
        rule: ExtensionRule::insensitive("html"),
    },
    ExtensionEntry {
        format_id: FormatId::JsonFeed11,
        rule: ExtensionRule::insensitive("json"),
    },
    ExtensionEntry {
        format_id: FormatId::Mime,
        rule: ExtensionRule::insensitive("eml"),
    },
    ExtensionEntry {
        format_id: FormatId::Mime,
        rule: ExtensionRule::insensitive("mim"),
    },
    ExtensionEntry {
        format_id: FormatId::Mime,
        rule: ExtensionRule::insensitive("mime"),
    },
    ExtensionEntry {
        format_id: FormatId::OutlookMsg,
        rule: ExtensionRule::insensitive("msg"),
    },
    ExtensionEntry {
        format_id: FormatId::AppleSingle,
        rule: ExtensionRule::insensitive("as"),
    },
    ExtensionEntry {
        format_id: FormatId::AppleDouble,
        rule: ExtensionRule::insensitive("ADF"),
    },
    ExtensionEntry {
        format_id: FormatId::AppleDouble,
        rule: ExtensionRule::insensitive("rsrc"),
    },
    ExtensionEntry {
        format_id: FormatId::CtbNode,
        rule: ExtensionRule::insensitive("ctbn"),
    },
    ExtensionEntry {
        format_id: FormatId::CtbNodeV1,
        rule: ExtensionRule::insensitive("ctbn"),
    },
    ExtensionEntry {
        format_id: FormatId::CtbNodeV2,
        rule: ExtensionRule::insensitive("ctbn"),
    },
    ExtensionEntry {
        format_id: FormatId::Dcal,
        rule: ExtensionRule::insensitive("dcal"),
    },
    ExtensionEntry {
        format_id: FormatId::Csdl,
        rule: ExtensionRule::insensitive("csdl"),
    },
    ExtensionEntry {
        format_id: FormatId::Dcts,
        rule: ExtensionRule::insensitive("dcts"),
    },
    ExtensionEntry {
        format_id: FormatId::DcMixed,
        rule: ExtensionRule::insensitive("dcmm"),
    },
    ExtensionEntry {
        format_id: FormatId::Utf8,
        rule: ExtensionRule::insensitive("txt"),
    },
    ExtensionEntry {
        format_id: FormatId::Utf8,
        rule: ExtensionRule::insensitive("utf8"),
    },
    ExtensionEntry {
        format_id: FormatId::AsciiSafeSubset,
        rule: ExtensionRule::insensitive("txt"),
    },
    ExtensionEntry {
        format_id: FormatId::AsciiSafeSubset,
        rule: ExtensionRule::insensitive("ascii"),
    },
    ExtensionEntry {
        format_id: FormatId::Ascii,
        rule: ExtensionRule::insensitive("txt"),
    },
    ExtensionEntry {
        format_id: FormatId::Ascii,
        rule: ExtensionRule::insensitive("ascii"),
    },
    ExtensionEntry {
        format_id: FormatId::Elf,
        rule: ExtensionRule::insensitive("axf"),
    },
    ExtensionEntry {
        format_id: FormatId::Elf,
        rule: ExtensionRule::insensitive("bin"),
    },
    ExtensionEntry {
        format_id: FormatId::Elf,
        rule: ExtensionRule::insensitive("elf"),
    },
    ExtensionEntry {
        format_id: FormatId::Elf,
        rule: ExtensionRule::insensitive("o"),
    },
    ExtensionEntry {
        format_id: FormatId::Elf,
        rule: ExtensionRule::insensitive("out"),
    },
    ExtensionEntry {
        format_id: FormatId::Elf,
        rule: ExtensionRule::insensitive("prx"),
    },
    ExtensionEntry {
        format_id: FormatId::Elf,
        rule: ExtensionRule::insensitive("puff"),
    },
    ExtensionEntry {
        format_id: FormatId::Elf,
        rule: ExtensionRule::insensitive("ko"),
    },
    ExtensionEntry {
        format_id: FormatId::Elf,
        rule: ExtensionRule::insensitive("mod"),
    },
    ExtensionEntry {
        format_id: FormatId::Elf,
        rule: ExtensionRule::insensitive("so"),
    },
    ExtensionEntry {
        format_id: FormatId::Elf,
        rule: ExtensionRule::insensitive("AppImage"),
    },
    ExtensionEntry {
        format_id: FormatId::Pe,
        rule: ExtensionRule::insensitive("exe"),
    },
    ExtensionEntry {
        format_id: FormatId::Pe,
        rule: ExtensionRule::insensitive("com"),
    },
    ExtensionEntry {
        format_id: FormatId::Pe,
        rule: ExtensionRule::insensitive("dll"),
    },
    ExtensionEntry {
        format_id: FormatId::Pe,
        rule: ExtensionRule::insensitive("sys"),
    },
    ExtensionEntry {
        format_id: FormatId::Pe,
        rule: ExtensionRule::insensitive("acm"),
    },
    ExtensionEntry {
        format_id: FormatId::Pe,
        rule: ExtensionRule::insensitive("ax"),
    },
    ExtensionEntry {
        format_id: FormatId::Pe,
        rule: ExtensionRule::insensitive("cpl"),
    },
    ExtensionEntry {
        format_id: FormatId::Pe,
        rule: ExtensionRule::insensitive("drv"),
    },
    ExtensionEntry {
        format_id: FormatId::Pe,
        rule: ExtensionRule::insensitive("efi"),
    },
    ExtensionEntry {
        format_id: FormatId::Pe,
        rule: ExtensionRule::insensitive("ime"),
    },
    ExtensionEntry {
        format_id: FormatId::Pe,
        rule: ExtensionRule::insensitive("mui"),
    },
    ExtensionEntry {
        format_id: FormatId::Pe,
        rule: ExtensionRule::insensitive("ocx"),
    },
    ExtensionEntry {
        format_id: FormatId::Pe,
        rule: ExtensionRule::insensitive("scr"),
    },
    ExtensionEntry {
        format_id: FormatId::Pe,
        rule: ExtensionRule::insensitive("tsp"),
    },
    ExtensionEntry {
        format_id: FormatId::Pe,
        rule: ExtensionRule::insensitive("msstyles"),
    },
    ExtensionEntry {
        format_id: FormatId::MachO,
        rule: ExtensionRule::insensitive("o"),
    },
    ExtensionEntry {
        format_id: FormatId::MachO,
        rule: ExtensionRule::insensitive("dylib"),
    },
    ExtensionEntry {
        format_id: FormatId::MachO,
        rule: ExtensionRule::insensitive("kext"),
    },
    ExtensionEntry {
        format_id: FormatId::DebianPackage,
        rule: ExtensionRule::insensitive("deb"),
    },
    ExtensionEntry {
        format_id: FormatId::Lnk,
        rule: ExtensionRule::insensitive("lnk"),
    },
    ExtensionEntry {
        format_id: FormatId::Lnk,
        rule: ExtensionRule::insensitive("url"),
    },
    ExtensionEntry {
        format_id: FormatId::Lnk,
        rule: ExtensionRule::insensitive("cda"),
    },
    ExtensionEntry {
        format_id: FormatId::Torrent,
        rule: ExtensionRule::insensitive("torrent"),
    },
    ExtensionEntry {
        format_id: FormatId::JavaScript,
        rule: ExtensionRule::insensitive("js"),
    },
    ExtensionEntry {
        format_id: FormatId::StageL,
        rule: ExtensionRule::insensitive("stagel"),
    },
    ExtensionEntry {
        format_id: FormatId::StageL2,
        rule: ExtensionRule::insensitive("sl"),
    },
    ExtensionEntry {
        format_id: FormatId::StageL2Intermediate,
        rule: ExtensionRule::insensitive("sli"),
    },
    ExtensionEntry {
        format_id: FormatId::ActionScript,
        rule: ExtensionRule::insensitive("as"),
    },
    ExtensionEntry {
        format_id: FormatId::DcBasenb,
        rule: ExtensionRule::insensitive("dcbnb"),
    },
    ExtensionEntry {
        format_id: FormatId::Vt100,
        rule: ExtensionRule::insensitive("vt100"),
    },
];

/// Helper to lookup `FormatId` from a single extension string.
pub fn lookup_format_by_extension(ext: &str) -> Vec<FormatId> {
    let mut matches = Vec::new();
    for entry in EXTENSION_REGISTRY {
        if entry.rule.matches_extension(ext) && !matches.contains(&entry.format_id) {
            matches.push(entry.format_id);
        }
    }
    matches
}

/// Returns all extension rules associated with the given `FormatId`.
pub fn extension_rules_for_format(format_id: FormatId) -> Vec<ExtensionRule> {
    EXTENSION_REGISTRY
        .iter()
        .filter(|entry| entry.format_id == format_id)
        .map(|entry| entry.rule)
        .collect()
}

/// Returns the primary (first registered) extension for the given `FormatId`.
pub fn primary_extension_for_format(format_id: FormatId) -> Option<&'static str> {
    EXTENSION_REGISTRY
        .iter()
        .find(|entry| entry.format_id == format_id)
        .map(|entry| entry.rule.extension)
}
