[package]
name = "ctb-formats-warc"
edition = "2024"

[lib]
path="warc.rs"
crate-type = ["lib"]

[dependencies]
ctb-utilities = { path = "../../utilities" }
warcat = { path = "../../../vendor/warcat", features = ["bin"] }
clap = { version = "4.5.54", features = ["cargo", "derive"] }

fancy-regex = "0.17.0"
once_cell = "1.21.3"

[lints]
workspace = true

[dev-dependencies]
tempfile = "3.27.0"
