name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  ci:
    name: Run CI
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/collectivetoolbox/collectivetoolbox-2026-jul-25:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run CI script
        run: ./ci
