[package]
name = "ctb-formats-text-extraction"
edition = "2024"

[lib]
path = "text_extraction.rs"
crate-type = ["lib"]

[dependencies]
ctb-utilities = { path = "../../utilities" }
ctb-formats-utilities = { path = "../utilities" }
ctb-formats-wfscan = { path = "../wfscan" }
anyhow = "1.0"

[dev-dependencies]
tempfile = "3.27"

[lints]
workspace = true
